; Generated by Coffee-AHK/0.0.43
global __ci_shell__ := Func("shell_241")
global $ := {}
$.abs := Func("shell_240")
$.activate := Func("shell_239")
$.add := Func("shell_238")
$.alert := Func("shell_237")
$.beep := Func("shell_235")
$.bind := Func("shell_234")
$.blockInput := Func("shell_233")
$.ceil := Func("shell_232")
$.chunk := Func("shell_231")
$.clearInterval := Func("shell_230")
$.clearTimeout := Func("shell_229")
$.click := Func("shell_228")
$.clone := Func("shell_227")
$.close := Func("shell_226")
$.compact := Func("shell_225")
$.concat := Func("shell_223")
$.confirm := Func("shell_222")
global __iDebounce__ := 0
global __tDebounce__ := {}
$.debounce := Func("shell_221")
$.defer := Func("shell_219")
$.delay := Func("shell_217")
$.drop := Func("shell_215")
$.each := Func("shell_213")
class EmitterShell {
  bus := []
  emit := Func("shell_212").Bind(__filter__).Bind(this)
  off := Func("shell_207").Bind(this)
  on := Func("shell_204").Bind(this)
  once := Func("shell_203").Bind(this)
}
$.emitter := Func("shell_202")
global __eq__ := Func("shell_201")
$.eq := __eq__
$.exec := Func("shell_200")
$.exit := Func("shell_199")
class FileShellX {
  name := ""
  __New(name) {
    this.name := name
  }
  append := Func("shell_198").Bind(this)
  exist := Func("shell_197").Bind(this)
  delete := Func("shell_196").Bind(this)
  load := Func("shell_195").Bind(this)
  save := Func("shell_194").Bind(this)
}
$.file := Func("shell_193")
$.filter := Func("shell_192")
$.findColor := Func("shell_191")
$.findImage := Func("shell_190")
$.first := Func("shell_189")
$.head := $.first
$.floor := Func("shell_188")
$.forEach := Func("shell_187")
$.formatHotkey := Func("shell_186")
global __formatKeyFormatHotkey__ := Func("shell_185")
global __pickPrefixFormatHotkey__ := Func("shell_184")
$.get := Func("shell_183")
$.getColor := Func("shell_182")
$.getPosition := Func("shell_181")
$.getState := Func("shell_180")
$.gt := Func("shell_179")
$.gte := Func("shell_178")
$.i := Func("shell_177")
$.includes := Func("shell_176")
$.info := Func("shell_175")
$.isActive := Func("shell_174")
$.isArray := Func("shell_173")
$.isExist := Func("shell_172")
$.isFunction := Func("shell_171")
$.isNumber := Func("shell_170")
$.isObject := Func("shell_169")
$.isString := Func("shell_168")
$.join := Func("shell_167")
class KeyBindingShellX {
  mapBound := {}
  mapCallback := {}
  add := Func("shell_166").Bind(this)
  fire := Func("shell_165").Bind(this)
  init := Func("shell_162").Bind(this)
  off := Func("shell_160").Bind(this)
  on := Func("shell_159").Bind(this)
  remove := Func("shell_158").Bind(this)
}
global keyBindingShell := new KeyBindingShellX()
$.off := keyBindingShell.remove
$.on := keyBindingShell.add
$.trigger := keyBindingShell.fire
$.keys := Func("shell_156")
$.last := Func("shell_155")
$.length := Func("shell_154")
$.lt := Func("shell_153")
$.lte := Func("shell_152")
$.map := Func("shell_151")
$.maximize := Func("shell_150")
$.minimize := Func("shell_149")
$.mixin := Func("shell_148")
$.mod := Func("shell_147")
$.move := Func("shell_146")
$.noop := Func("shell_145")
$.now := Func("shell_144")
$.nth := Func("shell_143")
global __cacheOnce__ := {}
global __indexOnce__ := 0
$.once := Func("shell_142")
$.open := Func("shell_140")
$.play := Func("shell_139")
$.pop := Func("shell_138")
$.press := Func("shell_137")
global __formatInputPress__ := Func("shell_136")
global __validateInputPress__ := Func("shell_135")
$.push := Func("shell_134")
$.random := Func("shell_133")
$.range := Func("shell_132")
$.reload := Func("shell_131")
$.replace := Func("shell_130")
$.reverse := Func("shell_129")
$.round := Func("shell_128")
$.setFixed := Func("shell_127")
$.setInterval := Func("shell_126")
$.setStyle := Func("shell_125")
$.setTimeout := Func("shell_124")
$.shift := Func("shell_123")
$.shuffle := Func("shell_122").Bind(__split__)
$.sleep := Func("shell_121")
$.slice := Func("shell_120")
global __pickArgumentSlice__ := Func("shell_119")
$.sort := Func("shell_118")
$.split := Func("shell_117")
$.startsWith := Func("shell_116")
$.subString := Func("shell_115")
$.sum := Func("shell_114")
$.suspend := Func("shell_113")
$.tail := Func("shell_112")
$.take := Func("shell_111")
global __iThrottle__ := 0
global __tThrottle__ := {}
global __tsThrottle__ := {}
$.throttle := Func("shell_110")
$.toLowerCase := Func("shell_107")
$.toLower := $.toLowerCase
$.toString := Func("shell_106")
$.toUpperCase := Func("shell_105")
$.toUpper := $.toUpperCase
$.trim := Func("shell_104")
$.trimEnd := Func("shell_103")
$.trimStart := Func("shell_102")
$.type := Func("shell_101")
$.uniq := Func("shell_100")
$.unshift := Func("shell_99")
$.values := Func("shell_98")
$.VERSION := "0.0.21"
$.wait := Func("shell_97")
(Func("shell_96")).Call()
(Func("shell_95")).Call()
(Func("shell_93")).Call()
(Func("shell_92")).Call()
(Func("shell_91")).Call()
(Func("shell_90")).Call()
(Func("shell_89")).Call()
(Func("shell_88")).Call()
(Func("shell_87")).Call()
(Func("shell_85")).Call()
(Func("shell_84")).Call()
(Func("shell_83")).Call()
(Func("shell_82")).Call()
(Func("shell_81")).Call()
(Func("shell_80")).Call()
(Func("shell_79")).Call()
(Func("shell_78")).Call()
(Func("shell_77")).Call()
(Func("shell_76")).Call()
(Func("shell_75")).Call()
(Func("shell_74")).Call()
(Func("shell_73")).Call()
(Func("shell_72")).Call()
(Func("shell_70")).Call()
(Func("shell_69")).Call()
(Func("shell_68")).Call()
(Func("shell_67")).Call()
(Func("shell_66")).Call()
(Func("shell_65")).Call()
(Func("shell_64")).Call()
(Func("shell_62")).Call()
(Func("shell_61")).Call()
(Func("shell_60")).Call()
(Func("shell_59")).Call()
(Func("shell_58")).Call()
(Func("shell_56")).Call()
(Func("shell_55")).Call()
(Func("shell_54")).Call()
(Func("shell_53")).Call()
(Func("shell_52")).Call()
(Func("shell_51")).Call()
(Func("shell_50")).Call()
(Func("shell_49")).Call()
(Func("shell_48")).Call()
(Func("shell_47")).Call()
(Func("shell_46")).Call()
(Func("shell_45")).Call()
(Func("shell_44")).Call()
(Func("shell_43")).Call()
(Func("shell_42")).Call()
(Func("shell_41")).Call()
(Func("shell_40")).Call()
(Func("shell_39")).Call()
(Func("shell_38")).Call()
(Func("shell_36")).Call()
(Func("shell_35")).Call()
(Func("shell_34")).Call()
(Func("shell_33")).Call()
(Func("shell_32")).Call()
(Func("shell_31")).Call()
(Func("shell_30")).Call()
(Func("shell_29")).Call()
(Func("shell_28")).Call()
(Func("shell_27")).Call()
(Func("shell_26")).Call()
(Func("shell_25")).Call()
(Func("shell_23")).Call()
(Func("shell_22")).Call()
(Func("shell_20")).Call()
(Func("shell_19")).Call()
(Func("shell_18")).Call()
(Func("shell_17")).Call()
(Func("shell_16")).Call()
(Func("shell_15")).Call()
(Func("shell_14")).Call()
(Func("shell_12")).Call()
(Func("shell_11")).Call()
(Func("shell_10")).Call()
(Func("shell_9")).Call()
(Func("shell_8")).Call()
(Func("shell_7")).Call()
(Func("shell_6")).Call()
(Func("shell_5")).Call()
(Func("shell_4")).Call()
(Func("shell_3")).Call()
(Func("shell_2")).Call()
(Func("shell_1")).Call()
shell_1() {
  if !(($.type.Call($.wait)) == "function") {
    throw 0
  }
}
shell_2() {
  list := [0]
  $.unshift.Call(list, 1)
  if !(list[1] == 1) {
    throw 0
  }
  len := $.unshift.Call(list, 2, 3, 4)
  if !(len == 5) {
    throw 1
  }
  if !(list[1] == 2) {
    throw 2
  }
  if !(list[4] == 1) {
    throw 3
  }
}
shell_3() {
  type := $.type.Call(42)
  if !(type == "number") {
    throw Exception(type)
  }
  type := $.type.Call($.type)
  if !(type == "function") {
    throw Exception(type)
  }
  type := $.type.Call([1, 2, 3])
  if !(type == "array") {
    throw Exception(type)
  }
  type := $.type.Call({a: 1, b: 2, c: 3})
  if !(type == "object") {
    throw Exception(type)
  }
  type := $.type.Call({0: ""})
  if !(type == "object") {
    throw Exception(type)
  }
  type := $.type.Call({0: "", 1: "a", 2: "b", 3: "c"})
  if !(type == "object") {
    throw Exception(type)
  }
}
shell_4() {
  string := "string"
  result := $.subString.Call(string, 0)
  if !(result == string) {
    throw result
  }
  result := $.subString.Call(string, 1)
  if !(result == "tring") {
    throw result
  }
  result := $.subString.Call(string, 1, 2)
  if !(result == "t") {
    throw result
  }
  result := $.subString.Call(string, 3, 5)
  if !(result == "in") {
    throw result
  }
}
shell_5() {
  string := "string"
  result := $.startsWith.Call(string, "s")
  if !(result) {
    throw 1
  }
  result := $.startsWith.Call(string, "t")
  if (result) {
    throw 2
  }
}
shell_6() {
  list := [0, 1, 2]
  first := $.shift.Call(list)
  if !(first == 0) {
    throw 0
  }
  if !(list[1] == 1 && list[2] == 2) {
    throw 1
  }
}
shell_7() {
  if !(($.type.Call($.setStyle)) == "function") {
    throw 0
  }
}
shell_8() {
  list := [0]
  $.push.Call(list, 1)
  if !(list[2] == 1) {
    throw 0
  }
  len := $.push.Call(list, 2, 3, 4)
  if !(len == 5) {
    throw 1
  }
  if !(list[3] == 2) {
    throw 2
  }
  if !(list[5] == 4) {
    throw 3
  }
}
shell_9() {
  if !(($.type.Call($.press)) == "function") {
    throw 0
  }
}
shell_10() {
  list := [0, 1, 2]
  last := $.pop.Call(list)
  if !(last == 2) {
    throw 0
  }
  if !(list[1] == 0 && list[2] == 1) {
    throw 1
  }
}
shell_11() {
  if !(($.type.Call($.play)) == "function") {
    throw 0
  }
}
shell_12() {
  if !(($.type.Call($.open)) == "function") {
    throw 0
  }
}
shell_13(map) {
  map.n += 1
}
shell_14() {
  map := {n: 0}
  add := $.once.Call(Func("shell_13").Bind(map))
  add.Call()
  if !(map.n == 1) {
    throw 0
  }
  add.Call()
  if !(map.n == 1) {
    throw 1
  }
}
shell_15() {
  list := [0, 1, 2, 3]
  n := $.nth.Call(list, 0)
  if !(n == 0) {
    throw n
  }
  n := $.nth.Call(list, 1)
  if !(n == 1) {
    throw n
  }
  n := $.nth.Call(list, -1)
  if !(n == 3) {
    throw n
  }
}
shell_16() {
  now := $.now.Call()
  if !(($.type.Call(now)) == "number") {
    throw 0
  }
}
shell_17() {
  if !(($.type.Call($.noop)) == "function") {
    throw 0
  }
}
shell_18() {
  $.move.Call([100, 100])
  __array__ := $.getPosition.Call()
  x := __array__[1]
  y := __array__[2]
  if !(x == 100 && y == 100) {
    throw 0
  }
}
shell_19() {
  n := $.mod.Call(5, 2)
  if !(n == 1) {
    throw n
  }
  n := $.mod.Call(7, 5)
  if !(n == 2) {
    throw n
  }
}
shell_20() {
  mapA := {a: 1}
  mapB := {b: 2}
  mapC := {c: 3}
  $.mixin.Call(mapA, mapB, mapC)
  result := $.join.Call($.keys.Call(mapA))
  if !(result == "a,b,c") {
    throw 1
  }
  result := $.join.Call($.values.Call(mapA))
  if !(result == "1,2,3") {
    throw 2
  }
}
shell_21(name) {
  isActive := $.isActive.Call(name)
  if !(isActive) {
    throw 1
  }
  $.minimize.Call(name)
  isActive := $.isActive.Call(name)
  if (isActive) {
    throw 2
  }
  $.close.Call(name)
}
shell_22() {
  if !(($.type.Call($.minimize)) == "function") {
    throw 0
  }
  name := "notepad.exe"
  $.close.Call(name)
  $.open.Call(name)
  $.wait.Call(name, Func("shell_21").Bind(name))
}
shell_23() {
  if !(($.type.Call($.maximize)) == "function") {
    throw 0
  }
}
shell_24(n) {
  return n + 1
}
shell_25() {
  list := [1, 2, 3]
  result := $.join.Call($.map.Call(list, Func("shell_24")))
  if !(result == "2,3,4") {
    throw 0
  }
}
shell_26() {
  result := $.lte.Call(1, 2)
  if !(result) {
    throw 0
  }
  result := $.lte.Call(2, 1)
  if (result) {
    throw 1
  }
  result := $.lte.Call(1, 1)
  if !(result) {
    throw 2
  }
}
shell_27() {
  result := $.lt.Call(1, 2)
  if !(result) {
    throw 0
  }
  result := $.lt.Call(2, 1)
  if (result) {
    throw 1
  }
  result := $.lt.Call(1, 1)
  if (result) {
    throw 2
  }
}
shell_28() {
  string := "wow"
  n := $.length.Call(string)
  if !(n == 3) {
    throw 3
  }
}
shell_29() {
  map := {a: 1, b: 2, c: 3}
  n := $.length.Call(map)
  if !(n == 3) {
    throw 2
  }
}
shell_30() {
  list := [1, 2, 3]
  n := $.length.Call(list)
  if !(n == 3) {
    throw 1
  }
}
shell_31() {
  list := [1, 2, 3]
  item := $.last.Call(list)
  if !(item == 3) {
    throw 0
  }
}
shell_32() {
  map := {a: 1, b: 2, c: 3}
  result := $.join.Call($.keys.Call(map))
  if !(result == "a,b,c") {
    throw 0
  }
  map := {0: "", 1: "a", 2: "b", 3: "c"}
  result := $.join.Call($.keys.Call(map))
  if !(result == "0,1,2,3") {
    throw result
  }
}
shell_33() {
  list := [1, 2, 3, 4, 5]
  result := $.join.Call(list)
  if !(result == "1,2,3,4,5") {
    throw 1
  }
  result := $.join.Call(list, "")
  if !(result == "12345") {
    throw 2
  }
}
shell_34() {
  string := "aloha"
  result := $.isString.Call(string)
  if !(result) {
    throw 1
  }
}
shell_35() {
  map := {a: 1}
  result := $.isObject.Call(map)
  if !(result) {
    throw 1
  }
}
shell_36() {
  n := 1
  result := $.isNumber.Call(n)
  if !(result) {
    throw 1
  }
}
shell_37() {
  return ""
}
shell_38() {
  fn := Func("shell_37")
  result := $.isFunction.Call(fn)
  if !(result) {
    throw 1
  }
}
shell_39() {
  if !($.isFunction.Call($.isExist)) {
    throw 0
  }
}
shell_40() {
  list := []
  result := $.isArray.Call(list)
  if !(list) {
    throw 1
  }
  list := [1, 2, 3]
  result := $.isArray.Call(list)
  if !(result) {
    throw 2
  }
}
shell_41() {
  if !(($.type.Call($.isActive)) == "function") {
    throw 0
  }
}
shell_42() {
  if !(($.type.Call($.info)) == "function") {
    throw 0
  }
}
shell_43() {
  list := [1, 2, 3]
  result := $.includes.Call(list, 1)
  if !(result) {
    throw 3
  }
  result := $.includes.Call(list, 4)
  if (result) {
    throw 4
  }
}
shell_44() {
  string := "string"
  result := $.includes.Call(string, "s")
  if !(result) {
    throw 1
  }
  result := $.includes.Call(string, "a")
  if (result) {
    throw 2
  }
}
shell_45() {
  if !(($.type.Call($.i)) == "function") {
    throw 0
  }
}
shell_46() {
  result := $.gte.Call(2, 1)
  if !(result) {
    throw 0
  }
  result := $.gte.Call(1, 2)
  if (result) {
    throw 1
  }
  result := $.gte.Call(1, 1)
  if !(result) {
    throw 2
  }
}
shell_47() {
  result := $.gt.Call(2, 1)
  if !(result) {
    throw 0
  }
  result := $.gt.Call(1, 2)
  if (result) {
    throw 1
  }
  result := $.gt.Call(1, 1)
  if (result) {
    throw 2
  }
}
shell_48() {
  if !(($.type.Call($.getState)) == "function") {
    throw 0
  }
}
shell_49() {
  if !(($.type.Call($.getPosition)) == "function") {
    throw 0
  }
  $.move.Call([100, 100])
  __array__ := $.getPosition.Call()
  x := __array__[1]
  y := __array__[2]
  if !(x == 100 && y == 100) {
    throw 0
  }
}
shell_50() {
  if !(($.type.Call($.getColor)) == "function") {
    throw 0
  }
}
shell_51() {
  if !(($.type.Call($.get)) == "function") {
    throw 0
  }
}
shell_52() {
  key := "alt + ctrl + shift + win + esc"
  result := $.formatHotkey.Call(key)
  if !(result == "!^+#esc") {
    throw result
  }
}
shell_53() {
  key := "win + r"
  result := $.formatHotkey.Call(key)
  if !(result == "#r") {
    throw result
  }
}
shell_54() {
  key := "shift + a"
  result := $.formatHotkey.Call(key)
  if !(result == "+a") {
    throw result
  }
}
shell_55() {
  key := "ctrl + f5"
  result := $.formatHotkey.Call(key)
  if !(result == "^f5") {
    throw result
  }
}
shell_56() {
  key := "alt + f4"
  result := $.formatHotkey.Call(key)
  if !(result == "!f4") {
    throw result
  }
}
shell_57(listA, it, i) {
  $.push.Call(listA, it)
  $.push.Call(listA, i)
}
shell_58() {
  list := [1, 2, 3]
  listA := []
  $.forEach.Call(list, Func("shell_57").Bind(listA))
  if !(($.join.Call(listA, "")) == "102132") {
    throw 0
  }
}
shell_59() {
  n := 1.2
  result := $.floor.Call(n)
  if !(result == 1) {
    throw result
  }
  n := -1.2
  result := $.floor.Call(n)
  if !(result == -2) {
    throw result
  }
}
shell_60() {
  list := [1, 2, 3]
  n := $.first.Call(list)
  if !(n == 1) {
    throw n
  }
}
shell_61() {
  if !(($.type.Call($.findImage)) == "function") {
    throw 0
  }
}
shell_62() {
  if !(($.type.Call($.findColor)) == "function") {
    throw 0
  }
}
shell_63(it) {
  return it != 2
}
shell_64() {
  list := [1, 2, 3]
  listA := $.filter.Call(list, Func("shell_63"))
  if !(($.join.Call(listA, "")) == "13") {
    throw 0
  }
}
shell_65() {
  if !(($.type.Call($.exit)) == "function") {
    throw 0
  }
}
shell_66() {
  if !($.isFunction.Call($.exec)) {
    throw 0
  }
}
shell_67() {
  mapA := {a: 1, b: 2}
  mapB := {a: 1, b: 2}
  if !($.eq.Call(mapA, mapB)) {
    throw 0
  }
  mapC := {a: 1, b: 2, c: 3}
  if ($.eq.Call(mapA, mapC)) {
    throw 1
  }
}
shell_68() {
  listA := [1, 2]
  listB := [1, 2]
  if !($.eq.Call(listA, listB)) {
    throw 0
  }
  listC := [1, 2, 3]
  if ($.eq.Call(listA, listC)) {
    throw 1
  }
}
shell_69() {
  stringA := "hello"
  stringB := "hello"
  if !($.eq.Call(stringA, stringB)) {
    throw 0
  }
  stringC := "aloha"
  if ($.eq.Call(stringA, stringC)) {
    throw 1
  }
}
shell_70() {
  a := 1
  b := 1
  if !($.eq.Call(a, b)) {
    throw 0
  }
  c := 2
  if ($.eq.Call(a, c)) {
    throw 1
  }
}
shell_71(listA, length, it, i) {
  listA[__ci_shell__.Call(length - i)] := it
}
shell_72() {
  list := [1, 2, 3, 4]
  listA := []
  length := $.length.Call(list)
  $.each.Call(list, Func("shell_71").Bind(listA, length))
  string := $.join.Call(list)
  if !(string := "4321") {
    throw string
  }
}
shell_73() {
  list := [1, 2, 3, 4, 5]
  listA := $.drop.Call(list)
  result := $.join.Call(listA, "")
  if !(result == "2345") {
    throw result
  }
  listB := $.drop.Call(list, 3)
  result := $.join.Call(listB, "")
  if !(result == "45") {
    throw result
  }
}
shell_74() {
  if !(($.type.Call($.delay)) == "function") {
    throw 0
  }
}
shell_75() {
  if !(($.type.Call($.defer)) == "function") {
    throw 0
  }
}
shell_76() {
  if !(($.type.Call($.debounce)) == "function") {
    throw 0
  }
}
shell_77() {
  if !(($.type.Call($.confirm)) == "function") {
    throw 0
  }
}
shell_78() {
  listA := $.concat.Call([1, 2, 3], 4, 5, [6, 7], 8, [9])
  if !(($.join.Call(listA, "")) == "123456789") {
    throw listA
  }
}
shell_79() {
  list := [0, 1, false, true, "", "x"]
  listA := $.compact.Call(list)
  if !(($.join.Call(listA, "")) == "11x") {
    throw listA
  }
}
shell_80() {
  if !(($.type.Call($.close)) == "function") {
    throw 0
  }
}
shell_81() {
  map := {a: 1, b: 2, c: 3}
  mapA := $.clone.Call(map)
  if !(($.join.Call([mapA.a, mapA.b, mapA.c], "")) == "123") {
    throw mapA
  }
}
shell_82() {
  list := [1, 2, 3]
  listA := $.clone.Call(list)
  if !(($.join.Call(listA, "")) == "123") {
    throw listA
  }
}
shell_83() {
  if !(($.type.Call($.click)) == "function") {
    throw 0
  }
}
shell_84() {
  if !(($.type.Call($.clearTimeout)) == "function") {
    throw 0
  }
}
shell_85() {
  if !(($.type.Call($.clearInterval)) == "function") {
    throw 0
  }
}
shell_86(it) {
  return $.join.Call(it, "")
}
shell_87() {
  list := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  listA := $.chunk.Call(list, 4)
  string := $.join.Call(($.map.Call(listA, Func("shell_86"))), ",")
  if !(string == "1234,5678,910") {
    throw string
  }
}
shell_88() {
  n := 1.2
  result := $.ceil.Call(n)
  if !(result == 2) {
    throw 0
  }
  n := -1.2
  result := $.ceil.Call(n)
  if !(result == -1) {
    throw 1
  }
}
shell_89() {
  if !(($.type.Call($.blockInput)) == "function") {
    throw 0
  }
}
shell_90() {
  if !(($.type.Call($.bind)) == "function") {
    throw 0
  }
}
shell_91() {
  if !(($.type.Call($.beep)) == "function") {
    throw 0
  }
}
shell_92() {
  if !(($.type.Call($.alert)) == "function") {
    throw 0
  }
}
shell_93() {
  a := 1
  b := 2
  c := 3
  d := -4
  result := $.add.Call(a)
  if !(result == 1) {
    throw result
  }
  result := $.add.Call(a, b, c)
  if !(result == 6) {
    throw result
  }
  result := $.add.Call(a, b, c, d)
  if !(result == 2) {
    throw result
  }
}
shell_94(name) {
  $.minimize.Call(name)
  isActive := $.isActive.Call(name)
  if (isActive) {
    throw 1
  }
  $.activate.Call(name)
  isActive := $.isActive.Call(name)
  if !(isActive) {
    throw 2
  }
  $.close.Call(name)
}
shell_95() {
  if !(($.type.Call($.activate)) == "function") {
    throw 0
  }
  name := "notepad.exe"
  $.close.Call(name)
  $.open.Call(name)
  $.wait.Call(name, Func("shell_94").Bind(name))
}
shell_96() {
  n := 42
  result := $.abs.Call(n)
  if !(result == 42) {
    throw result
  }
  n := -42
  result := $.abs.Call(n)
  if !(result == 42) {
    throw result
  }
}
shell_97(target, callback) {
  if !(target) {
    throw Exception("$.wait: target is required")
  }
  if !(callback) {
    throw Exception("$.wait: callback is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinWait, % __target__
  if !(($.type.Call(callback)) == "function") {
    return
  }
  callback.Call()
}
shell_98(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "object") {
    throw Exception("$.values: invalid type '" . (__type__) . "'")
  }
  __listResult__ := []
  for __index_for__, __key__ in $.keys.Call(ipt) {
    __listResult__.Push(ipt[__ci_shell__.Call(__key__)])
  }
  return __listResult__
}
shell_99(list, args*) {
  __type__ := $.type.Call(list)
  if !(__type__ == "array") {
    throw Exception("$.unshift: invalid type '" . (__type__) . "'")
  }
  list.InsertAt(1, args*)
  return list.Length()
}
shell_100(list) {
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (($.type.Call(__item__)) == "string") {
      __hasString__ := true
      break
    }
  }
  __string__ := $.join.Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C U D,
  } else {
    Sort, __string__, N U D,
  }
  return $.split.Call(__string__, ",")
}
shell_101(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
shell_102(ipt, omitting := " `t") {
  return LTrim(ipt, omitting)
}
shell_103(ipt, omitting := " `t") {
  return RTrim(ipt, omitting)
}
shell_104(ipt, omitting := " `t") {
  return Trim(ipt, omitting)
}
shell_105(ipt) {
  StringUpper, __result__, ipt
  return __result__
}
shell_106(ipt) {
  __type__ := $.type.Call(ipt)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in ipt {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in ipt {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return ipt
}
shell_107(ipt) {
  StringLower, __result__, ipt
  return __result__
}
shell_108(callback, index) {
  callback.Call()
  __tsThrottle__[__ci_shell__.Call(index)] := $.now.Call()
}
shell_109(callback, time, index) {
  $.clearTimeout.Call(__tThrottle__[__ci_shell__.Call(index)])
  __tThrottle__[__ci_shell__.Call(index)] := $.setTimeout.Call(Func("shell_108").Bind(callback, index), __tsThrottle__[__ci_shell__.Call(index)] - $.now.Call() + time)
}
shell_110(time, callback) {
  __iThrottle__++
  __tsThrottle__[__ci_shell__.Call(__iThrottle__)] := 0
  return Func("shell_109").Bind(callback, time, __iThrottle__)
}
shell_111(list, count := 1) {
  __len__ := $.length.Call(list)
  if !(__len__) {
    return []
  }
  if !(count >= 0) {
    return []
  }
  if (count >= __len__) {
    count := __len__
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if (__i__ >= count) {
      break
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_112(list) {
  return $.drop.Call(list, 1)
}
shell_113(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
shell_114(list) {
  __result__ := 0
  for __index_for__, __n__ in list {
    __result__ := __result__ + __n__
  }
  return __result__
}
shell_115(text, iStart, iEnd := 0) {
  __type__ := $.type.Call(text)
  if !(__type__ == "string") {
    throw Exception("$.subString: invalid type '" . (__type__) . "'")
  }
  if (iEnd) {
    __len__ := iEnd - iStart
  } else {
    __len__ := 0
  }
  if !(__len__) {
    return SubStr(text, iStart + 1)
  } else {
    return SubStr(text, iStart + 1, __len__)
  }
}
shell_116(text, string) {
  return (InStr(text, string)) == 1
}
shell_117(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
shell_118(list) {
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (($.type.Call(__item__)) == "string") {
      __hasString__ := true
      break
    }
  }
  __string__ := $.join.Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C D,
  } else {
    Sort, __string__, N D,
  }
  return $.split.Call(__string__, ",")
}
shell_119(args) {
  switch $.length.Call(args) {
    case 1: {
      __array__ := [args[1], 0, $.length.Call(args[1])]
      __list__ := __array__[1]
      __start__ := __array__[2]
      __end__ := __array__[3]
    }
    case 2: {
      __array__ := [args[1], args[2], $.length.Call(args[1])]
      __list__ := __array__[1]
      __start__ := __array__[2]
      __end__ := __array__[3]
    }
    case 3: {
      __array__ := args
      __list__ := __array__[1]
      __start__ := __array__[2]
      __end__ := __array__[3]
    }
  }
  return [__list__, __start__, __end__]
}
shell_120(args*) {
  __array__ := __pickArgumentSlice__.Call(args)
  __list__ := __array__[1]
  __start__ := __array__[2]
  __end__ := __array__[3]
  __type__ := $.type.Call(__list__)
  if !(__type__ == "array") {
    throw Exception("$.slice: invalid type '" . (__type__) . "'")
  }
  __len__ := __list__.Length()
  if (__start__ > __len__) {
    __start__ := __len__
  }
  if (__start__ < 0) {
    __start__ := __len__ + __start__
  }
  if (__end__ > __len__) {
    __end__ := __len__
  }
  if (__end__ < 0) {
    __end__ := __len__ + __end__
  }
  __isReverse__ := false
  if (__start__ > __end__) {
    __isReverse__ := true
    __array__ := [__end__, __start__]
    __start__ := __array__[1]
    __end__ := __array__[2]
  }
  __listNew__ := []
  __n__ := 0
  __max__ := __end__ - __start__
  while (__n__ < __max__) {
    $.push.Call(__listNew__, __list__[__ci_shell__.Call(__start__ + __n__)])
    __n__++
  }
  if (__isReverse__) {
    return $.reverse.Call(__listNew__)
  }
  return __listNew__
}
shell_121(time) {
  if !(time > 0) {
    throw Exception("$.sleep: time is required")
  }
  Sleep, % time
}
shell_122(__split__, list) {
  __string__ := $.join.Call(list, ",")
  Sort, __string__, Random D,
  return __split__.Call(__string__, ",")
}
shell_123(list) {
  __type__ := $.type.Call(list)
  if !(__type__ == "array") {
    throw Exception("$.shift: invalid type '" . (__type__) . "'")
  }
  __first__ := list[1]
  list.RemoveAt(1)
  return __first__
}
shell_124(callback, time) {
  callback := $.bind.Call(callback)
  if !($.isNumber.Call(time)) {
    throw Exception("$.setTimeout: invalid type")
  }
  if (time < 1) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
shell_125(target, style) {
  if !(target) {
    throw Exception("$.setStyle: target is required")
  }
  if !(style) {
    throw Exception("$.setStyle: style is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinSet, Style, % style, % __target__
}
shell_126(callback, time) {
  callback := $.bind.Call(callback)
  if !(time > 0) {
    throw Exception("$.setInterval: invalid value")
  }
  SetTimer, % callback, % time
  return callback
}
shell_127(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
shell_128(n) {
  return Round(n)
}
shell_129(list) {
  __len__ := $.length.Call(list)
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    __listNew__[__ci_shell__.Call(__len__ - 1 - __i__)] := __item__
  }
  for __i__, __item__ in __listNew__ {
    __i__ := __i__ - 1
    list[__ci_shell__.Call(__i__)] := __item__
  }
  return list
}
shell_130(ipt, searchment, replacement, limit := -1) {
  return StrReplace(ipt, searchment, replacement, limit)
}
shell_131() {
  Reload
}
shell_132(args*) {
  switch $.length.Call(args) {
    case 1: {
      __array__ := [0, args[1], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 2: {
      __array__ := [args[1], args[2], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 3: {
      __array__ := args
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    default: {
      throw Exception("$.range: invalid arguments")
    }
  }
  if (__start__ == __end__) {
    return [__start__]
  }
  if (__start__ > __end__) {
    return []
  }
  __listResult__ := []
  __n__ := 0
  __max__ := __end__ - __start__
  while (__n__ < __max__) {
    $.push.Call(__listResult__, __start__ + __step__ * __n__)
    __n__++
  }
  return __listResult__
}
shell_133(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
shell_134(list, args*) {
  __type__ := $.type.Call(list)
  if !(__type__ == "array") {
    throw Exception("$.push: invalid type '" . (__type__) . "'")
  }
  for __index_for__, __arg__ in args {
    list.Push(__arg__)
  }
  return list.Length()
}
shell_135(listInput) {
  if !($.length.Call(listInput)) {
    return false
  }
  __key__ := listInput[1]
  if ($.includes.Call(__key__, "-button")) {
    __key__ := $.replace.Call(__key__, "l-button", "left")
    __key__ := $.replace.Call(__key__, "m-button", "middle")
    __key__ := $.replace.Call(__key__, "r-button", "right")
    $.click.Call(__key__)
    return false
  }
  return true
}
shell_136(listInput) {
  __listKey__ := []
  for __index_for__, __input__ in listInput {
    __ipt__ := $.toLowerCase.Call(__input__)
    __ipt__ := $.replace.Call(__ipt__, " ", "")
    __ipt__ := $.replace.Call(__ipt__, "-", "")
    $.push.Call(__listKey__, ($.split.Call(__ipt__, "+"))*)
  }
  return __listKey__
}
shell_137(listInput*) {
  if !(__validateInputPress__.Call(listInput)) {
    return
  }
  __listKey__ := __formatInputPress__.Call(listInput)
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for __i__, __key__ in __listKey__ {
    __i__ := __i__ - 1
    if (__i__ == __len__ - 1) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      continue
    }
    if ($.includes.Call(__key__, ":")) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := $.split.Call(__key__, ":")
    } else {
      __listResult__[__ci_shell__.Call(__i__)] := [__key__, "down"]
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := [__key__, "up"]
    }
  }
  for __i__, __it__ in __listResult__ {
    __i__ := __i__ - 1
    if (__it__[1] == "win") {
      __it__[1] := "lwin"
    }
    __listResult__[__ci_shell__.Call(__i__)] := $.trim.Call("" . (__it__[1]) . " " . (__it__[2]) . "")
  }
  __result__ := ""
  for __index_for__, __it__ in __listResult__ {
    __result__ := "" . (__result__) . "{" . (__it__) . "}"
  }
  Send, % __result__
}
shell_138(list) {
  __type__ := $.type.Call(list)
  if !(__type__ == "array") {
    throw Exception("$.pop: invalid type '" . (__type__) . "'")
  }
  return list.Pop()
}
shell_139(filename) {
  SoundPlay, % filename
}
shell_140(source) {
  Run, % source
}
shell_141(__i__, callback, args*) {
  if (__cacheOnce__[__ci_shell__.Call(__i__)][1]) {
    return __cacheOnce__[__ci_shell__.Call(__i__)][2]
  }
  __result__ := callback.Call(args*)
  __cacheOnce__[__ci_shell__.Call(__i__)] := [true, __result__]
  return __result__
}
shell_142(callback) {
  __i__ := __indexOnce__
  __indexOnce__++
  __cacheOnce__[__ci_shell__.Call(__i__)] := [false, ""]
  return Func("shell_141").Bind(__i__, callback)
}
shell_143(list, n := 0) {
  if (n >= 0) {
    return list[__ci_shell__.Call(n)]
  } else {
    return list[__ci_shell__.Call(($.length.Call(list)) + n)]
  }
}
shell_144() {
  return A_TickCount
}
shell_145() {
  return
}
shell_146(point := "", speed := 0) {
  MouseMove, point[1], point[2], speed
}
shell_147(dividend, divisor) {
  return Mod(dividend, divisor)
}
shell_148(args*) {
  if !($.length.Call(args)) {
    throw Exception("$.mixin: invalid arguments")
  }
  __result__ := args[1]
  for __index_for__, __item__ in $.tail.Call(args) {
    for __key__, __value__ in __item__ {
      __result__[__ci_shell__.Call(__key__)] := __value__
    }
  }
  return __result__
}
shell_149(target := "") {
  if !(target) {
    throw Exception("$.minimize: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinMinimize, % __target__
}
shell_150(target) {
  if !(target) {
    throw Exception("$.maximize: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinMaximize, % __target__
}
shell_151(list, callback) {
  __listResult__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    $.push.Call(__listResult__, callback.Call(__item__, __i__))
  }
  return __listResult__
}
shell_152(value, other) {
  return value <= other
}
shell_153(value, other) {
  return value < other
}
shell_154(ipt) {
  __type__ := $.type.Call(ipt)
  switch __type__ {
    case "array": {
      return ipt.Length()
    }
    case "object": {
      return ipt.Count()
    }
    case "string": {
      return StrLen(ipt)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
shell_155(list) {
  return list[__ci_shell__.Call(($.length.Call(list)) - 1)]
}
shell_156(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "object") {
    throw Exception("$.keys: invalid type '" . (__type__) . "'")
  }
  __listResult__ := []
  for __key__, __value__ in ipt {
    __listResult__.Push(__key__)
  }
  return $.sort.Call(__listResult__)
}
shell_157(__name__, __item__) {
  return __item__[1] != __name__
}
shell_158(this, key) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return
  }
  __listNew__ := $.filter.Call(this.mapCallback[__ci_shell__.Call(key)], Func("shell_157").Bind(__name__))
  if !($.length.Call(__listNew__)) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return
  }
  this.mapCallback[__ci_shell__.Call(key)] := __listNew__
}
shell_159(this, key, callback) {
  key := $.formatHotkey.Call($.replace.Call(key, ":down", ""))
  Hotkey, % key, % callback, On
}
shell_160(this, key, callback) {
  key := $.formatHotkey.Call($.replace.Call(key, ":down", ""))
  Hotkey, % key, % callback, Off
}
shell_161(key, this) {
  this.fire.Call(key)
}
shell_162(this, key) {
  if (this.mapCallback[__ci_shell__.Call(key)]) {
    return
  }
  this.mapCallback[__ci_shell__.Call(key)] := []
  __fn__ := Func("shell_161").Bind(key, this)
  this.mapBound[__ci_shell__.Call(key)] := __fn__
  this.on.Call(key, __fn__)
}
shell_163(it) {
  it[2].Call()
}
shell_164(__name__, it) {
  return it[1] == __name__
}
shell_165(this, key) {
  __array__ := $.split.Call(($.replace.Call(key, ":down", "")), ".")
  key := __array__[1]
  __name__ := __array__[2]
  __list__ := this.mapCallback[__ci_shell__.Call(key)]
  if (__name__) {
    __list__ := $.filter.Call(__list__, Func("shell_164").Bind(__name__))
  }
  $.forEach.Call(__list__, Func("shell_163"))
}
shell_166(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  this.init.Call(key)
  $.push.Call(this.mapCallback[__ci_shell__.Call(key)], [__name__, callback])
}
shell_167(list, seperator := ",") {
  __result__ := ""
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__) {
      __result__ := __item__
      continue
    }
    __result__ := "" . (__result__) . "" . (seperator) . "" . (__item__) . ""
  }
  return __result__
}
shell_168(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "string") {
    return false
  }
  return true
}
shell_169(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "object") {
    return false
  }
  return true
}
shell_170(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "number") {
    return false
  }
  return true
}
shell_171(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "function") {
    return false
  }
  return true
}
shell_172(target) {
  return WinExist("ahk_exe " . (target) . "")
}
shell_173(ipt) {
  __type__ := $.type.Call(ipt)
  if !(__type__ == "array") {
    return false
  }
  return true
}
shell_174(target) {
  return WinActive("ahk_exe " . (target) . "")
}
shell_175(message, p := "") {
  if !(message) {
    return message
  }
  if !(p) {
    p := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % p[1], % p[2]
  return message
}
shell_176(ipt, needle) {
  __type__ := $.type.Call(ipt)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(ipt, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, __it__ in ipt {
      if (__it__ == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
shell_177(message) {
  $.info.Call("[" . ($.now.Call()) . "] " . ($.toString.Call(message)) . "", [0, 0])
  return message
}
shell_178(value, other) {
  return value >= other
}
shell_179(value, other) {
  return value > other
}
shell_180(key) {
  key := $.formatHotkey.Call(key)
  return GetKeyState(key, "P")
}
shell_181() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
shell_182(p := "") {
  if !(p) {
    p := $.getPosition.Call()
  }
  PixelGetColor, __result__, % p[1], % p[2], RGB
  return __result__
}
shell_183(url, callback) {
  try {
    whr := ComObjCreate("WinHttp.WinHttpRequest.5.1")
    whr.Open("GET", url, true)
    whr.Send()
    whr.WaitForResponse()
    callback.Call(whr.ResponseText)
  } catch {
    callback.Call("")
  }
}
shell_184(listKey) {
  if (($.length.Call(listKey)) == 1) {
    return ["", listKey]
  }
  __prefix__ := ""
  __listNew__ := []
  for __index_for__, __key__ in listKey {
    if (__key__ == "alt") {
      __prefix__ := "" . (__prefix__) . "!"
      continue
    }
    if (__key__ == "ctrl") {
      __prefix__ := "" . (__prefix__) . "^"
      continue
    }
    if (__key__ == "shift") {
      __prefix__ := "" . (__prefix__) . "+"
      continue
    }
    if (__key__ == "win") {
      __prefix__ := "" . (__prefix__) . "#"
      continue
    }
    $.push.Call(__listNew__, __key__)
  }
  return [__prefix__, __listNew__]
}
shell_185(key) {
  __listKey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  $.push.Call(__listKey__, ($.split.Call(__key__, "+"))*)
  return __listKey__
}
shell_186(key) {
  __listKey__ := __formatKeyFormatHotkey__.Call(key)
  __array__ := __pickPrefixFormatHotkey__.Call(__listKey__)
  __prefix__ := __array__[1]
  __listKey__ := __array__[2]
  __result__ := ""
  for __index_for__, __it__ in __listKey__ {
    __result__ := "" . (__result__) . " & " . (__it__) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
shell_187(list, callback) {
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    callback.Call(__item__, __i__)
  }
}
shell_188(n) {
  return Floor(n)
}
shell_189(list) {
  return list[1]
}
shell_190(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
shell_191(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
shell_192(list, callback) {
  __listResult__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(callback.Call(__item__, __i__)) {
      continue
    }
    $.push.Call(__listResult__, __item__)
  }
  return __listResult__
}
shell_193(name) {
  return new FileShellX(name)
}
shell_194(this, content) {
  this.delete.Call()
  return this.append.Call(content)
}
shell_195(this) {
  if !(this.exist.Call()) {
    return ""
  }
  FileRead, __result__, % this.name
  return $.replace.Call(__result__, "`r", "")
}
shell_196(this) {
  if !(this.exist.Call()) {
    return this
  }
  FileDelete, % this.name
  return this
}
shell_197(this) {
  if !(FileExist(this.name)) {
    return false
  }
  return true
}
shell_198(this, content) {
  FileAppend, % content, % this.name, UTF-8
  return content
}
shell_199() {
  ExitApp
}
shell_200(__input__, __callback__) {
  if ($.isString.Call(__input__)) {
    __input__ := [__input__]
  }
  __input__ := $.join.Call(__input__, " && ")
  RunWait, %comSpec% /c %__input__%,, Hide UseErrorLevel
  if ($.isFunction.Call(__callback__)) {
    __callback__.Call(ErrorLevel)
  }
}
shell_201(value, other) {
  __typeA__ := $.type.Call(value)
  __typeB__ := $.type.Call(other)
  if !(__typeA__ == __typeB__) {
    return false
  }
  if ($.includes.Call(["function", "number", "string"], __typeA__)) {
    return value == other
  }
  __lengthA__ := $.length.Call(value)
  __lengthB__ := $.length.Call(other)
  if !(__lengthA__ == __lengthB__) {
    return false
  }
  if (__typeA__ == "array") {
    for __i__, __it__ in value {
      __i__ := __i__ - 1
      if !(__eq__.Call(__it__, other[__ci_shell__.Call(__i__)])) {
        return false
      }
    }
    return true
  }
  for __k__, __v__ in value {
    if !(__eq__.Call(__v__, other[__ci_shell__.Call(__k__)])) {
      return false
    }
  }
  return true
}
shell_202() {
  return new EmitterShell
}
shell_203(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  $.push.Call(this.bus, [__type__, __name__, callback, 1])
}
shell_204(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  $.push.Call(this.bus, [__type__, __name__, callback, 0])
}
shell_205(__type__, __it__) {
  return __it__[1] != __type__
}
shell_206(__type__, __name__, __it__) {
  return !(__it__[1] == __type__ && __it__[2] == __name__)
}
shell_207(this, key) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    this.bus := []
    return
  }
  if (__name__) {
    this.bus := $.filter.Call(this.bus, Func("shell_206").Bind(__type__, __name__))
  } else {
    this.bus := $.filter.Call(this.bus, Func("shell_205").Bind(__type__))
  }
}
shell_208(__it__) {
  return __it__[4] != 2
}
shell_209(args, __it__) {
  __it__[3].Call(args*)
  if (__it__[4] == 1) {
    __it__[4] := 2
  }
}
shell_210(__type__, __it__) {
  return __it__[1] == __type__
}
shell_211(__type__, __name__, __it__) {
  return __it__[1] == __type__ && __it__[2] == __name__
}
shell_212(__filter__, this, key, args*) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    return
  }
  if (__name__) {
    __list__ := $.filter.Call(this.bus, Func("shell_211").Bind(__type__, __name__))
  } else {
    __list__ := $.filter.Call(this.bus, Func("shell_210").Bind(__type__))
  }
  $.forEach.Call(__list__, Func("shell_209").Bind(args))
  this.bus := __filter__.Call(this.bus, Func("shell_208"))
}
shell_213(list, callback) {
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    callback.Call(__item__, __i__)
  }
}
shell_214(n, _it, i) {
  return i >= n
}
shell_215(list, n := 1) {
  return $.filter.Call(list, Func("shell_214").Bind(n))
}
shell_216(callback, args) {
  callback.Call(args*)
}
shell_217(callback, time, args*) {
  __timer__ := $.setTimeout.Call(Func("shell_216").Bind(callback, args), time)
  return __timer__
}
shell_218(callback, args) {
  callback.Call(args*)
}
shell_219(callback, args*) {
  return $.delay.Call(Func("shell_218").Bind(callback, args), 1)
}
shell_220(callback, time, index) {
  $.clearTimeout.Call(__tDebounce__[__ci_shell__.Call(index)])
  __tDebounce__[__ci_shell__.Call(index)] := $.setTimeout.Call(callback, time)
}
shell_221(time, callback) {
  __iDebounce__++
  return Func("shell_220").Bind(callback, time, __iDebounce__)
}
shell_222(text, callback) {
  
  MsgBox, 0x4,, % text`
  IfMsgBox Yes
    callback.Call(true)
  else
    callback.Call(false)
  
}
shell_223(list, args*) {
  __listNew__ := $.clone.Call(list)
  for __index_for__, __arg__ in args {
    __type__ := $.type.Call(__arg__)
    if (__type__ == "array") {
      for __index_for__, __item__ in __arg__ {
        $.push.Call(__listNew__, __item__)
      }
    } else {
      $.push.Call(__listNew__, __arg__)
    }
  }
  return __listNew__
}
shell_224(it) {
  return it
}
shell_225(list) {
  return $.filter.Call(list, Func("shell_224"))
}
shell_226(target) {
  if !(target) {
    throw Exception("$.close: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinClose, % __target__
}
shell_227(ipt) {
  __type__ := $.type.Call(ipt)
  if (__type__ == "array") {
    return $.slice.Call(ipt)
  }
  if (__type__ == "object") {
    __mapNew__ := {}
    for __key__, __value__ in ipt {
      __mapNew__[__ci_shell__.Call(__key__)] := __value__
    }
    return __mapNew__
  }
  throw Exception("$.clone: invalid type '" . (__type__) . "'")
}
shell_228(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
shell_229(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_230(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_231(list, n := 1) {
  __listNew__ := []
  __length__ := $.length.Call(list)
  __i__ := 0
  while (__i__ < __length__ / n) {
    __listTemp__ := []
    __j__ := 0
    while (__j__ < n) {
      __index__ := __i__ * n + __j__
      if !(__index__ < __length__) {
        break
      }
      $.push.Call(__listTemp__, list[__ci_shell__.Call(__index__)])
      __j__++
    }
    $.push.Call(__listNew__, __listTemp__)
    __i__++
  }
  return __listNew__
}
shell_232(n) {
  return Ceil(n)
}
shell_233(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
shell_234(callback, args*) {
  if !(callback.Name) {
    if !($.length.Call(args)) {
      return callback
    }
    throw Exception("$.bind: cannot bind a bound function")
  }
  return callback.Bind(args*)
}
shell_235() {
  SoundBeep
}
shell_236(msg) {
  return $.toString.Call(msg)
}
shell_237(message*) {
  __msg__ := $.join.Call(($.map.Call(message, Func("shell_236"))), ", ")
  MsgBox, % __msg__
}
shell_238(args*) {
  __result__ := 0
  for __index_for__, __arg__ in args {
    __result__ := __result__ + __arg__
  }
  return __result__
}
shell_239(target) {
  if !(target) {
    throw Exception("$.activate: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinActivate, % __target__
}
shell_240(n) {
  return Abs(n)
}
shell_241(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}
