; Generated by Coffee-AHK/0.0.41
global __ci_shell__ := Func("shell_216")
global $ := {}
$.abs := Func("shell_215")
$.activate := Func("shell_214")
$.add := Func("shell_213")
$.alert := Func("shell_212")
$.beep := Func("shell_210")
$.bind := Func("shell_209")
$.blockInput := Func("shell_208")
$.ceil := Func("shell_207")
$.chunk := Func("shell_206")
$.clearInterval := Func("shell_205")
$.clearTimeout := Func("shell_204")
$.click := Func("shell_203")
$.clone := Func("shell_202")
$.close := Func("shell_201")
$.compact := Func("shell_200")
$.concat := Func("shell_198")
$.confirm := Func("shell_197")
global __iDebounce__ := 0
global __tDebounce__ := {}
$.debounce := Func("shell_196")
$.defer := Func("shell_194")
$.delay := Func("shell_192")
$.drop := Func("shell_190")
$.each := Func("shell_188")
class EmitterShellX {
  bus := []
  emit := Func("shell_187").Bind(this)
  off := Func("shell_186").Bind(this)
  on := Func("shell_185").Bind(this)
}
$.emitter := Func("shell_184")
global __eq__ := Func("shell_183")
$.eq := __eq__
$.exit := Func("shell_182")
class FileShellX {
  name := ""
  __New(name) {
    this.name := name
  }
  append := Func("shell_181").Bind(this)
  exist := Func("shell_180").Bind(this)
  delete := Func("shell_179").Bind(this)
  load := Func("shell_178").Bind(this)
  save := Func("shell_177").Bind(this)
}
$.file := Func("shell_176")
$.filter := Func("shell_175")
$.findColor := Func("shell_174")
$.findImage := Func("shell_173")
$.first := Func("shell_172")
$.head := $.first
$.floor := Func("shell_171")
$.formatHotkey := Func("shell_170")
global __formatKeyFormatHotkey__ := Func("shell_169")
global __pickPrefixFormatHotkey__ := Func("shell_168")
$.get := Func("shell_167")
$.getColor := Func("shell_166")
$.getPosition := Func("shell_165")
$.getState := Func("shell_164")
$.gt := Func("shell_163")
$.gte := Func("shell_162")
$.i := Func("shell_161")
$.includes := Func("shell_160")
$.info := Func("shell_159")
$.isActive := Func("shell_158")
$.isArray := Func("shell_157")
$.isExisted := Func("shell_156")
$.isFunction := Func("shell_155")
$.isNumber := Func("shell_154")
$.isObject := Func("shell_153")
$.isString := Func("shell_152")
$.join := Func("shell_151")
class KeyBindingShellX {
  mapBound := {}
  mapCallback := {}
  add := Func("shell_150").Bind(this)
  fire := Func("shell_149").Bind(this)
  init := Func("shell_148").Bind(this)
  off := Func("shell_146").Bind(this)
  on := Func("shell_145").Bind(this)
  remove := Func("shell_144").Bind(this)
}
global keyBindingShell := new KeyBindingShellX()
$.off := keyBindingShell.remove
$.on := keyBindingShell.add
$.trigger := keyBindingShell.fire
$.keys := Func("shell_142")
$.last := Func("shell_141")
$.length := Func("shell_140")
$.lt := Func("shell_139")
$.lte := Func("shell_138")
$.map := Func("shell_137")
$.maximize := Func("shell_136")
$.minimize := Func("shell_135")
$.mixin := Func("shell_134")
$.mod := Func("shell_133")
$.move := Func("shell_132")
$.noop := Func("shell_131")
$.now := Func("shell_130")
$.nth := Func("shell_129")
global __cacheOnce__ := {}
global __indexOnce__ := 0
$.once := Func("shell_128")
$.open := Func("shell_126")
$.play := Func("shell_125")
$.press := Func("shell_124")
global __formatInputPress__ := Func("shell_123")
global __validateInputPress__ := Func("shell_122")
$.push := Func("shell_121")
$.random := Func("shell_120")
$.range := Func("shell_119")
$.reload := Func("shell_118")
$.replace := Func("shell_117")
$.reverse := Func("shell_116")
$.round := Func("shell_115")
$.setFixed := Func("shell_114")
$.setInterval := Func("shell_113")
$.setStyle := Func("shell_112")
$.setTimeout := Func("shell_111")
$.shuffle := Func("shell_110").Bind(__split__)
$.sleep := Func("shell_109")
$.slice := Func("shell_108")
global __pickArgumentSlice__ := Func("shell_107")
$.sort := Func("shell_106")
$.split := Func("shell_105")
$.sum := Func("shell_104")
$.suspend := Func("shell_103")
$.tail := Func("shell_102")
$.take := Func("shell_101")
global __iThrottle__ := 0
global __tThrottle__ := {}
global __tsThrottle__ := {}
$.throttle := Func("shell_100")
$.toLowerCase := Func("shell_97")
$.toLower := $.toLowerCase
$.toString := Func("shell_96")
$.toUpperCase := Func("shell_95")
$.toUpper := $.toUpperCase
$.trim := Func("shell_94")
$.trimEnd := Func("shell_93")
$.trimStart := Func("shell_92")
$.type := Func("shell_91")
$.uniq := Func("shell_90")
$.values := Func("shell_89")
$.VERSION := "0.0.15"
$.wait := Func("shell_88")
(Func("shell_87")).Call()
(Func("shell_86")).Call()
(Func("shell_84")).Call()
(Func("shell_83")).Call()
(Func("shell_82")).Call()
(Func("shell_81")).Call()
(Func("shell_80")).Call()
(Func("shell_79")).Call()
(Func("shell_78")).Call()
(Func("shell_76")).Call()
(Func("shell_75")).Call()
(Func("shell_74")).Call()
(Func("shell_73")).Call()
(Func("shell_72")).Call()
(Func("shell_71")).Call()
(Func("shell_70")).Call()
(Func("shell_69")).Call()
(Func("shell_68")).Call()
(Func("shell_67")).Call()
(Func("shell_66")).Call()
(Func("shell_65")).Call()
(Func("shell_64")).Call()
(Func("shell_63")).Call()
(Func("shell_61")).Call()
(Func("shell_60")).Call()
(Func("shell_59")).Call()
(Func("shell_58")).Call()
(Func("shell_57")).Call()
(Func("shell_56")).Call()
(Func("shell_54")).Call()
(Func("shell_53")).Call()
(Func("shell_52")).Call()
(Func("shell_51")).Call()
(Func("shell_50")).Call()
(Func("shell_49")).Call()
(Func("shell_48")).Call()
(Func("shell_47")).Call()
(Func("shell_46")).Call()
(Func("shell_45")).Call()
(Func("shell_44")).Call()
(Func("shell_43")).Call()
(Func("shell_42")).Call()
(Func("shell_41")).Call()
(Func("shell_40")).Call()
(Func("shell_39")).Call()
(Func("shell_38")).Call()
(Func("shell_37")).Call()
(Func("shell_36")).Call()
(Func("shell_35")).Call()
(Func("shell_34")).Call()
(Func("shell_33")).Call()
(Func("shell_32")).Call()
(Func("shell_30")).Call()
(Func("shell_29")).Call()
(Func("shell_28")).Call()
(Func("shell_27")).Call()
(Func("shell_26")).Call()
(Func("shell_25")).Call()
(Func("shell_24")).Call()
(Func("shell_23")).Call()
(Func("shell_22")).Call()
(Func("shell_21")).Call()
(Func("shell_20")).Call()
(Func("shell_19")).Call()
(Func("shell_17")).Call()
(Func("shell_16")).Call()
(Func("shell_14")).Call()
(Func("shell_13")).Call()
(Func("shell_12")).Call()
(Func("shell_11")).Call()
(Func("shell_10")).Call()
(Func("shell_9")).Call()
(Func("shell_8")).Call()
(Func("shell_6")).Call()
(Func("shell_5")).Call()
(Func("shell_4")).Call()
(Func("shell_3")).Call()
(Func("shell_2")).Call()
(Func("shell_1")).Call()
shell_1() {
  if !(($.type.Call($.wait)) == "function") {
    throw 0
  }
}
shell_2() {
  if !(($.type.Call($.setStyle)) == "function") {
    throw 0
  }
}
shell_3() {
  list := [0]
  $.push.Call(list, 1)
  if !(list[2] == 1) {
    throw 0
  }
  $.push.Call(list, 2, 3, 4)
  if !(list[3] == 2) {
    throw 1
  }
  if !(list[5] == 4) {
    throw 4
  }
}
shell_4() {
  if !(($.type.Call($.press)) == "function") {
    throw 0
  }
}
shell_5() {
  if !(($.type.Call($.play)) == "function") {
    throw 0
  }
}
shell_6() {
  if !(($.type.Call($.open)) == "function") {
    throw 0
  }
}
shell_7(map) {
  map.n += 1
}
shell_8() {
  map := {n: 0}
  add := $.once.Call(Func("shell_7").Bind(map))
  add.Call()
  if !(map.n == 1) {
    throw 0
  }
  add.Call()
  if !(map.n == 1) {
    throw 1
  }
}
shell_9() {
  list := [0, 1, 2, 3]
  n := $.nth.Call(list, 0)
  if !(n == 0) {
    throw n
  }
  n := $.nth.Call(list, 1)
  if !(n == 1) {
    throw n
  }
  n := $.nth.Call(list, -1)
  if !(n == 3) {
    throw n
  }
}
shell_10() {
  now := $.now.Call()
  if !(($.type.Call(now)) == "number") {
    throw 0
  }
}
shell_11() {
  if !(($.type.Call($.noop)) == "function") {
    throw 0
  }
}
shell_12() {
  $.move.Call([100, 100])
  __array__ := $.getPosition.Call()
  x := __array__[1]
  y := __array__[2]
  if !(x == 100 && y == 100) {
    throw 0
  }
}
shell_13() {
  n := $.mod.Call(5, 2)
  if !(n == 1) {
    throw n
  }
  n := $.mod.Call(7, 5)
  if !(n == 2) {
    throw n
  }
}
shell_14() {
  mapA := {a: 1}
  mapB := {b: 2}
  mapC := {c: 3}
  $.mixin.Call(mapA, mapB, mapC)
  result := $.join.Call($.keys.Call(mapA))
  if !(result == "a,b,c") {
    throw 1
  }
  result := $.join.Call($.values.Call(mapA))
  if !(result == "1,2,3") {
    throw 2
  }
}
shell_15(name) {
  isActive := $.isActive.Call(name)
  if !(isActive) {
    throw 1
  }
  $.minimize.Call(name)
  isActive := $.isActive.Call(name)
  if (isActive) {
    throw 2
  }
  $.close.Call(name)
}
shell_16() {
  if !(($.type.Call($.minimize)) == "function") {
    throw 0
  }
  name := "notepad.exe"
  $.close.Call(name)
  $.open.Call(name)
  $.wait.Call(name, Func("shell_15").Bind(name))
}
shell_17() {
  if !(($.type.Call($.maximize)) == "function") {
    throw 0
  }
}
shell_18(n) {
  return n + 1
}
shell_19() {
  list := [1, 2, 3]
  result := $.join.Call($.map.Call(list, Func("shell_18")))
  if !(result == "2,3,4") {
    throw 0
  }
}
shell_20() {
  result := $.lte.Call(1, 2)
  if !(result) {
    throw 0
  }
  result := $.lte.Call(2, 1)
  if (result) {
    throw 1
  }
  result := $.lte.Call(1, 1)
  if !(result) {
    throw 2
  }
}
shell_21() {
  result := $.lt.Call(1, 2)
  if !(result) {
    throw 0
  }
  result := $.lt.Call(2, 1)
  if (result) {
    throw 1
  }
  result := $.lt.Call(1, 1)
  if (result) {
    throw 2
  }
}
shell_22() {
  string := "wow"
  n := $.length.Call(string)
  if !(n == 3) {
    throw 3
  }
}
shell_23() {
  map := {a: 1, b: 2, c: 3}
  n := $.length.Call(map)
  if !(n == 3) {
    throw 2
  }
}
shell_24() {
  list := [1, 2, 3]
  n := $.length.Call(list)
  if !(n == 3) {
    throw 1
  }
}
shell_25() {
  list := [1, 2, 3]
  item := $.last.Call(list)
  if !(item == 3) {
    throw 0
  }
}
shell_26() {
  map := {a: 1, b: 2, c: 3}
  result := $.join.Call($.keys.Call(map))
  if !(result := "a,b,c") {
    throw 0
  }
}
shell_27() {
  list := [1, 2, 3, 4, 5]
  result := $.join.Call(list)
  if !(result == "1,2,3,4,5") {
    throw 1
  }
  result := $.join.Call(list, "")
  if !(result == "12345") {
    throw 2
  }
}
shell_28() {
  string := "aloha"
  result := $.isString.Call(string)
  if !(result) {
    throw 1
  }
}
shell_29() {
  map := {a: 1}
  result := $.isObject.Call(map)
  if !(result) {
    throw 1
  }
}
shell_30() {
  n := 1
  result := $.isNumber.Call(n)
  if !(result) {
    throw 1
  }
}
shell_31() {
  return ""
}
shell_32() {
  fn := Func("shell_31")
  result := $.isFunction.Call(fn)
  if !(result) {
    throw 1
  }
}
shell_33() {
  if !(($.type.Call($.isExisted)) == "function") {
    throw 0
  }
}
shell_34() {
  list := []
  result := $.isArray.Call(list)
  if !(list) {
    throw 1
  }
  list := [1, 2, 3]
  result := $.isArray.Call(list)
  if !(result) {
    throw 2
  }
}
shell_35() {
  if !(($.type.Call($.isActive)) == "function") {
    throw 0
  }
}
shell_36() {
  if !(($.type.Call($.info)) == "function") {
    throw 0
  }
}
shell_37() {
  list := [1, 2, 3]
  result := $.includes.Call(list, 1)
  if !(result) {
    throw 3
  }
  result := $.includes.Call(list, 4)
  if (result) {
    throw 4
  }
}
shell_38() {
  string := "string"
  result := $.includes.Call(string, "s")
  if !(result) {
    throw 1
  }
  result := $.includes.Call(string, "a")
  if (result) {
    throw 2
  }
}
shell_39() {
  if !(($.type.Call($.i)) == "function") {
    throw 0
  }
}
shell_40() {
  result := $.gte.Call(2, 1)
  if !(result) {
    throw 0
  }
  result := $.gte.Call(1, 2)
  if (result) {
    throw 1
  }
  result := $.gte.Call(1, 1)
  if !(result) {
    throw 2
  }
}
shell_41() {
  result := $.gt.Call(2, 1)
  if !(result) {
    throw 0
  }
  result := $.gt.Call(1, 2)
  if (result) {
    throw 1
  }
  result := $.gt.Call(1, 1)
  if (result) {
    throw 2
  }
}
shell_42() {
  if !(($.type.Call($.getState)) == "function") {
    throw 0
  }
}
shell_43() {
  if !(($.type.Call($.getPosition)) == "function") {
    throw 0
  }
  $.move.Call([100, 100])
  __array__ := $.getPosition.Call()
  x := __array__[1]
  y := __array__[2]
  if !(x == 100 && y == 100) {
    throw 0
  }
}
shell_44() {
  if !(($.type.Call($.getColor)) == "function") {
    throw 0
  }
}
shell_45() {
  if !(($.type.Call($.get)) == "function") {
    throw 0
  }
}
shell_46() {
  key := "alt + ctrl + shift + win + esc"
  result := $.formatHotkey.Call(key)
  if !(result == "!^+#esc") {
    throw result
  }
}
shell_47() {
  key := "win + r"
  result := $.formatHotkey.Call(key)
  if !(result == "#r") {
    throw result
  }
}
shell_48() {
  key := "shift + a"
  result := $.formatHotkey.Call(key)
  if !(result == "+a") {
    throw result
  }
}
shell_49() {
  key := "ctrl + f5"
  result := $.formatHotkey.Call(key)
  if !(result == "^f5") {
    throw result
  }
}
shell_50() {
  key := "alt + f4"
  result := $.formatHotkey.Call(key)
  if !(result == "!f4") {
    throw result
  }
}
shell_51() {
  n := 1.2
  result := $.floor.Call(n)
  if !(result == 1) {
    throw result
  }
  n := -1.2
  result := $.floor.Call(n)
  if !(result == -2) {
    throw result
  }
}
shell_52() {
  list := [1, 2, 3]
  n := $.first.Call(list)
  if !(n == 1) {
    throw n
  }
}
shell_53() {
  if !(($.type.Call($.findImage)) == "function") {
    throw 0
  }
}
shell_54() {
  if !(($.type.Call($.findColor)) == "function") {
    throw 0
  }
}
shell_55(it) {
  return it != 2
}
shell_56() {
  list := [1, 2, 3]
  listA := $.filter.Call(list, Func("shell_55"))
  if !(($.join.Call(listA, "")) == "13") {
    throw 0
  }
}
shell_57() {
  if !(($.type.Call($.exit)) == "function") {
    throw 0
  }
}
shell_58() {
  mapA := {a: 1, b: 2}
  mapB := {a: 1, b: 2}
  if !($.eq.Call(mapA, mapB)) {
    throw 0
  }
  mapC := {a: 1, b: 2, c: 3}
  if ($.eq.Call(mapA, mapC)) {
    throw 1
  }
}
shell_59() {
  listA := [1, 2]
  listB := [1, 2]
  if !($.eq.Call(listA, listB)) {
    throw 0
  }
  listC := [1, 2, 3]
  if ($.eq.Call(listA, listC)) {
    throw 1
  }
}
shell_60() {
  stringA := "hello"
  stringB := "hello"
  if !($.eq.Call(stringA, stringB)) {
    throw 0
  }
  stringC := "aloha"
  if ($.eq.Call(stringA, stringC)) {
    throw 1
  }
}
shell_61() {
  a := 1
  b := 1
  if !($.eq.Call(a, b)) {
    throw 0
  }
  c := 2
  if ($.eq.Call(a, c)) {
    throw 1
  }
}
shell_62(listA, length, it, i) {
  listA[__ci_shell__.Call(length - i)] := it
}
shell_63() {
  list := [1, 2, 3, 4]
  listA := []
  length := $.length.Call(list)
  $.each.Call(list, Func("shell_62").Bind(listA, length))
  string := $.join.Call(list)
  if !(string := "4321") {
    throw string
  }
}
shell_64() {
  list := [1, 2, 3, 4, 5]
  listA := $.drop.Call(list)
  result := $.join.Call(listA, "")
  if !(result == "2345") {
    throw result
  }
  listB := $.drop.Call(list, 3)
  result := $.join.Call(listB, "")
  if !(result == "45") {
    throw result
  }
}
shell_65() {
  if !(($.type.Call($.delay)) == "function") {
    throw 0
  }
}
shell_66() {
  if !(($.type.Call($.defer)) == "function") {
    throw 0
  }
}
shell_67() {
  if !(($.type.Call($.debounce)) == "function") {
    throw 0
  }
}
shell_68() {
  if !(($.type.Call($.confirm)) == "function") {
    throw 0
  }
}
shell_69() {
  listA := $.concat.Call([1, 2, 3], 4, 5, [6, 7], 8, [9])
  if !(($.join.Call(listA, "")) == "123456789") {
    throw listA
  }
}
shell_70() {
  list := [0, 1, false, true, "", "x"]
  listA := $.compact.Call(list)
  if !(($.join.Call(listA, "")) == "11x") {
    throw listA
  }
}
shell_71() {
  if !(($.type.Call($.close)) == "function") {
    throw 0
  }
}
shell_72() {
  map := {a: 1, b: 2, c: 3}
  mapA := $.clone.Call(map)
  if !(($.join.Call([mapA.a, mapA.b, mapA.c], "")) == "123") {
    throw mapA
  }
}
shell_73() {
  list := [1, 2, 3]
  listA := $.clone.Call(list)
  if !(($.join.Call(listA, "")) == "123") {
    throw listA
  }
}
shell_74() {
  if !(($.type.Call($.click)) == "function") {
    throw 0
  }
}
shell_75() {
  if !(($.type.Call($.clearTimeout)) == "function") {
    throw 0
  }
}
shell_76() {
  if !(($.type.Call($.clearInterval)) == "function") {
    throw 0
  }
}
shell_77(it) {
  return $.join.Call(it, "")
}
shell_78() {
  list := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  listA := $.chunk.Call(list, 4)
  string := $.join.Call(($.map.Call(listA, Func("shell_77"))), ",")
  if !(string == "1234,5678,910") {
    throw string
  }
}
shell_79() {
  n := 1.2
  result := $.ceil.Call(n)
  if !(result == 2) {
    throw 0
  }
  n := -1.2
  result := $.ceil.Call(n)
  if !(result == -1) {
    throw 1
  }
}
shell_80() {
  if !(($.type.Call($.blockInput)) == "function") {
    throw 0
  }
}
shell_81() {
  if !(($.type.Call($.bind)) == "function") {
    throw 0
  }
}
shell_82() {
  if !(($.type.Call($.beep)) == "function") {
    throw 0
  }
}
shell_83() {
  if !(($.type.Call($.alert)) == "function") {
    throw 0
  }
}
shell_84() {
  a := 1
  b := 2
  c := 3
  d := -4
  result := $.add.Call(a)
  if !(result == 1) {
    throw result
  }
  result := $.add.Call(a, b, c)
  if !(result == 6) {
    throw result
  }
  result := $.add.Call(a, b, c, d)
  if !(result == 2) {
    throw result
  }
}
shell_85(name) {
  $.minimize.Call(name)
  isActive := $.isActive.Call(name)
  if (isActive) {
    throw 1
  }
  $.activate.Call(name)
  isActive := $.isActive.Call(name)
  if !(isActive) {
    throw 2
  }
  $.close.Call(name)
}
shell_86() {
  if !(($.type.Call($.activate)) == "function") {
    throw 0
  }
  name := "notepad.exe"
  $.close.Call(name)
  $.open.Call(name)
  $.wait.Call(name, Func("shell_85").Bind(name))
}
shell_87() {
  n := 42
  result := $.abs.Call(n)
  if !(result == 42) {
    throw result
  }
  n := -42
  result := $.abs.Call(n)
  if !(result == 42) {
    throw result
  }
}
shell_88(target, callback) {
  if !(target) {
    throw Exception("$.wait: target is required")
  }
  if !(callback) {
    throw Exception("$.wait: callback is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinWait, % __target__
  if !(($.type.Call(callback)) == "function") {
    return
  }
  callback.Call()
}
shell_89(input) {
  __listResult__ := []
  for __index_for__, __key__ in $.keys.Call(input) {
    $.push.Call(__listResult__, input[__ci_shell__.Call(__key__)])
  }
  return __listResult__
}
shell_90(list) {
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (($.type.Call(__item__)) == "string") {
      __hasString__ := true
      break
    }
  }
  __string__ := $.join.Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C U D,
  } else {
    Sort, __string__, N U D,
  }
  return $.split.Call(__string__, ",")
}
shell_91(input) {
  if input is Number
    return "number"
  if (IsFunc(input)) {
    return "function"
  }
  if (IsObject(input)) {
    if (input.Count() == input.Length()) {
      if !(input.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
shell_92(input, omitting := " `t") {
  return LTrim(input, omitting)
}
shell_93(input, omitting := " `t") {
  return RTrim(input, omitting)
}
shell_94(input, omitting := " `t") {
  return Trim(input, omitting)
}
shell_95(input) {
  StringUpper, __result__, input
  return __result__
}
shell_96(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in input {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in input {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return input
}
shell_97(input) {
  StringLower, __result__, input
  return __result__
}
shell_98(callback, index) {
  callback.Call()
  __tsThrottle__[__ci_shell__.Call(index)] := $.now.Call()
}
shell_99(callback, time, index) {
  $.clearTimeout.Call(__tThrottle__[__ci_shell__.Call(index)])
  __tThrottle__[__ci_shell__.Call(index)] := $.setTimeout.Call(Func("shell_98").Bind(callback, index), __tsThrottle__[__ci_shell__.Call(index)] - $.now.Call() + time)
}
shell_100(time, callback) {
  __iThrottle__++
  __tsThrottle__[__ci_shell__.Call(__iThrottle__)] := 0
  return Func("shell_99").Bind(callback, time, __iThrottle__)
}
shell_101(list, count := 1) {
  __len__ := $.length.Call(list)
  if !(__len__) {
    return []
  }
  if !(count >= 0) {
    return []
  }
  if (count >= __len__) {
    count := __len__
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if (__i__ >= count) {
      break
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_102(list) {
  return $.drop.Call(list, 1)
}
shell_103(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
shell_104(list) {
  __result__ := 0
  for __index_for__, __n__ in list {
    __result__ := __result__ + __n__
  }
  return __result__
}
shell_105(input, delimiter) {
  return StrSplit(input, delimiter)
}
shell_106(list) {
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (($.type.Call(__item__)) == "string") {
      __hasString__ := true
      break
    }
  }
  __string__ := $.join.Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C D,
  } else {
    Sort, __string__, N D,
  }
  return $.split.Call(__string__, ",")
}
shell_107(args) {
  switch $.length.Call(args) {
    case 1: {
      __array__ := [args[1], 0, $.length.Call(args[1])]
      __list__ := __array__[1]
      __start__ := __array__[2]
      __end__ := __array__[3]
    }
    case 2: {
      __array__ := [args[1], args[2], $.length.Call(args[1])]
      __list__ := __array__[1]
      __start__ := __array__[2]
      __end__ := __array__[3]
    }
    case 3: {
      __array__ := args
      __list__ := __array__[1]
      __start__ := __array__[2]
      __end__ := __array__[3]
    }
  }
  return [__list__, __start__, __end__]
}
shell_108(args*) {
  __array__ := __pickArgumentSlice__.Call(args)
  __list__ := __array__[1]
  __start__ := __array__[2]
  __end__ := __array__[3]
  __len__ := $.length.Call(__list__)
  if (__start__ > __len__) {
    __start__ := __len__
  }
  if (__start__ < 0) {
    __start__ := __len__ + __start__
  }
  if (__end__ > __len__) {
    __end__ := __len__
  }
  if (__end__ < 0) {
    __end__ := __len__ + __end__
  }
  __isReverse__ := false
  if (__start__ > __end__) {
    __isReverse__ := true
    __array__ := [__end__, __start__]
    __start__ := __array__[1]
    __end__ := __array__[2]
  }
  __listNew__ := []
  __n__ := 0
  __max__ := __end__ - __start__
  while (__n__ < __max__) {
    $.push.Call(__listNew__, __list__[__ci_shell__.Call(__start__ + __n__)])
    __n__++
  }
  if (__isReverse__) {
    return $.reverse.Call(__listNew__)
  }
  return __listNew__
}
shell_109(time) {
  if !(time > 0) {
    throw Exception("$.sleep: time is required")
  }
  Sleep, % time
}
shell_110(__split__, list) {
  __string__ := $.join.Call(list, ",")
  Sort, __string__, Random D,
  return __split__.Call(__string__, ",")
}
shell_111(callback, time) {
  callback := $.bind.Call(callback)
  if !($.isNumber.Call(time)) {
    throw Exception("$.setTimeout: invalid type")
  }
  if (time <= 0) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
shell_112(target, style) {
  if !(target) {
    throw Exception("$.setStyle: target is required")
  }
  if !(style) {
    throw Exception("$.setStyle: style is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinSet, Style, % style, % __target__
}
shell_113(callback, time) {
  callback := $.bind.Call(callback)
  if !(time > 0) {
    throw Exception("$.setInterval: invalid value")
  }
  SetTimer, % callback, % time
  return callback
}
shell_114(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
shell_115(n) {
  return Round(n)
}
shell_116(list) {
  __len__ := $.length.Call(list)
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    __listNew__[__ci_shell__.Call(__len__ - 1 - __i__)] := __item__
  }
  for __i__, __item__ in __listNew__ {
    __i__ := __i__ - 1
    list[__ci_shell__.Call(__i__)] := __item__
  }
  return list
}
shell_117(input, searchment, replacement, limit := -1) {
  return StrReplace(input, searchment, replacement, limit)
}
shell_118() {
  Reload
}
shell_119(args*) {
  switch $.length.Call(args) {
    case 1: {
      __array__ := [0, args[1], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 2: {
      __array__ := [args[1], args[2], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 3: {
      __array__ := args
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    default: {
      throw Exception("$.range: invalid arguments")
    }
  }
  if (__start__ == __end__) {
    return [__start__]
  }
  if (__start__ > __end__) {
    return []
  }
  __listResult__ := []
  __n__ := 0
  __max__ := __end__ - __start__
  while (__n__ < __max__) {
    $.push.Call(__listResult__, __start__ + __step__ * __n__)
    __n__++
  }
  return __listResult__
}
shell_120(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
shell_121(list, args*) {
  for __index_for__, __arg__ in args {
    list.Push(__arg__)
  }
  return list
}
shell_122(listInput) {
  if !($.length.Call(listInput)) {
    return false
  }
  __key__ := listInput[1]
  if ($.includes.Call(__key__, "-button")) {
    __key__ := $.replace.Call(__key__, "l-button", "left")
    __key__ := $.replace.Call(__key__, "m-button", "middle")
    __key__ := $.replace.Call(__key__, "r-button", "right")
    $.click.Call(__key__)
    return false
  }
  return true
}
shell_123(listInput) {
  __listKey__ := []
  for __index_for__, __input__ in listInput {
    __ipt__ := $.toLowerCase.Call(__input__)
    __ipt__ := $.replace.Call(__ipt__, " ", "")
    __ipt__ := $.replace.Call(__ipt__, "-", "")
    $.push.Call(__listKey__, ($.split.Call(__ipt__, "+"))*)
  }
  return __listKey__
}
shell_124(listInput*) {
  if !(__validateInputPress__.Call(listInput)) {
    return
  }
  __listKey__ := __formatInputPress__.Call(listInput)
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for __i__, __key__ in __listKey__ {
    __i__ := __i__ - 1
    if (__i__ == __len__ - 1) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      continue
    }
    if ($.includes.Call(__key__, ":")) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := $.split.Call(__key__, ":")
    } else {
      __listResult__[__ci_shell__.Call(__i__)] := [__key__, "down"]
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := [__key__, "up"]
    }
  }
  for __i__, __it__ in __listResult__ {
    __i__ := __i__ - 1
    if (__it__[1] == "win") {
      __it__[1] := "lwin"
    }
    __listResult__[__ci_shell__.Call(__i__)] := $.trim.Call("" . (__it__[1]) . " " . (__it__[2]) . "")
  }
  __result__ := ""
  for __index_for__, __it__ in __listResult__ {
    __result__ := "" . (__result__) . "{" . (__it__) . "}"
  }
  Send, % __result__
}
shell_125(filename) {
  SoundPlay, % filename
}
shell_126(source) {
  Run, % source
}
shell_127(__i__, callback, args*) {
  if (__cacheOnce__[__ci_shell__.Call(__i__)][1]) {
    return __cacheOnce__[__ci_shell__.Call(__i__)][2]
  }
  __result__ := callback.Call(args*)
  __cacheOnce__[__ci_shell__.Call(__i__)] := [true, __result__]
  return __result__
}
shell_128(callback) {
  __i__ := __indexOnce__
  __indexOnce__++
  __cacheOnce__[__ci_shell__.Call(__i__)] := [false, ""]
  return Func("shell_127").Bind(__i__, callback)
}
shell_129(list, n := 0) {
  if (n >= 0) {
    return list[__ci_shell__.Call(n)]
  } else {
    return list[__ci_shell__.Call(($.length.Call(list)) + n)]
  }
}
shell_130() {
  return A_TickCount
}
shell_131() {
  return
}
shell_132(point := "", speed := 0) {
  MouseMove, point[1], point[2], speed
}
shell_133(dividend, divisor) {
  return Mod(dividend, divisor)
}
shell_134(args*) {
  if !($.length.Call(args)) {
    throw Exception("$.mixin: invalid arguments")
  }
  __result__ := args[1]
  for __index_for__, __item__ in $.tail.Call(args) {
    for __key__, __value__ in __item__ {
      __result__[__ci_shell__.Call(__key__)] := __value__
    }
  }
  return __result__
}
shell_135(target := "") {
  if !(target) {
    throw Exception("$.minimize: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinMinimize, % __target__
}
shell_136(target) {
  if !(target) {
    throw Exception("$.maximize: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinMaximize, % __target__
}
shell_137(list, callback) {
  __listResult__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    $.push.Call(__listResult__, callback.Call(__item__, __i__))
  }
  return __listResult__
}
shell_138(value, other) {
  return value <= other
}
shell_139(value, other) {
  return value < other
}
shell_140(input) {
  __type__ := $.type.Call(input)
  switch __type__ {
    case "array": {
      return input.Length()
    }
    case "object": {
      return input.Count()
    }
    case "string": {
      return StrLen(input)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
shell_141(list) {
  return list[__ci_shell__.Call(($.length.Call(list)) - 1)]
}
shell_142(input) {
  __listResult__ := []
  for __key__, __value__ in input {
    $.push.Call(__listResult__, __key__)
  }
  return $.sort.Call(__listResult__)
}
shell_143(__name__, __item__) {
  __item__[1] != __name__
}
shell_144(this, key) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return
  }
  __listNew__ := $.filter.Call(this.mapCallback[__ci_shell__.Call(key)], Func("shell_143").Bind(__name__))
  if !($.length.Call(__listNew__)) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return
  }
  this.mapCallback[__ci_shell__.Call(key)] := __listNew__
}
shell_145(this, key, callback) {
  key := $.formatHotkey.Call($.replace.Call(key, ":down", ""))
  Hotkey, % key, % callback, On
}
shell_146(this, key, callback) {
  key := $.formatHotkey.Call($.replace.Call(key, ":down", ""))
  Hotkey, % key, % callback, Off
}
shell_147(key, this) {
  this.fire.Call(key)
}
shell_148(this, key) {
  if (this.mapCallback[__ci_shell__.Call(key)]) {
    return
  }
  this.mapCallback[__ci_shell__.Call(key)] := []
  __fn__ := Func("shell_147").Bind(key, this)
  this.mapBound[__ci_shell__.Call(key)] := __fn__
  this.on.Call(key, __fn__)
}
shell_149(this, key) {
  __array__ := $.split.Call(($.replace.Call(key, ":down", "")), ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
      __item__[2].Call()
    }
    return
  }
  for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
    if !(__item__[1] == __name__) {
      continue
    }
    __item__[2].Call()
    return
  }
}
shell_150(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  this.init.Call(key)
  $.push.Call(this.mapCallback[__ci_shell__.Call(key)], [__name__, callback])
}
shell_151(list, seperator := ",") {
  __result__ := ""
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__) {
      __result__ := __item__
      continue
    }
    __result__ := "" . (__result__) . "" . (seperator) . "" . (__item__) . ""
  }
  return __result__
}
shell_152(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "string") {
    return false
  }
  return true
}
shell_153(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "object") {
    return false
  }
  return true
}
shell_154(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "number") {
    return false
  }
  return true
}
shell_155(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "function") {
    return false
  }
  return true
}
shell_156(target) {
  return WinExist("ahk_exe " . (target) . "")
}
shell_157(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "array") {
    return false
  }
  return true
}
shell_158(target) {
  return WinActive("ahk_exe " . (target) . "")
}
shell_159(message, p := "") {
  if !(message) {
    return message
  }
  if !(p) {
    p := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % p[1], % p[2]
  return message
}
shell_160(input, needle) {
  __type__ := $.type.Call(input)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(input, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, __it__ in input {
      if (__it__ == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
shell_161(message) {
  $.info.Call("[" . ($.now.Call()) . "] " . ($.toString.Call(message)) . "", [0, 0])
  return message
}
shell_162(value, other) {
  return value >= other
}
shell_163(value, other) {
  return value > other
}
shell_164(key) {
  key := $.formatHotkey.Call(key)
  return GetKeyState(key, "P")
}
shell_165() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
shell_166(p := "") {
  if !(p) {
    p := $.getPosition.Call()
  }
  PixelGetColor, __result__, % p[1], % p[2], RGB
  return __result__
}
shell_167(url, callback) {
  try {
    whr := ComObjCreate("WinHttp.WinHttpRequest.5.1")
    whr.Open("GET", url, true)
    whr.Send()
    whr.WaitForResponse()
    callback.Call(whr.ResponseText)
  } catch {
    callback.Call("")
  }
}
shell_168(listKey) {
  if (($.length.Call(listKey)) == 1) {
    return ["", listKey]
  }
  __prefix__ := ""
  __listNew__ := []
  for __index_for__, __key__ in listKey {
    if (__key__ == "alt") {
      __prefix__ := "" . (__prefix__) . "!"
      continue
    }
    if (__key__ == "ctrl") {
      __prefix__ := "" . (__prefix__) . "^"
      continue
    }
    if (__key__ == "shift") {
      __prefix__ := "" . (__prefix__) . "+"
      continue
    }
    if (__key__ == "win") {
      __prefix__ := "" . (__prefix__) . "#"
      continue
    }
    $.push.Call(__listNew__, __key__)
  }
  return [__prefix__, __listNew__]
}
shell_169(key) {
  __listKey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  $.push.Call(__listKey__, ($.split.Call(__key__, "+"))*)
  return __listKey__
}
shell_170(key) {
  __listKey__ := __formatKeyFormatHotkey__.Call(key)
  __array__ := __pickPrefixFormatHotkey__.Call(__listKey__)
  __prefix__ := __array__[1]
  __listKey__ := __array__[2]
  __result__ := ""
  for __index_for__, __it__ in __listKey__ {
    __result__ := "" . (__result__) . " & " . (__it__) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
shell_171(n) {
  return Floor(n)
}
shell_172(list) {
  return list[1]
}
shell_173(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
shell_174(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
shell_175(list, callback) {
  __listResult__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(callback.Call(__item__, __i__)) {
      continue
    }
    $.push.Call(__listResult__, __item__)
  }
  return __listResult__
}
shell_176(name) {
  return new FileShellX(name)
}
shell_177(this, content) {
  this.delete.Call()
  return this.append.Call(content)
}
shell_178(this) {
  if !(this.exist.Call()) {
    return ""
  }
  FileRead, __result__, % this.name
  return $.replace.Call(__result__, "`r", "")
}
shell_179(this) {
  if !(this.exist.Call()) {
    return this
  }
  FileDelete, % this.name
  return this
}
shell_180(this) {
  if !(FileExist(this.name)) {
    return false
  }
  return true
}
shell_181(this, content) {
  FileAppend, % content, % this.name, UTF-8
  return content
}
shell_182() {
  ExitApp
}
shell_183(value, other) {
  __typeA__ := $.type.Call(value)
  __typeB__ := $.type.Call(other)
  if !(__typeA__ == __typeB__) {
    return false
  }
  if ($.includes.Call(["function", "number", "string"], __typeA__)) {
    return value == other
  }
  __lengthA__ := $.length.Call(value)
  __lengthB__ := $.length.Call(other)
  if !(__lengthA__ == __lengthB__) {
    return false
  }
  if (__typeA__ == "array") {
    for __i__, __it__ in value {
      __i__ := __i__ - 1
      if !(__eq__.Call(__it__, other[__ci_shell__.Call(__i__)])) {
        return false
      }
    }
    return true
  }
  for __k__, __v__ in value {
    if !(__eq__.Call(__v__, other[__ci_shell__.Call(__k__)])) {
      return false
    }
  }
  return true
}
shell_184() {
  return new EmitterShellX
}
shell_185(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  $.push.Call(this.bus, [__type__, __name__, callback])
  return this
}
shell_186(this, key) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    this.bus := []
    return this
  }
  if !(__name__) {
    __busNew__ := []
    for __index_for__, __item__ in this.bus {
      if (__item__[1] == __type__) {
        continue
      }
      $.push.Call(__busNew__, __item__)
    }
    this.bus := __busNew__
    return this
  }
  __busNew__ := []
  for __index_for__, __item__ in this.bus {
    if (__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    $.push.Call(__busNew__, __item__)
  }
  this.bus := __busNew__
  return this
}
shell_187(this, key, args*) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    return this
  }
  if !(__name__) {
    for __index_for__, __item__ in this.bus {
      if !(__item__[1] == __type__) {
        continue
      }
      __item__[3].Call(args*)
    }
    return this
  }
  for __index_for__, __item__ in this.bus {
    if !(__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    __item__[3].Call(args*)
  }
  return this
}
shell_188(list, callback) {
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    callback.Call(__item__, __i__)
  }
}
shell_189(n, _it, i) {
  return i >= n
}
shell_190(list, n := 1) {
  return $.filter.Call(list, Func("shell_189").Bind(n))
}
shell_191(callback, args) {
  callback.Call(args*)
}
shell_192(callback, time, args*) {
  __timer__ := $.setTimeout.Call(Func("shell_191").Bind(callback, args), time)
  return __timer__
}
shell_193(callback, args) {
  callback.Call(args*)
}
shell_194(callback, args*) {
  return $.delay.Call(Func("shell_193").Bind(callback, args), 1)
}
shell_195(callback, time, index) {
  $.clearTimeout.Call(__tDebounce__[__ci_shell__.Call(index)])
  __tDebounce__[__ci_shell__.Call(index)] := $.setTimeout.Call(callback, time)
}
shell_196(time, callback) {
  __iDebounce__++
  return Func("shell_195").Bind(callback, time, __iDebounce__)
}
shell_197(text, callback) {
  
  MsgBox, 0x4,, % text`
  IfMsgBox Yes
    callback.Call(true)
  else
    callback.Call(false)
  
}
shell_198(list, args*) {
  __listNew__ := $.clone.Call(list)
  for __index_for__, __arg__ in args {
    __type__ := $.type.Call(__arg__)
    if (__type__ == "array") {
      for __index_for__, __item__ in __arg__ {
        $.push.Call(__listNew__, __item__)
      }
    } else {
      $.push.Call(__listNew__, __arg__)
    }
  }
  return __listNew__
}
shell_199(it) {
  return it
}
shell_200(list) {
  return $.filter.Call(list, Func("shell_199"))
}
shell_201(target) {
  if !(target) {
    throw Exception("$.close: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinClose, % __target__
}
shell_202(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    return $.slice.Call(input)
  }
  if (__type__ == "object") {
    __mapNew__ := {}
    for __key__, __value__ in input {
      __mapNew__[__ci_shell__.Call(__key__)] := __value__
    }
    return __mapNew__
  }
  throw Exception("$.clone: invalid type '" . (__type__) . "'")
}
shell_203(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
shell_204(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_205(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_206(list, n := 1) {
  __listNew__ := []
  __length__ := $.length.Call(list)
  __i__ := 0
  while (__i__ < __length__ / n) {
    __listTemp__ := []
    __j__ := 0
    while (__j__ < n) {
      __index__ := __i__ * n + __j__
      if !(__index__ < __length__) {
        break
      }
      $.push.Call(__listTemp__, list[__ci_shell__.Call(__index__)])
      __j__++
    }
    $.push.Call(__listNew__, __listTemp__)
    __i__++
  }
  return __listNew__
}
shell_207(n) {
  return Ceil(n)
}
shell_208(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
shell_209(callback, args*) {
  if !(callback.Name) {
    if !($.length.Call(args)) {
      return callback
    }
    throw Exception("$.bind: cannot bind a bound function")
  }
  return callback.Bind(args*)
}
shell_210() {
  SoundBeep
}
shell_211(msg) {
  return $.toString.Call(msg)
}
shell_212(message*) {
  __msg__ := $.join.Call(($.map.Call(message, Func("shell_211"))), ", ")
  MsgBox, % __msg__
}
shell_213(args*) {
  __result__ := 0
  for __index_for__, __arg__ in args {
    __result__ := __result__ + __arg__
  }
  return __result__
}
shell_214(target) {
  if !(target) {
    throw Exception("$.activate: target is required")
  }
  __target__ := "ahk_exe " . (target) . ""
  WinActivate, % __target__
}
shell_215(n) {
  return Abs(n)
}
shell_216(input) {
  if input is Number
    return input + 1
  return input
}
