; Generated by Coffee-AHK/0.0.37
; Generated by Coffee-AHK/0.0.37
global __ci_shell__ := Func("shell_102")
global $ := {}
$.abs := Func("shell_101")
$.alert := Func("shell_100")
$.beep := Func("shell_99")
$.bind := Func("shell_98")
$.blockInput := Func("shell_97")
$.ceil := Func("shell_96")
$.chunk := Func("shell_95")
$.clearInterval := Func("shell_94")
$.clearTimeout := Func("shell_93")
$.click := Func("shell_92")
$.clone := Func("shell_91")
$.compact := Func("shell_90")
$.concat := Func("shell_89")
global __iDebounce__ := 0
global __tDebounce__ := {}
$.debounce := Func("shell_88")
$.defer := Func("shell_86")
$.delay := Func("shell_84")
$.drop := Func("shell_82")
class EmitterShellX {
  bus := []
  emit := Func("shell_81").Bind(this)
  off := Func("shell_80").Bind(this)
  on := Func("shell_79").Bind(this)
}
$.emitter := Func("shell_78")
$.exit := Func("shell_77")
class FileShellX {
  name := ""
  __New(name) {
    this.name := name
  }
  append := Func("shell_76").Bind(this)
  exist := Func("shell_75").Bind(this)
  delete := Func("shell_74").Bind(this)
  load := Func("shell_73").Bind(this)
  save := Func("shell_72").Bind(this)
}
$.file := Func("shell_71")
$.findColor := Func("shell_70")
$.findImage := Func("shell_69")
$.first := Func("shell_68")
$.head := $.first
$.floor := Func("shell_67")
$.formatHotkey := Func("shell_66")
global __formatKeyFormatHotkey__ := Func("shell_65")
global __setPrefixFormatHotkey__ := Func("shell_64")
$.getColor := Func("shell_63")
$.getPosition := Func("shell_62")
$.getState := Func("shell_61")
$.i := Func("shell_60")
$.includes := Func("shell_59")
$.info := Func("shell_58")
$.isArray := Func("shell_57")
$.isFunction := Func("shell_56")
$.isNumber := Func("shell_55")
$.isObject := Func("shell_54")
$.isString := Func("shell_53")
$.join := Func("shell_52")
class KeyBindingShellX {
  mapBound := {}
  mapCallback := {}
  add := Func("shell_51").Bind(this)
  fire := Func("shell_50").Bind(this)
  init := Func("shell_49").Bind(this)
  off := Func("shell_47").Bind(this)
  on := Func("shell_46").Bind(this)
  remove := Func("shell_45").Bind(this)
}
global keyBindingShell := new KeyBindingShellX()
$.off := keyBindingShell.remove
$.on := keyBindingShell.add
$.trigger := keyBindingShell.fire
$.keys := Func("shell_44")
$.last := Func("shell_43")
$.length := Func("shell_42")
$.mixin := Func("shell_41")
$.move := Func("shell_40")
$.noop := Func("shell_39")
$.now := Func("shell_38")
$.nth := Func("shell_37")
global __cacheOnce__ := {}
global __indexOnce__ := 0
$.once := Func("shell_36").Bind(args)
$.open := Func("shell_34")
$.play := Func("shell_33")
$.press := Func("shell_32")
global __formatInputPress__ := Func("shell_31")
global __validateInputPress__ := Func("shell_30")
$.push := Func("shell_29")
$.random := Func("shell_28")
$.range := Func("shell_27")
$.reload := Func("shell_26")
$.replace := Func("shell_25")
$.reverse := Func("shell_24")
$.round := Func("shell_23")
$.setFixed := Func("shell_22")
$.setInterval := Func("shell_21")
$.setTimeout := Func("shell_20")
$.shuffle := Func("shell_19").Bind(__split__)
$.sleep := Func("shell_18")
$.sort := Func("shell_17")
$.split := Func("shell_16")
$.suspend := Func("shell_15")
$.tail := Func("shell_14")
$.take := Func("shell_13")
global __iThrottle__ := 0
global __tThrottle__ := {}
global __tsThrottle__ := {}
$.throttle := Func("shell_12")
$.toLowerCase := Func("shell_9")
$.toLower := $.toLowerCase
$.toString := Func("shell_8")
$.toUpperCase := Func("shell_7")
$.toUpper := $.toUpperCase
$.trim := Func("shell_6")
$.trimEnd := Func("shell_5")
$.trimStart := Func("shell_4")
$.type := Func("shell_3")
$.uniq := Func("shell_2")
$.values := Func("shell_1")
$.VERSION := "0.0.4"
shell_1(input) {
  if !($.isObject.Call(input)) {
    throw Exception("$.values: invalid type")
  }
  __listResult__ := []
  for __index_for__, __key__ in $.keys.Call(input) {
    $.push.Call(__listResult__, input[__ci_shell__.Call(__key__)])
  }
  return __listResult__
}
shell_2(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.uniq: invalid type")
  }
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (($.type.Call(__item__)) == "string") {
      __hasString__ := true
      break
    }
  }
  __string__ := $.join.Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C U D,
  } else {
    Sort, __string__, N U D,
  }
  return $.split.Call(__string__, ",")
}
shell_3(input) {
  if input is Number
    return "number"
  if (IsFunc(input)) {
    return "function"
  }
  if (IsObject(input)) {
    if (input.Count() == input.Length()) {
      if !(input.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
shell_4(input, omitting := " `t") {
  return LTrim(input, omitting)
}
shell_5(input, omitting := " `t") {
  return RTrim(input, omitting)
}
shell_6(input, omitting := " `t") {
  return Trim(input, omitting)
}
shell_7(input) {
  StringUpper, __result__, input
  return __result__
}
shell_8(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in input {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in input {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return input
}
shell_9(input) {
  StringLower, __result__, input
  return __result__
}
shell_10(callback, index) {
  callback.Call()
  __tsThrottle__[__ci_shell__.Call(index)] := $.now.Call()
}
shell_11(callback, time, index) {
  $.clearTimeout.Call(__tThrottle__[__ci_shell__.Call(index)])
  __tThrottle__[__ci_shell__.Call(index)] := $.setTimeout.Call(Func("shell_10").Bind(callback, index), __tsThrottle__[__ci_shell__.Call(index)] - $.now.Call() + time)
}
shell_12(time, callback) {
  __iThrottle__++
  __tsThrottle__[__ci_shell__.Call(__iThrottle__)] := 0
  return Func("shell_11").Bind(callback, time, __iThrottle__)
}
shell_13(list, count := 1) {
  if !($.isArray.Call(list)) {
    throw Exception("$.take: invalid type")
  }
  __len__ := $.length.Call(list)
  if !(__len__) {
    return []
  }
  if !(count >= 0) {
    return []
  }
  if (count >= __len__) {
    count := __len__
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if (__i__ >= count) {
      break
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_14(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.tail: invalid type")
  }
  return $.drop.Call(list, 1)
}
shell_15(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
shell_16(input, delimiter) {
  return StrSplit(input, delimiter)
}
shell_17(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.sort: invalid type")
  }
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (($.type.Call(__item__)) == "string") {
      __hasString__ := true
      break
    }
  }
  __string__ := $.join.Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C D,
  } else {
    Sort, __string__, N D,
  }
  return $.split.Call(__string__, ",")
}
shell_18(time) {
  Sleep, % time
}
shell_19(__split__, list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.shuffle: invalid type")
  }
  __string__ := $.join.Call(list, ",")
  Sort, __string__, Random D,
  return __split__.Call(__string__, ",")
}
shell_20(callback, time) {
  if ($.isFunction.Call(callback)) {
    callback := $.bind.Call(callback)
  }
  if !($.isNumber.Call(time)) {
    throw Exception("$.setTimeout: invalid type")
  }
  if (time <= 0) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
shell_21(callback, time) {
  if ($.isFunction.Call(callback)) {
    callback := $.bind.Call(callback)
  }
  if !($.isNumber.Call(time)) {
    throw Exception("$.setInterval: invalid type")
  }
  if !(time > 0) {
    throw Exception("$.setInterval: invalid value")
  }
  SetTimer, % callback, % time
  return callback
}
shell_22(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
shell_23(n) {
  return Round(n)
}
shell_24(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.reverse: invalid type")
  }
  __len__ := $.length.Call(list)
  __listNew__ := []
  for __i__, __key__ in list {
    __i__ := __i__ - 1
    __listNew__[__ci_shell__.Call(__len__ - 1 - __i__)] := __key__
  }
  return __listNew__
}
shell_25(input, searchment, replacement, limit := -1) {
  return StrReplace(input, searchment, replacement, limit)
}
shell_26() {
  Reload
}
shell_27(args*) {
  switch $.length.Call(args) {
    case 1: {
      __array__ := [0, args[1], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 2: {
      __array__ := [args[1], args[2], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 3: {
      __array__ := args
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    default: {
      throw Exception("$.range: invalid arguments")
    }
  }
  if (__start__ == __end__) {
    return [__start__]
  }
  if (__start__ > __end__) {
    return []
  }
  __listResult__ := []
  __n__ := 0
  __max__ := __end__ - __start__
  while (__n__ < __max__) {
    $.push.Call(__listResult__, __start__ + __step__ * __n__)
    __n__++
  }
  return __listResult__
}
shell_28(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
shell_29(list, args*) {
  if !($.isArray.Call(list)) {
    throw Exception("$.push: invalid type")
  }
  for __index_for__, __arg__ in args {
    list.Push(__arg__)
  }
  return list
}
shell_30(listInput) {
  if !($.length.Call(listInput)) {
    return false
  }
  __key__ := listInput[1]
  if ($.includes.Call(__key__, "-button")) {
    __key__ := $.replace.Call(__key__, "l-button", "left")
    __key__ := $.replace.Call(__key__, "m-button", "middle")
    __key__ := $.replace.Call(__key__, "r-button", "right")
    $.click.Call(__key__)
    return false
  }
  return true
}
shell_31(listInput) {
  __listKey__ := []
  for __index_for__, __input__ in listInput {
    __ipt__ := $.toLowerCase.Call(__input__)
    __ipt__ := $.replace.Call(__ipt__, " ", "")
    __ipt__ := $.replace.Call(__ipt__, "-", "")
    $.push.Call(__listKey__, ($.split.Call(__ipt__, "+"))*)
  }
  return __listKey__
}
shell_32(listInput*) {
  if !(__validateInputPress__.Call(listInput)) {
    return
  }
  __listKey__ := __formatInputPress__.Call(listInput)
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for __i__, __key__ in __listKey__ {
    __i__ := __i__ - 1
    if (__i__ == __len__ - 1) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      continue
    }
    if ($.includes.Call(__key__, ":")) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := $.split.Call(__key__, ":")
    } else {
      __listResult__[__ci_shell__.Call(__i__)] := [__key__, "down"]
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := [__key__, "up"]
    }
  }
  for __i__, __it__ in __listResult__ {
    __i__ := __i__ - 1
    if (__it__[1] == "win") {
      __it__[1] := "lwin"
    }
    __listResult__[__ci_shell__.Call(__i__)] := $.trim.Call("" . (__it__[1]) . " " . (__it__[2]) . "")
  }
  __result__ := ""
  for __index_for__, __it__ in __listResult__ {
    __result__ := "" . (__result__) . "{" . (__it__) . "}"
  }
  Send, % __result__
}
shell_33(filename) {
  SoundPlay, % filename
}
shell_34(source) {
  Run, % source
}
shell_35(__i__, callback, args*) {
  if (__cacheOnce__[__ci_shell__.Call(__i__)][1]) {
    return __cacheOnce__[__ci_shell__.Call(__i__)][2]
  }
  __result__ := callback.Call(args*)
  __cacheOnce__[__ci_shell__.Call(__i__)] := [true, __result__]
  return __result__
}
shell_36(args, callback) {
  if !($.isFunction.Call(callback)) {
    throw Exception("$.once: invalid type")
  }
  __i__ := __indexOnce__
  __indexOnce__++
  __cacheOnce__[__ci_shell__.Call(__i__)] := [false, ""]
  return Func("shell_35").Bind(__i__, callback)
}
shell_37(list, n := 0) {
  if !($.isArray.Call(list)) {
    throw Exception("$.nth: invalid type")
  }
  if !($.isNumber.Call(n)) {
    throw Exception("$.nth: invalid type")
  }
  if (n >= 0) {
    return list[__ci_shell__.Call(n)]
  } else {
    return list[__ci_shell__.Call(($.length.Call(list)) + n)]
  }
}
shell_38() {
  return A_TickCount
}
shell_39() {
  return
}
shell_40(point := "", speed := 0) {
  if !(point) {
    throw Exception("$.move: invalid point")
  }
  MouseMove, point[1], point[2], speed
}
shell_41(args*) {
  switch $.length.Call(args) {
    case 1: {
      __array__ := [{}, args[1]]
      __target__ := __array__[1]
      __source__ := __array__[2]
    }
    case 2: {
      __array__ := args
      __target__ := __array__[1]
      __source__ := __array__[2]
    }
    default: {
      throw Exception("$.mixin: invalid arguments")
    }
  }
  if !($.isObject.Call(__target__)) {
    throw Exception("$.mixin: invalid type")
  }
  if !($.isObject.Call(__source__)) {
    throw Exception("$.mixin: invalid type")
  }
  for __key__, __value__ in __source__ {
    __target__[__ci_shell__.Call(__key__)] := __value__
  }
  return __target__
}
shell_42(input) {
  __type__ := $.type.Call(input)
  switch __type__ {
    case "array": {
      return input.Length()
    }
    case "object": {
      return input.Count()
    }
    case "string": {
      return StrLen(input)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
shell_43(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.last: invalid type")
  }
  return list[__ci_shell__.Call(($.length.Call(list)) - 1)]
}
shell_44(input) {
  if !($.isObject.Call(input)) {
    throw Exception("$.keys: invalid type")
  }
  __listResult__ := []
  for __key__, __value__ in input {
    $.push.Call(__listResult__, __key__)
  }
  return $.sort.Call(__listResult__)
}
shell_45(this, key) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return $
  }
  __listNew__ := []
  for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
    if (__item__[1] == __name__) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  if !($.length.Call(__listNew__)) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return $
  }
  this.mapCallback[__ci_shell__.Call(key)] := __listNew__
  return $
}
shell_46(this, key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, On
  return $
}
shell_47(this, key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, Off
  return $
}
shell_48(key, this) {
  this.fire.Call(key)
}
shell_49(this, key) {
  if (this.mapCallback[__ci_shell__.Call(key)]) {
    return $
  }
  this.mapCallback[__ci_shell__.Call(key)] := []
  __fn__ := Func("shell_48").Bind(key, this)
  this.mapBound[__ci_shell__.Call(key)] := __fn__
  this.on.Call(key, __fn__)
}
shell_50(this, key) {
  __array__ := $.split.Call(($.replace.Call(key, ":down", "")), ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
      __item__[2].Call()
    }
    return $
  }
  for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
    if !(__item__[1] == __name__) {
      continue
    }
    __item__[2].Call()
  }
  return $
}
shell_51(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  this.init.Call(key)
  $.push.Call(this.mapCallback[__ci_shell__.Call(key)], [__name__, callback])
  return $
}
shell_52(list, seperator := "") {
  if !($.isArray.Call(list)) {
    throw Exception("$.join: invalid type")
  }
  __result__ := ""
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__) {
      __result__ := __item__
      continue
    }
    __result__ := "" . (__result__) . "" . (seperator) . "" . (__item__) . ""
  }
  return __result__
}
shell_53(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "string") {
    return false
  }
  return true
}
shell_54(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "object") {
    return false
  }
  return true
}
shell_55(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "number") {
    return false
  }
  return true
}
shell_56(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "function") {
    return false
  }
  return true
}
shell_57(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "array") {
    return false
  }
  return true
}
shell_58(message, point := "") {
  if !(message) {
    return message
  }
  if !(point) {
    point := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % point[1], % point[2]
  return message
}
shell_59(input, needle) {
  __type__ := $.type.Call(input)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(input, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, __it__ in input {
      if (__it__ == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
shell_60(message) {
  $.info.Call("[" . ($.now.Call()) . "] " . ($.toString.Call(message)) . "", [0, 0])
  return message
}
shell_61(key) {
  key := $.formatHotkey.Call(key)
  return GetKeyState(key, "P")
}
shell_62() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
shell_63(point := "") {
  if !(point) {
    point := $.getPosition.Call()
  }
  PixelGetColor, __result__, % point[1], % point[2], RGB
  return __result__
}
shell_64(listKey) {
  __isAlt__ := false
  __isCtrl__ := false
  __isShift__ := false
  __isWin__ := false
  for __index_for__, __key__ in listKey {
    if (__key__ == "alt") {
      __isAlt__ := true
      continue
    }
    if (__key__ == "ctrl") {
      __isCtrl__ := true
      continue
    }
    if (__key__ == "shift") {
      __isShift__ := true
      continue
    }
    if (__key__ == "win") {
      __isWin__ := true
      continue
    }
  }
  __prefix__ := ""
  if (__isAlt__) {
    __prefix__ := "" . (__prefix__) . "!"
  }
  if (__isCtrl__) {
    __prefix__ := "" . (__prefix__) . "^"
  }
  if (__isShift__) {
    __prefix__ := "" . (__prefix__) . "+"
  }
  if (__isWin__) {
    __prefix__ := "" . (__prefix__) . "#"
  }
  return __prefix__
}
shell_65(key) {
  __listKey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  $.push.Call(__listKey__, ($.split.Call(__key__, "+"))*)
  return __listKey__
}
shell_66(key) {
  __listKey__ := __formatKeyFormatHotkey__.Call(key)
  __prefix__ := __setPrefixFormatHotkey__.Call(__listKey__)
  __result__ := ""
  for __index_for__, __it__ in __listKey__ {
    __result__ := "" . (__result__) . " & " . (__it__) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
shell_67(n) {
  return Floor(n)
}
shell_68(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.first: invalid type")
  }
  return list[1]
}
shell_69(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
shell_70(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
shell_71(name) {
  return new FileShellX(name)
}
shell_72(this, content) {
  this.delete.Call()
  return this.append.Call(content)
}
shell_73(this) {
  if !(this.exist.Call()) {
    return ""
  }
  FileRead, __result__, % this.name
  return $.replace.Call(__result__, "`r", "")
}
shell_74(this) {
  if !(this.exist.Call()) {
    return this
  }
  FileDelete, % this.name
  return this
}
shell_75(this) {
  if !(FileExist(this.name)) {
    return false
  }
  return true
}
shell_76(this, content) {
  FileAppend, % content, % this.name, UTF-8
  return content
}
shell_77() {
  ExitApp
}
shell_78() {
  return new EmitterShellX
}
shell_79(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  $.push.Call(this.bus, [__type__, __name__, callback])
  return this
}
shell_80(this, key) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    this.bus := []
    return this
  }
  if !(__name__) {
    __busNew__ := []
    for __index_for__, __item__ in this.bus {
      if (__item__[1] == __type__) {
        continue
      }
      $.push.Call(__busNew__, __item__)
    }
    this.bus := __busNew__
    return this
  }
  __busNew__ := []
  for __index_for__, __item__ in this.bus {
    if (__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    $.push.Call(__busNew__, __item__)
  }
  this.bus := __busNew__
  return this
}
shell_81(this, key, args*) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    return this
  }
  if !(__name__) {
    for __index_for__, __item__ in this.bus {
      if !(__item__[1] == __type__) {
        continue
      }
      __item__[3].Call(args*)
    }
    return this
  }
  for __index_for__, __item__ in this.bus {
    if !(__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    __item__[3].Call(args*)
  }
  return this
}
shell_82(list, n := 1) {
  if !($.isArray.Call(list)) {
    throw Exception("$.drop: invalid type")
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__ >= n) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_83(callback, args) {
  callback.Call(args*)
}
shell_84(callback, time, args*) {
  if !($.isFunction.Call(callback)) {
    throw Exception("$.delay: invalid type")
  }
  if !($.isNumber.Call(time)) {
    throw Exception("$.delay: invalid type")
  }
  __timer__ := $.setTimeout.Call(Func("shell_83").Bind(callback, args), time)
  return __timer__
}
shell_85(callback, args) {
  callback.Call(args*)
}
shell_86(callback, args*) {
  if !($.isFunction.Call(callback)) {
    throw Exception("$.defer: invalid type")
  }
  return $.delay.Call(Func("shell_85").Bind(callback, args), 1)
}
shell_87(callback, time, index) {
  $.clearTimeout.Call(__tDebounce__[__ci_shell__.Call(index)])
  __tDebounce__[__ci_shell__.Call(index)] := $.setTimeout.Call(callback, time)
}
shell_88(time, callback) {
  __iDebounce__++
  return Func("shell_87").Bind(callback, time, __iDebounce__)
}
shell_89(list, args*) {
  if !($.isArray.Call(list)) {
    throw Exception("$.concat: invalid type")
  }
  __listNew__ := $.clone.Call(list)
  for __index_for__, __arg__ in args {
    __type__ := $.type.Call(__arg__)
    if (__type__ == "array") {
      for __index_for__, __item__ in __arg__ {
        $.push.Call(__listNew__, __item__)
      }
    } else {
      $.push.Call(__listNew__, __arg__)
    }
  }
  return __listNew__
}
shell_90(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.compact: invalid type")
  }
  __listNew__ := []
  for __index_for__, __item__ in list {
    if !(__item__) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_91(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __listNew__ := []
    for __index_for__, __item__ in input {
      $.push.Call(__listNew__, __item__)
    }
    return __listNew__
  }
  if (__type__ == "object") {
    __mapNew__ := {}
    for __key__, __value__ in input {
      __mapNew__[__ci_shell__.Call(__key__)] := __value__
    }
    return __mapNew__
  }
  throw Exception("$.clone: invalid type '" . (__type__) . "'")
}
shell_92(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
shell_93(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_94(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_95(list, n := 1) {
  if !($.isArray.Call(list)) {
    throw Exception("$.chunk: invalid type")
  }
  __listNew__ := []
  __i__ := 0
  while (__i__ < ($.length.Call(list)) / n) {
    __listTemp__ := []
    __j__ := 0
    while (__j__ < n) {
      $.push.Call(__listTemp__, list[__ci_shell__.Call(__i__ * n + __j__)])
      __j__++
    }
    $.push.Call(__listNew__, __listTemp__)
    __i__++
  }
  return __listNew__
}
shell_96(n) {
  return Ceil(n)
}
shell_97(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
shell_98(callback, args*) {
  if !($.isFunction.Call(callback)) {
    throw Exception("$.bind: invalid type")
  }
  if !(callback.Name) {
    if !($.length.Call(args)) {
      return callback
    }
    throw Exception("$.bind: cannot bind a bound function")
  }
  return callback.Bind(args*)
}
shell_99() {
  SoundBeep
}
shell_100(message := "") {
  __msg__ := $.toString.Call(message)
  MsgBox, % __msg__
  return message
}
shell_101(n) {
  return Abs(n)
}
shell_102(input) {
  if input is Number
    return input + 1
  return input
}

$.on.Call("1", Func("script_1"))
script_1() {
  a := [3, 2, 10, 1, 4, 2]
  b := ["a", "c", "d", "b", 2]
  $.alert.Call($.uniq.Call(a))
}
