; Generated by Coffee-AHK/0.0.37
global __ci_genshin__ := Func("genshin_72")
global $ := {}
$.abs := Func("genshin_71")
$.alert := Func("genshin_70")
$.beep := Func("genshin_69")
$.blockInput := Func("genshin_68")
$.ceil := Func("genshin_67")
$.clearInterval := Func("genshin_66")
$.clearTimeout := Func("genshin_65")
$.click := Func("genshin_64")
global __index_debounce__ := 0
global __timer_debounce__ := {}
$.debounce := Func("genshin_63")
$.delay := Func("genshin_61")
class EmitterShellX {
  bus := []
  emit := Func("genshin_60").Bind(this)
  off := Func("genshin_59").Bind(this)
  on := Func("genshin_58").Bind(this)
}
$.emitter := Func("genshin_57")
$.exit := Func("genshin_56")
class FileShellX {
  name := ""
  __New(name) {
    this.name := name
  }
  append := Func("genshin_55").Bind(this)
  exist := Func("genshin_54").Bind(this)
  delete := Func("genshin_53").Bind(this)
  load := Func("genshin_52").Bind(this)
  save := Func("genshin_51").Bind(this)
}
$.file := Func("genshin_50")
$.findColor := Func("genshin_49")
$.findImage := Func("genshin_48")
$.floor := Func("genshin_47")
$.formatHotkey := Func("genshin_46")
$.getColor := Func("genshin_45")
$.getPosition := Func("genshin_44")
$.getState := Func("genshin_43")
$.i := Func("genshin_42")
$.includes := Func("genshin_41")
$.info := Func("genshin_40")
class KeyBindingShellX {
  mapBound := {}
  mapCallback := {}
  add := Func("genshin_39").Bind(this)
  fire := Func("genshin_38").Bind(this)
  init := Func("genshin_37").Bind(this)
  off := Func("genshin_35").Bind(this)
  on := Func("genshin_34").Bind(this)
  remove := Func("genshin_33").Bind(this)
}
global keyBindingShell := new KeyBindingShellX()
$.off := keyBindingShell.remove
$.on := keyBindingShell.add
$.trigger := keyBindingShell.fire
$.length := Func("genshin_32")
$.move := Func("genshin_31")
$.now := Func("genshin_30")
$.open := Func("genshin_29")
$.play := Func("genshin_28")
$.press := Func("genshin_27")
$.push := Func("genshin_26")
$.random := Func("genshin_25")
$.reload := Func("genshin_24")
$.replace := Func("genshin_23")
$.reverse := Func("genshin_22")
$.round := Func("genshin_21")
$.setFixed := Func("genshin_20")
$.setInterval := Func("genshin_19")
$.setTimeout := Func("genshin_18")
$.sleep := Func("genshin_17")
$.split := Func("genshin_16")
$.suspend := Func("genshin_15")
$.take := Func("genshin_14")
global __index_throttle__ := 0
global __timer_throttle__ := {}
global __ts_throttle__ := {}
$.throttle := Func("genshin_13")
$.toLowerCase := Func("genshin_10")
$.toString := Func("genshin_9")
$.toUpperCase := Func("genshin_8")
$.trim := Func("genshin_7")
$.trimEnd := Func("genshin_6")
$.trimStart := Func("genshin_5")
$.type := Func("genshin_4")
$.VERSION := "0.0.2"
$ := $
$.on.Call("a", Func("genshin_3")).on.Call("b", Func("genshin_2")).on.Call("c", Func("genshin_1"))
genshin_1() {
  $.off.Call("a")
}
genshin_2() {
  $.trigger.Call("a")
}
genshin_3() {
  $.info.Call($.now.Call())
}
genshin_4(input) {
  if input is Number
    return "number"
  if (IsFunc(input)) {
    return "function"
  }
  if (IsObject(input)) {
    if (input.Count() == input.Length()) {
      return "array"
    }
    return "object"
  }
  return "string"
}
genshin_5(input, omitting := " `t") {
  return LTrim(input, omitting)
}
genshin_6(input, omitting := " `t") {
  return RTrim(input, omitting)
}
genshin_7(input, omitting := " `t") {
  return Trim(input, omitting)
}
genshin_8(input) {
  StringUpper, __result__, input
  return __result__
}
genshin_9(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in input {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in input {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return input
}
genshin_10(input) {
  StringLower, __result__, input
  return __result__
}
genshin_11(callback, index) {
  callback.Call()
  __ts_throttle__[__ci_genshin__.Call(index)] := $.now.Call()
}
genshin_12(callback, time, index) {
  $.clearTimeout.Call(__timer_throttle__[__ci_genshin__.Call(index)])
  __timer_throttle__[__ci_genshin__.Call(index)] := $.setTimeout.Call(Func("genshin_11").Bind(callback, index), __ts_throttle__[__ci_genshin__.Call(index)] - $.now.Call() + time)
}
genshin_13(time, callback) {
  __index_throttle__++
  __ts_throttle__[__ci_genshin__.Call(__index_throttle__)] := 0
  return Func("genshin_12").Bind(callback, time, __index_throttle__)
}
genshin_14(list, count := 1) {
  __len__ := $.length.Call(list)
  if !(__len__) {
    return []
  }
  if !(count >= 0) {
    return []
  }
  if (count >= __len__) {
    count := __len__
  }
  __listNew__ := []
  for __i__, __item__ in list {
    if (__i__ >= count + 1) {
      break
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
genshin_15(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
genshin_16(input, delimiter) {
  return StrSplit(input, delimiter)
}
genshin_17(time) {
  Sleep, % time
}
genshin_18(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if (time <= 0) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
genshin_19(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if !(time > 0) {
    throw Exception("setTimeout: invalid time value '" . (time) . "'")
  }
  SetTimer, % callback, % time
  return callback
}
genshin_20(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
genshin_21(n) {
  return Round(n)
}
genshin_22(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "array") {
    throw Exception("$.reverse: invalid type '" . (__type__) . "'")
  }
  __len__ := $.length.Call(input)
  __output_as_array__ := []
  for i, key in input {
    i := i - 1
    __output_as_array__[__ci_genshin__.Call(__len__ - 1 - i)] := key
  }
  return __output_as_array__
}
genshin_23(input, searchment, replacement, limit := -1) {
  return StrReplace(input, searchment, replacement, limit)
}
genshin_24() {
  Reload
}
genshin_25(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
genshin_26(list, item) {
  list.Push(item)
  return list
}
genshin_27(listInput*) {
  if !($.length.Call(listInput)) {
    throw Exception("$.press: invalid key")
  }
  __listKey__ := []
  for __index_for__, input in listInput {
    __input__ := $.toLowerCase.Call(input)
    __input__ := $.replace.Call(__input__, " ", "")
    __input__ := $.replace.Call(__input__, "-", "")
    __list__ := $.split.Call(__input__, "+")
    for __index_for__, it in __list__ {
      $.push.Call(__listKey__, it)
    }
  }
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for i, key in __listKey__ {
    i := i - 1
    if (i == __len__ - 1) {
      __listResult__[__ci_genshin__.Call(i)] := $.split.Call(key, ":")
      continue
    }
    if ($.includes.Call(key, ":")) {
      __listResult__[__ci_genshin__.Call(i)] := $.split.Call(key, ":")
      __listResult__[__ci_genshin__.Call((__len__ - 1) * 2 - i)] := $.split.Call(key, ":")
    } else {
      __listResult__[__ci_genshin__.Call(i)] := [key, "down"]
      __listResult__[__ci_genshin__.Call((__len__ - 1) * 2 - i)] := [key, "up"]
    }
  }
  for i, it in __listResult__ {
    i := i - 1
    if (it[1] == "win") {
      it[1] := "lwin"
    }
    __listResult__[__ci_genshin__.Call(i)] := $.trim.Call("" . (it[1]) . " " . (it[2]) . "")
  }
  __output_as_string__ := ""
  for __index_for__, it in __listResult__ {
    __output_as_string__ := "" . (__output_as_string__) . "{" . (it) . "}"
  }
  Send, % __output_as_string__
}
genshin_28(filename) {
  SoundPlay, % filename
}
genshin_29(source) {
  Run, % source
}
genshin_30() {
  return A_TickCount
}
genshin_31(point := "", speed := 0) {
  if !(point) {
    throw Exception("$.move: invalid point")
  }
  MouseMove, point[1], point[2], speed
}
genshin_32(input) {
  __type__ := $.type.Call(input)
  switch __type__ {
    case "array": {
      return input.Length()
    }
    case "object": {
      return input.Count()
    }
    case "string": {
      return StrLen(input)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
genshin_33(this, key) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    this.mapCallback[__ci_genshin__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_genshin__.Call(key)])
    return $
  }
  __listNew__ := []
  for __index_for__, __item__ in this.mapCallback[__ci_genshin__.Call(key)] {
    if (__item__[1] == __name__) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  if !($.length.Call(__listNew__)) {
    this.mapCallback[__ci_genshin__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_genshin__.Call(key)])
    return $
  }
  this.mapCallback[__ci_genshin__.Call(key)] := __listNew__
  return $
}
genshin_34(this, key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, On
  return $
}
genshin_35(this, key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, Off
  return $
}
genshin_36(key, this) {
  this.fire.Call(key)
}
genshin_37(this, key) {
  if (this.mapCallback[__ci_genshin__.Call(key)]) {
    return $
  }
  this.mapCallback[__ci_genshin__.Call(key)] := []
  __fn__ := Func("genshin_36").Bind(key, this)
  this.mapBound[__ci_genshin__.Call(key)] := __fn__
  this.on.Call(key, __fn__)
}
genshin_38(this, key) {
  __array__ := $.split.Call(($.replace.Call(key, ":down", "")), ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    for __index_for__, __item__ in this.mapCallback[__ci_genshin__.Call(key)] {
      __item__[2].Call()
    }
    return $
  }
  for __index_for__, __item__ in this.mapCallback[__ci_genshin__.Call(key)] {
    if !(__item__[1] == __name__) {
      continue
    }
    __item__[2].Call()
  }
  return $
}
genshin_39(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  this.init.Call(key)
  $.push.Call(this.mapCallback[__ci_genshin__.Call(key)], [__name__, callback])
  return $
}
genshin_40(message, point := "") {
  if !(message) {
    return message
  }
  if !(point) {
    point := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % point[1], % point[2]
  return message
}
genshin_41(input, needle) {
  __type__ := $.type.Call(input)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(input, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, it in input {
      if (it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
genshin_42(message) {
  $.info.Call("[" . ($.now.Call()) . "] " . ($.toString.Call(message)) . "", [0, 0])
  return message
}
genshin_43(key) {
  key := $.formatHotkey.Call(key)
  return GetKeyState(key, "P")
}
genshin_44() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
genshin_45(point := "") {
  if !(point) {
    point := $.getPosition.Call()
  }
  PixelGetColor, __result__, % point[1], % point[2], RGB
  return __result__
}
genshin_46(key) {
  __listkey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  _list := $.split.Call(__key__, "+")
  for __index_for__, it in _list {
    $.push.Call(__listkey__, it)
  }
  __isAlt__ := false
  __isCtrl__ := false
  __isShift__ := false
  __isWin__ := false
  __listResult__ := []
  for __index_for__, key in __listkey__ {
    if (key == "alt") {
      __isAlt__ := true
      continue
    }
    if (key == "ctrl") {
      __isCtrl__ := true
      continue
    }
    if (key == "shift") {
      __isShift__ := true
      continue
    }
    if (key == "win") {
      __isWin__ := true
      continue
    }
    $.push.Call(__listResult__, key)
  }
  __prefix__ := ""
  if (__isAlt__) {
    __prefix__ := "" . (__prefix__) . "!"
  }
  if (__isCtrl__) {
    __prefix__ := "" . (__prefix__) . "^"
  }
  if (__isShift__) {
    __prefix__ := "" . (__prefix__) . "+"
  }
  if (__isWin__) {
    __prefix__ := "" . (__prefix__) . "#"
  }
  __result__ := ""
  for __index_for__, it in __listResult__ {
    __result__ := "" . (__result__) . " & " . (it) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
genshin_47(n) {
  return Floor(n)
}
genshin_48(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
genshin_49(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
genshin_50(name) {
  return new FileShellX(name)
}
genshin_51(this, content) {
  this.delete.Call()
  return this.append.Call(content)
}
genshin_52(this) {
  if !(this.exist.Call()) {
    return ""
  }
  FileRead, __result__, % this.name
  return $.replace.Call(__result__, "`r", "")
}
genshin_53(this) {
  if !(this.exist.Call()) {
    return this
  }
  FileDelete, % this.name
  return this
}
genshin_54(this) {
  if !(FileExist(this.name)) {
    return false
  }
  return true
}
genshin_55(this, content) {
  FileAppend, % content, % this.name, UTF-8
  return content
}
genshin_56() {
  ExitApp
}
genshin_57() {
  return new EmitterShellX
}
genshin_58(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  $.push.Call(this.bus, [__type__, __name__, callback])
  return this
}
genshin_59(this, key) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    this.bus := []
    return this
  }
  if !(__name__) {
    __busNew__ := []
    for __index_for__, __item__ in this.bus {
      if (__item__[1] == __type__) {
        continue
      }
      $.push.Call(__busNew__, __item__)
    }
    this.bus := __busNew__
    return this
  }
  __busNew__ := []
  for __index_for__, __item__ in this.bus {
    if (__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    $.push.Call(__busNew__, __item__)
  }
  this.bus := __busNew__
  return this
}
genshin_60(this, key, args*) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    return this
  }
  if !(__name__) {
    for __index_for__, __item__ in this.bus {
      if !(__item__[1] == __type__) {
        continue
      }
      __item__[3].Call(args*)
    }
    return this
  }
  for __index_for__, __item__ in this.bus {
    if !(__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    __item__[3].Call(args*)
  }
  return this
}
genshin_61(time, callback) {
  __timer__ := $.setTimeout.Call(callback, time)
  return __timer__
}
genshin_62(callback, time, index) {
  $.clearTimeout.Call(__timer_debounce__[__ci_genshin__.Call(index)])
  __timer_debounce__[__ci_genshin__.Call(index)] := $.setTimeout.Call(callback, time)
}
genshin_63(time, callback) {
  __index_debounce__++
  return Func("genshin_62").Bind(callback, time, __index_debounce__)
}
genshin_64(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
genshin_65(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
genshin_66(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
genshin_67(n) {
  return Ceil(n)
}
genshin_68(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
genshin_69() {
  SoundBeep
}
genshin_70(message := "") {
  __msg__ := $.toString.Call(message)
  MsgBox, % __msg__
  return message
}
genshin_71(n) {
  return Abs(n)
}
genshin_72(input) {
  if input is Number
    return input + 1
  return input
}
