; Generated by Coffee-AHK/0.0.54
global __rf_4m7e6icnutg__ := Func("4m7e6icnutg_68")
global __ci_4m7e6icnutg__ := Func("4m7e6icnutg_67")

#KeyHistory, 0
#MaxThreads, 20
#NoEnv
#Persistent
#SingleInstance, Force
#UseHook, On

CoordMode, Mouse, Client
CoordMode, Pixel, Client
CoordMode, ToolTip, Client
SendMode, Event
SetBatchLines, 100ms
SetKeyDelay, 0, 50
SetMouseDelay, 0, 50
StringCaseSense, On

global __4m7e6icnutg_module_1__ := (Func("4m7e6icnutg_66")).Call()
global __4m7e6icnutg_module_2__ := (Func("4m7e6icnutg_64")).Call()
global __4m7e6icnutg_module_5__ := (Func("4m7e6icnutg_62")).Call()
global __4m7e6icnutg_module_10__ := (Func("4m7e6icnutg_60")).Call()
global __4m7e6icnutg_module_11__ := (Func("4m7e6icnutg_58")).Call()
global __4m7e6icnutg_module_12__ := (Func("4m7e6icnutg_56")).Call()
global __4m7e6icnutg_module_13__ := (Func("4m7e6icnutg_54")).Call()
global __4m7e6icnutg_module_14__ := (Func("4m7e6icnutg_52")).Call()
global __4m7e6icnutg_module_15__ := (Func("4m7e6icnutg_50")).Call()
global __4m7e6icnutg_module_20__ := (Func("4m7e6icnutg_48")).Call()
global __4m7e6icnutg_module_24__ := (Func("4m7e6icnutg_46")).Call()
global __4m7e6icnutg_module_6__ := (Func("4m7e6icnutg_44")).Call()
global __4m7e6icnutg_module_8__ := (Func("4m7e6icnutg_42")).Call()
global __4m7e6icnutg_module_16__ := (Func("4m7e6icnutg_40")).Call()
global __4m7e6icnutg_module_17__ := (Func("4m7e6icnutg_38")).Call()
global __4m7e6icnutg_module_18__ := (Func("4m7e6icnutg_36")).Call()
global __4m7e6icnutg_module_21__ := (Func("4m7e6icnutg_34")).Call()
global __4m7e6icnutg_module_22__ := (Func("4m7e6icnutg_33")).Call()
global __4m7e6icnutg_module_23__ := (Func("4m7e6icnutg_29")).Call()
global keyBindingShell_filter := __4m7e6icnutg_module_20__
global keyBindingShell_forEach := __4m7e6icnutg_module_21__
global keyBindingShell_formatHotkey := __4m7e6icnutg_module_22__
global keyBindingShell_noop := __4m7e6icnutg_module_14__
global keyBindingShell_replace := __4m7e6icnutg_module_10__
global keyBindingShell_split := __4m7e6icnutg_module_11__
class KeyBindingShell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
    this.mapPrevented := {}
  }
  add := Func("4m7e6icnutg_27").Bind(this)
  fire := Func("4m7e6icnutg_26").Bind(this)
  formatKey := Func("4m7e6icnutg_24").Bind(this)
  getListItem := Func("4m7e6icnutg_23").Bind(this)
  isPrevented := Func("4m7e6icnutg_21").Bind(this)
  prepare := Func("4m7e6icnutg_20").Bind(this)
  prevent := Func("4m7e6icnutg_18").Bind(this)
  register := Func("4m7e6icnutg_17").Bind(this)
  remove := Func("4m7e6icnutg_16").Bind(this)
}
__rf_4m7e6icnutg__.Call(keyBindingShell_noop, "#rf/4m7e6icnutg/1").Call(KeyBindingShell)
global __4m7e6icnutg_module_19__ := (Func("4m7e6icnutg_14")).Call()
global __4m7e6icnutg_module_7__ := (Func("4m7e6icnutg_12")).Call()
global __4m7e6icnutg_module_9__ := (Func("4m7e6icnutg_11")).Call()
global __4m7e6icnutg_module_3__ := (Func("4m7e6icnutg_9")).Call()
global __4m7e6icnutg_module_4__ := (Func("4m7e6icnutg_8")).Call()
global $beep := __4m7e6icnutg_module_1__
global $exit := __4m7e6icnutg_module_2__
global $on := __4m7e6icnutg_module_3__
global $press := __4m7e6icnutg_module_4__
global $reload := __4m7e6icnutg_module_5__
global $sleep := __4m7e6icnutg_module_6__
global resetKyes := Func("4m7e6icnutg_4")
global main := Func("4m7e6icnutg_3")
__rf_4m7e6icnutg__.Call($on, "#rf/4m7e6icnutg/2").Call("f1", main)
__rf_4m7e6icnutg__.Call($on, "#rf/4m7e6icnutg/3").Call("f4", Func("4m7e6icnutg_2"))
__rf_4m7e6icnutg__.Call($on, "#rf/4m7e6icnutg/4").Call("f5", Func("4m7e6icnutg_1"))
4m7e6icnutg_1() {
  __rf_4m7e6icnutg__.Call($beep, "#rf/4m7e6icnutg/5").Call()
  __rf_4m7e6icnutg__.Call(resetKyes, "#rf/4m7e6icnutg/6").Call()
  __rf_4m7e6icnutg__.Call($reload, "#rf/4m7e6icnutg/7").Call()
}
4m7e6icnutg_2() {
  __rf_4m7e6icnutg__.Call($beep, "#rf/4m7e6icnutg/8").Call()
  __rf_4m7e6icnutg__.Call(resetKyes, "#rf/4m7e6icnutg/9").Call()
  __rf_4m7e6icnutg__.Call($exit, "#rf/4m7e6icnutg/10").Call()
}
4m7e6icnutg_3() {
  __rf_4m7e6icnutg__.Call($beep, "#rf/4m7e6icnutg/11").Call()
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/12").Call("e")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/13").Call(200)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/14").Call("e")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/15").Call("w:down")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/16").Call("space:down")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/17").Call(2000)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/18").Call("a:down")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/19").Call(750)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/20").Call("a:up")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/21").Call(750)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/22").Call("space:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/23").Call("w:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/24").Call("t")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/25").Call(3000)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/26").Call("t")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/27").Call(3000)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/28").Call("g")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/29").Call(200)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/30").Call("s")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/31").Call(200)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/32").Call("e")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/33").Call(500)
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/34").Call("e")
  __rf_4m7e6icnutg__.Call($sleep, "#rf/4m7e6icnutg/35").Call(5000)
  __rf_4m7e6icnutg__.Call(main, "#rf/4m7e6icnutg/36").Call()
  return
}
4m7e6icnutg_4() {
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/37").Call("a:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/38").Call("e:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/39").Call("g:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/40").Call("s:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/41").Call("space:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/42").Call("t:up")
  __rf_4m7e6icnutg__.Call($press, "#rf/4m7e6icnutg/43").Call("w:up")
}
4m7e6icnutg_5(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim, listInput*) {
  if !(__rf_4m7e6icnutg__.Call(press_validateInputPress, "#rf/4m7e6icnutg/44").Call(listInput)) {
    return
  }
  press_listKey := __rf_4m7e6icnutg__.Call(press_formatInputPress, "#rf/4m7e6icnutg/45").Call(listInput)
  press_listResult := []
  press_len := press_listKey.Length()
  for press_i, press_key in press_listKey {
    press_i := press_i - 1
    if (press_i == press_len - 1) {
      press_listResult[__ci_4m7e6icnutg__.Call(press_i)] := __rf_4m7e6icnutg__.Call(press_split, "#rf/4m7e6icnutg/46").Call(press_key, ":")
      continue
    }
    if (__rf_4m7e6icnutg__.Call(press_includes, "#rf/4m7e6icnutg/47").Call(press_key, ":")) {
      press_listResult[__ci_4m7e6icnutg__.Call(press_i)] := __rf_4m7e6icnutg__.Call(press_split, "#rf/4m7e6icnutg/48").Call(press_key, ":")
      press_listResult[__ci_4m7e6icnutg__.Call((press_len - 1) * 2 - press_i)] := __rf_4m7e6icnutg__.Call(press_split, "#rf/4m7e6icnutg/49").Call(press_key, ":")
    } else {
      press_listResult[__ci_4m7e6icnutg__.Call(press_i)] := [press_key, "down"]
      press_listResult[__ci_4m7e6icnutg__.Call((press_len - 1) * 2 - press_i)] := [press_key, "up"]
    }
  }
  for press_i, press_it in press_listResult {
    press_i := press_i - 1
    if (press_it[1] == "win") {
      press_it[1] := "lwin"
    }
    press_listResult[__ci_4m7e6icnutg__.Call(press_i)] := __rf_4m7e6icnutg__.Call(press_trim, "#rf/4m7e6icnutg/50").Call("" . (press_it[1]) . " " . (press_it[2]) . "")
  }
  press_result := ""
  for __index_for__, press_it in press_listResult {
    press_result := "" . (press_result) . "{" . (press_it) . "}"
  }
  Send, % press_result
  return
}
4m7e6icnutg_6(press_includes, press_replace, press_click, listInput) {
  if !(listInput.Length()) {
    return false
  }
  press_key := listInput[1]
  if (__rf_4m7e6icnutg__.Call(press_includes, "#rf/4m7e6icnutg/51").Call(press_key, "-button")) {
    press_key := __rf_4m7e6icnutg__.Call(press_replace, "#rf/4m7e6icnutg/52").Call(press_key, "l-button", "left")
    press_key := __rf_4m7e6icnutg__.Call(press_replace, "#rf/4m7e6icnutg/53").Call(press_key, "m-button", "middle")
    press_key := __rf_4m7e6icnutg__.Call(press_replace, "#rf/4m7e6icnutg/54").Call(press_key, "r-button", "right")
    __rf_4m7e6icnutg__.Call(press_click, "#rf/4m7e6icnutg/55").Call(press_key)
    return false
  }
  return true
}
4m7e6icnutg_7(press_toLowerCase, press_replace, press_split, listInput) {
  press_listKey := []
  for __index_for__, press_input in listInput {
    press_ipt := __rf_4m7e6icnutg__.Call(press_toLowerCase, "#rf/4m7e6icnutg/56").Call(press_input)
    press_ipt := __rf_4m7e6icnutg__.Call(press_replace, "#rf/4m7e6icnutg/57").Call(press_ipt, " ", "")
    press_ipt := __rf_4m7e6icnutg__.Call(press_replace, "#rf/4m7e6icnutg/58").Call(press_ipt, "-", "")
    press_listKey.Push((__rf_4m7e6icnutg__.Call(press_split, "#rf/4m7e6icnutg/59").Call(press_ipt, "+"))*)
  }
  return press_listKey
}
4m7e6icnutg_8() {
  press_click := __4m7e6icnutg_module_8__
  press_includes := __4m7e6icnutg_module_9__
  press_replace := __4m7e6icnutg_module_10__
  press_split := __4m7e6icnutg_module_11__
  press_toLowerCase := __4m7e6icnutg_module_12__
  press_trim := __4m7e6icnutg_module_13__
  press_formatInputPress := Func("4m7e6icnutg_7").Bind(press_toLowerCase, press_replace, press_split)
  press_validateInputPress := Func("4m7e6icnutg_6").Bind(press_includes, press_replace, press_click)
  return Func("4m7e6icnutg_5").Bind(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim)
}
4m7e6icnutg_9() {
  on_keyBindingXShell := __4m7e6icnutg_module_7__
  return on_keyBindingXShell.add
}
4m7e6icnutg_10(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray, ipt, needle) {
  includes_type := __rf_4m7e6icnutg__.Call(includes_getType, "#rf/4m7e6icnutg/60").Call(ipt)
  if ((__rf_4m7e6icnutg__.Call(includes_isString, "#rf/4m7e6icnutg/61").Call(ipt)) || __rf_4m7e6icnutg__.Call(includes_isNumber, "#rf/4m7e6icnutg/62").Call(ipt)) {
    if !(__rf_4m7e6icnutg__.Call(includes_isString, "#rf/4m7e6icnutg/63").Call(needle)) {
      return false
    }
    return (InStr((__rf_4m7e6icnutg__.Call(includes_toString, "#rf/4m7e6icnutg/64").Call(ipt)), needle)) > 0
  }
  if (__rf_4m7e6icnutg__.Call(includes_isArray, "#rf/4m7e6icnutg/65").Call(ipt)) {
    for __index_for__, includes_it in ipt {
      if (includes_it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("includes: invalid type '" . (includes_type) . "'")
}
4m7e6icnutg_11() {
  includes_getType := __4m7e6icnutg_module_15__
  includes_isArray := __4m7e6icnutg_module_16__
  includes_isNumber := __4m7e6icnutg_module_17__
  includes_isString := __4m7e6icnutg_module_18__
  includes_toString := __4m7e6icnutg_module_19__
  return Func("4m7e6icnutg_10").Bind(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray)
}
4m7e6icnutg_12() {
  return new KeyBindingShell()
}
4m7e6icnutg_13(toString_isArray, toString_trim, toString_isObject, ipt) {
  if (__rf_4m7e6icnutg__.Call(toString_isArray, "#rf/4m7e6icnutg/66").Call(ipt)) {
    toString_result := ""
    for __index_for__, toString_it in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_it) . ""
    }
    return "[" . (__rf_4m7e6icnutg__.Call(toString_trim, "#rf/4m7e6icnutg/67").Call(toString_result, " ,")) . "]"
  }
  if (__rf_4m7e6icnutg__.Call(toString_isObject, "#rf/4m7e6icnutg/68").Call(ipt)) {
    toString_result := ""
    for toString_key, toString_value in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_key) . ": " . (toString_value) . ""
    }
    return "{" . (__rf_4m7e6icnutg__.Call(toString_trim, "#rf/4m7e6icnutg/69").Call(toString_result, " ,")) . "}"
  }
  return ipt
}
4m7e6icnutg_14() {
  toString_isArray := __4m7e6icnutg_module_16__
  toString_isObject := __4m7e6icnutg_module_23__
  toString_trim := __4m7e6icnutg_module_13__
  return Func("4m7e6icnutg_13").Bind(toString_isArray, toString_trim, toString_isObject)
}
4m7e6icnutg_15(keyBindingShell_name, keyBindingShell_item) {
  return keyBindingShell_item[1] != keyBindingShell_name
}
4m7e6icnutg_16(this, keyMixed) {
  __array__ := __rf_4m7e6icnutg__.Call(keyBindingShell_split, "#rf/4m7e6icnutg/70").Call((__rf_4m7e6icnutg__.Call(keyBindingShell_replace, "#rf/4m7e6icnutg/71").Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    this.mapCallback[__ci_4m7e6icnutg__.Call(keyBindingShell_key)] := []
    return
  }
  keyBindingShell_listNew := __rf_4m7e6icnutg__.Call(keyBindingShell_filter, "#rf/4m7e6icnutg/72").Call(this.mapCallback[__ci_4m7e6icnutg__.Call(keyBindingShell_key)], Func("4m7e6icnutg_15").Bind(keyBindingShell_name))
  this.mapCallback[__ci_4m7e6icnutg__.Call(keyBindingShell_key)] := keyBindingShell_listNew
  return
}
4m7e6icnutg_17(this, key) {
  __rf_4m7e6icnutg__.Call(this.prepare, "#rf/4m7e6icnutg/73").Call(key)
  keyBindingShell_callback := this.mapBound[__ci_4m7e6icnutg__.Call(key)]
  keyBindingShell_key := __rf_4m7e6icnutg__.Call(this.formatKey, "#rf/4m7e6icnutg/74").Call(key, "~")
  if (this.mapPrevented[__ci_4m7e6icnutg__.Call(key)]) {
    keyBindingShell_key := __rf_4m7e6icnutg__.Call(this.formatKey, "#rf/4m7e6icnutg/75").Call(key)
  }
  __rf_4m7e6icnutg__.Call(keyBindingShell_noop, "#rf/4m7e6icnutg/76").Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
4m7e6icnutg_18(this, key, isPrevented) {
  __rf_4m7e6icnutg__.Call(this.prepare, "#rf/4m7e6icnutg/77").Call(key)
  this.mapPrevented[__ci_4m7e6icnutg__.Call(key)] := isPrevented
  keyBindingShell_callback := this.mapBound[__ci_4m7e6icnutg__.Call(key)]
  keyBindingShell_key := __rf_4m7e6icnutg__.Call(this.formatKey, "#rf/4m7e6icnutg/78").Call(key, "~")
  if (isPrevented) {
    keyBindingShell_key := __rf_4m7e6icnutg__.Call(this.formatKey, "#rf/4m7e6icnutg/79").Call(key)
  }
  __rf_4m7e6icnutg__.Call(keyBindingShell_noop, "#rf/4m7e6icnutg/80").Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
4m7e6icnutg_19(key, this) {
  return __rf_4m7e6icnutg__.Call(this.fire, "#rf/4m7e6icnutg/81").Call(key)
}
4m7e6icnutg_20(this, key) {
  if (this.mapCallback[__ci_4m7e6icnutg__.Call(key)]) {
    return
  }
  this.mapBound[__ci_4m7e6icnutg__.Call(key)] := Func("4m7e6icnutg_19").Bind(key, this)
  this.mapCallback[__ci_4m7e6icnutg__.Call(key)] := []
  this.mapPrevented[__ci_4m7e6icnutg__.Call(key)] := false
  return
}
4m7e6icnutg_21(this, key) {
  return this.mapPrevented[__ci_4m7e6icnutg__.Call(key)] == true
}
4m7e6icnutg_22(keyBindingShell_name, it) {
  return it[1] == keyBindingShell_name
}
4m7e6icnutg_23(this, keyMixed) {
  __array__ := __rf_4m7e6icnutg__.Call(keyBindingShell_split, "#rf/4m7e6icnutg/82").Call((__rf_4m7e6icnutg__.Call(keyBindingShell_replace, "#rf/4m7e6icnutg/83").Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  keyBindingShell_list := this.mapCallback[__ci_4m7e6icnutg__.Call(keyBindingShell_key)]
  if (keyBindingShell_name) {
    keyBindingShell_list := __rf_4m7e6icnutg__.Call(keyBindingShell_filter, "#rf/4m7e6icnutg/84").Call(keyBindingShell_list, Func("4m7e6icnutg_22").Bind(keyBindingShell_name))
  }
  return keyBindingShell_list
}
4m7e6icnutg_24(this, key, prefix := "") {
  keyBindingShell_key := __rf_4m7e6icnutg__.Call(keyBindingShell_formatHotkey, "#rf/4m7e6icnutg/85").Call(__rf_4m7e6icnutg__.Call(keyBindingShell_replace, "#rf/4m7e6icnutg/86").Call(key, ":down", ""))
  if !(prefix) {
    return keyBindingShell_key
  }
  return "" . (prefix) . "" . (keyBindingShell_key) . ""
}
4m7e6icnutg_25(it) {
  return __rf_4m7e6icnutg__.Call(it[2], "#rf/4m7e6icnutg/87").Call()
}
4m7e6icnutg_26(this, keyMixed) {
  return __rf_4m7e6icnutg__.Call(keyBindingShell_forEach, "#rf/4m7e6icnutg/88").Call((__rf_4m7e6icnutg__.Call(this.getListItem, "#rf/4m7e6icnutg/89").Call(keyMixed)), Func("4m7e6icnutg_25"))
}
4m7e6icnutg_27(this, keyMixed, callback) {
  __array__ := __rf_4m7e6icnutg__.Call(keyBindingShell_split, "#rf/4m7e6icnutg/90").Call((__rf_4m7e6icnutg__.Call(keyBindingShell_replace, "#rf/4m7e6icnutg/91").Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  __rf_4m7e6icnutg__.Call(this.register, "#rf/4m7e6icnutg/92").Call(keyBindingShell_key)
  this.mapCallback[__ci_4m7e6icnutg__.Call(keyBindingShell_key)].Push([keyBindingShell_name, callback])
  return
}
4m7e6icnutg_28(isObject_getType, ipt) {
  isObject_type := __rf_4m7e6icnutg__.Call(isObject_getType, "#rf/4m7e6icnutg/93").Call(ipt)
  if !(isObject_type == "object") {
    return false
  }
  return true
}
4m7e6icnutg_29() {
  isObject_getType := __4m7e6icnutg_module_15__
  return Func("4m7e6icnutg_28").Bind(isObject_getType)
}
4m7e6icnutg_30(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim, key) {
  formatHotkey_listKey := __rf_4m7e6icnutg__.Call(formatHotkey_formatKeyFormatHotkey, "#rf/4m7e6icnutg/94").Call(key)
  __array__ := __rf_4m7e6icnutg__.Call(formatHotkey_pickPrefixFormatHotkey, "#rf/4m7e6icnutg/95").Call(formatHotkey_listKey)
  formatHotkey_prefix := __array__[1]
  formatHotkey_listKey := __array__[2]
  formatHotkey_result := ""
  for __index_for__, formatHotkey_it in formatHotkey_listKey {
    formatHotkey_result := "" . (formatHotkey_result) . " & " . (formatHotkey_it) . ""
  }
  return __rf_4m7e6icnutg__.Call(formatHotkey_replace, "#rf/4m7e6icnutg/96").Call("" . (formatHotkey_prefix) . "" . (__rf_4m7e6icnutg__.Call(formatHotkey_trim, "#rf/4m7e6icnutg/97").Call(formatHotkey_result, " &")) . "", ":", " ")
}
4m7e6icnutg_31(listKey) {
  if (listKey.Length() == 1) {
    return ["", listKey]
  }
  formatHotkey_prefix := ""
  formatHotkey_listNew := []
  for __index_for__, formatHotkey_key in listKey {
    if (formatHotkey_key == "alt") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "!"
      continue
    }
    if (formatHotkey_key == "ctrl") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "^"
      continue
    }
    if (formatHotkey_key == "shift") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "+"
      continue
    }
    if (formatHotkey_key == "win") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "#"
      continue
    }
    formatHotkey_listNew.Push(formatHotkey_key)
  }
  return [formatHotkey_prefix, formatHotkey_listNew]
}
4m7e6icnutg_32(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split, key) {
  formatHotkey_listKey := []
  formatHotkey_key := __rf_4m7e6icnutg__.Call(formatHotkey_toLowerCase, "#rf/4m7e6icnutg/98").Call(key)
  formatHotkey_key := __rf_4m7e6icnutg__.Call(formatHotkey_replace, "#rf/4m7e6icnutg/99").Call(formatHotkey_key, " ", "")
  formatHotkey_key := __rf_4m7e6icnutg__.Call(formatHotkey_replace, "#rf/4m7e6icnutg/100").Call(formatHotkey_key, "-", "")
  formatHotkey_listSplit := __rf_4m7e6icnutg__.Call(formatHotkey_split, "#rf/4m7e6icnutg/101").Call(formatHotkey_key, "+")
  if (formatHotkey_listSplit.Length()) {
    formatHotkey_listKey.Push(formatHotkey_listSplit*)
  }
  return formatHotkey_listKey
}
4m7e6icnutg_33() {
  formatHotkey_replace := __4m7e6icnutg_module_10__
  formatHotkey_split := __4m7e6icnutg_module_11__
  formatHotkey_toLowerCase := __4m7e6icnutg_module_12__
  formatHotkey_trim := __4m7e6icnutg_module_13__
  formatHotkey_formatKeyFormatHotkey := Func("4m7e6icnutg_32").Bind(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split)
  formatHotkey_pickPrefixFormatHotkey := Func("4m7e6icnutg_31")
  return Func("4m7e6icnutg_30").Bind(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim)
}
4m7e6icnutg_34() {
  forEach_each := __4m7e6icnutg_module_24__
  return forEach_each
}
4m7e6icnutg_35(isString_getType, ipt) {
  isString_type := __rf_4m7e6icnutg__.Call(isString_getType, "#rf/4m7e6icnutg/102").Call(ipt)
  if !(isString_type == "string") {
    return false
  }
  return true
}
4m7e6icnutg_36() {
  isString_getType := __4m7e6icnutg_module_15__
  return Func("4m7e6icnutg_35").Bind(isString_getType)
}
4m7e6icnutg_37(isNumber_getType, ipt) {
  isNumber_type := __rf_4m7e6icnutg__.Call(isNumber_getType, "#rf/4m7e6icnutg/103").Call(ipt)
  if !(isNumber_type == "number") {
    return false
  }
  return true
}
4m7e6icnutg_38() {
  isNumber_getType := __4m7e6icnutg_module_15__
  return Func("4m7e6icnutg_37").Bind(isNumber_getType)
}
4m7e6icnutg_39(isArray_getType, ipt) {
  isArray_type := __rf_4m7e6icnutg__.Call(isArray_getType, "#rf/4m7e6icnutg/104").Call(ipt)
  if !(isArray_type == "array") {
    return false
  }
  return true
}
4m7e6icnutg_40() {
  isArray_getType := __4m7e6icnutg_module_15__
  return Func("4m7e6icnutg_39").Bind(isArray_getType)
}
4m7e6icnutg_41(click_replace, key := "left") {
  key := __rf_4m7e6icnutg__.Call(click_replace, "#rf/4m7e6icnutg/105").Call(key, "-", "")
  key := __rf_4m7e6icnutg__.Call(click_replace, "#rf/4m7e6icnutg/106").Call(key, ":", " ")
  Click, % key
  return
}
4m7e6icnutg_42() {
  click_replace := __4m7e6icnutg_module_10__
  return Func("4m7e6icnutg_41").Bind(click_replace)
}
4m7e6icnutg_43(sleep_noop, time := 1000) {
  __rf_4m7e6icnutg__.Call(sleep_noop, "#rf/4m7e6icnutg/107").Call(time)
  Sleep, % time
  return
}
4m7e6icnutg_44() {
  sleep_noop := __4m7e6icnutg_module_14__
  return Func("4m7e6icnutg_43").Bind(sleep_noop)
}
4m7e6icnutg_45(list, cb) {
  for each_i, each_item in list {
    each_i := each_i - 1
    __rf_4m7e6icnutg__.Call(cb, "#rf/4m7e6icnutg/108").Call(each_item, each_i)
  }
  return
}
4m7e6icnutg_46() {
  return Func("4m7e6icnutg_45")
}
4m7e6icnutg_47(list, cb) {
  filter_listNew := []
  for filter_i, filter_item in list {
    filter_i := filter_i - 1
    if !(__rf_4m7e6icnutg__.Call(cb, "#rf/4m7e6icnutg/109").Call(filter_item, filter_i)) {
      continue
    }
    filter_listNew.Push(filter_item)
  }
  return filter_listNew
}
4m7e6icnutg_48() {
  return Func("4m7e6icnutg_47")
}
4m7e6icnutg_49(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
4m7e6icnutg_50() {
  return Func("4m7e6icnutg_49")
}
4m7e6icnutg_51(_args*) {
  return
}
4m7e6icnutg_52() {
  return Func("4m7e6icnutg_51")
}
4m7e6icnutg_53(ipt, omitting := " `n`r`t") {
  return Trim(ipt, omitting)
}
4m7e6icnutg_54() {
  return Func("4m7e6icnutg_53")
}
4m7e6icnutg_55(ipt) {
  toLowerCase_result := ipt
  StringLower, toLowerCase_result, ipt
  return toLowerCase_result
}
4m7e6icnutg_56() {
  return Func("4m7e6icnutg_55")
}
4m7e6icnutg_57(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
4m7e6icnutg_58() {
  return Func("4m7e6icnutg_57")
}
4m7e6icnutg_59(original, searchment, replacement, count := -1) {
  return StrReplace(original, searchment, replacement, count)
}
4m7e6icnutg_60() {
  return Func("4m7e6icnutg_59")
}
4m7e6icnutg_61() {
  Reload
  return
}
4m7e6icnutg_62() {
  return Func("4m7e6icnutg_61")
}
4m7e6icnutg_63() {
  ExitApp
  return
}
4m7e6icnutg_64() {
  return Func("4m7e6icnutg_63")
}
4m7e6icnutg_65() {
  SoundBeep
  return
}
4m7e6icnutg_66() {
  return Func("4m7e6icnutg_65")
}
4m7e6icnutg_67(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}
4m7e6icnutg_68(__fn__, __token__) {
  if (__fn__) {
    return __fn__
  }
  throw Exception("invalid function: " . (__token__) . "")
}
