; Generated by Coffee-AHK/0.0.54
global __rf_z__ := Func("z_70")
global __ci_z__ := Func("z_69")

#KeyHistory, 0
#MaxThreads, 20
#NoEnv
#Persistent
#SingleInstance, Force
#UseHook, On

CoordMode, Mouse, Client
CoordMode, Pixel, Client
CoordMode, ToolTip, Client
SendMode, Event
SetBatchLines, 100ms
SetKeyDelay, 0, 50
SetMouseDelay, 0, 50
StringCaseSense, On

global __z_module_19__ := (Func("z_68")).Call()
global __z_module_20__ := (Func("z_66")).Call()
global __z_module_23__ := (Func("z_64")).Call()
global __z_module_28__ := (Func("z_62")).Call()
global __z_module_29__ := (Func("z_60")).Call()
global __z_module_30__ := (Func("z_58")).Call()
global __z_module_31__ := (Func("z_56")).Call()
global __z_module_32__ := (Func("z_54")).Call()
global __z_module_33__ := (Func("z_52")).Call()
global __z_module_38__ := (Func("z_50")).Call()
global __z_module_43__ := (Func("z_48")).Call()
global __z_module_24__ := (Func("z_46")).Call()
global __z_module_26__ := (Func("z_44")).Call()
global __z_module_34__ := (Func("z_42")).Call()
global __z_module_35__ := (Func("z_40")).Call()
global __z_module_36__ := (Func("z_38")).Call()
global __z_module_39__ := (Func("z_36")).Call()
global __z_module_40__ := (Func("z_35")).Call()
global __z_module_41__ := (Func("z_31")).Call()
global __z_module_42__ := (Func("z_29")).Call()
global keyBindingShell_filter := __z_module_38__
global keyBindingShell_forEach := __z_module_39__
global keyBindingShell_formatHotkey := __z_module_40__
global keyBindingShell_isFunction := __z_module_41__
global keyBindingShell_noop := __z_module_32__
global keyBindingShell_replace := __z_module_28__
global keyBindingShell_split := __z_module_29__
class KeyBindingShell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
    this.mapPrevented := {}
    return this
  }
  add := Func("z_27").Bind(this)
  fire := Func("z_26").Bind(this)
  formatKey := Func("z_24").Bind(this)
  getListItem := Func("z_23").Bind(this)
  isPrevented := Func("z_21").Bind(this)
  prepare := Func("z_20").Bind(this)
  prevent := Func("z_18").Bind(this)
  register := Func("z_17").Bind(this)
  remove := Func("z_16").Bind(this)
}
__rf_z__.Call(keyBindingShell_noop, "#rf/z/1").Call(KeyBindingShell)
global __z_module_37__ := (Func("z_14")).Call()
global __z_module_25__ := (Func("z_12")).Call()
global __z_module_27__ := (Func("z_11")).Call()
global __z_module_21__ := (Func("z_9")).Call()
global __z_module_22__ := (Func("z_8")).Call()
global $beep := __z_module_19__
global $exit := __z_module_20__
global $on := __z_module_21__
global $press := __z_module_22__
global $reload := __z_module_23__
global $sleep := __z_module_24__
global resetKyes := Func("z_4")
global main := Func("z_3")
__rf_z__.Call($on, "#rf/z/2").Call("f1", main)
__rf_z__.Call($on, "#rf/z/3").Call("f4", Func("z_2"))
__rf_z__.Call($on, "#rf/z/4").Call("f5", Func("z_1"))
z_1() {
  __rf_z__.Call($beep, "#rf/z/5").Call()
  __rf_z__.Call(resetKyes, "#rf/z/6").Call()
  __rf_z__.Call($reload, "#rf/z/7").Call()
}
z_2() {
  __rf_z__.Call($beep, "#rf/z/8").Call()
  __rf_z__.Call(resetKyes, "#rf/z/9").Call()
  __rf_z__.Call($exit, "#rf/z/10").Call()
}
z_3() {
  __rf_z__.Call($beep, "#rf/z/11").Call()
  __rf_z__.Call($press, "#rf/z/12").Call("e")
  __rf_z__.Call($sleep, "#rf/z/13").Call(200)
  __rf_z__.Call($press, "#rf/z/14").Call("e")
  __rf_z__.Call($press, "#rf/z/15").Call("w:down")
  __rf_z__.Call($press, "#rf/z/16").Call("space:down")
  __rf_z__.Call($sleep, "#rf/z/17").Call(2000)
  __rf_z__.Call($press, "#rf/z/18").Call("a:down")
  __rf_z__.Call($sleep, "#rf/z/19").Call(750)
  __rf_z__.Call($press, "#rf/z/20").Call("a:up")
  __rf_z__.Call($sleep, "#rf/z/21").Call(750)
  __rf_z__.Call($press, "#rf/z/22").Call("space:up")
  __rf_z__.Call($press, "#rf/z/23").Call("w:up")
  __rf_z__.Call($press, "#rf/z/24").Call("t")
  __rf_z__.Call($sleep, "#rf/z/25").Call(3000)
  __rf_z__.Call($press, "#rf/z/26").Call("t")
  __rf_z__.Call($sleep, "#rf/z/27").Call(3000)
  __rf_z__.Call($press, "#rf/z/28").Call("g")
  __rf_z__.Call($sleep, "#rf/z/29").Call(200)
  __rf_z__.Call($press, "#rf/z/30").Call("s")
  __rf_z__.Call($sleep, "#rf/z/31").Call(200)
  __rf_z__.Call($press, "#rf/z/32").Call("e")
  __rf_z__.Call($sleep, "#rf/z/33").Call(500)
  __rf_z__.Call($press, "#rf/z/34").Call("e")
  __rf_z__.Call($sleep, "#rf/z/35").Call(5000)
  __rf_z__.Call(main, "#rf/z/36").Call()
  return
}
z_4() {
  __rf_z__.Call($press, "#rf/z/37").Call("a:up")
  __rf_z__.Call($press, "#rf/z/38").Call("e:up")
  __rf_z__.Call($press, "#rf/z/39").Call("g:up")
  __rf_z__.Call($press, "#rf/z/40").Call("s:up")
  __rf_z__.Call($press, "#rf/z/41").Call("space:up")
  __rf_z__.Call($press, "#rf/z/42").Call("t:up")
  __rf_z__.Call($press, "#rf/z/43").Call("w:up")
}
z_5(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim, listInput*) {
  if !(__rf_z__.Call(press_validateInputPress, "#rf/z/44").Call(listInput)) {
    return
  }
  press_listKey := __rf_z__.Call(press_formatInputPress, "#rf/z/45").Call(listInput)
  press_listResult := []
  press_len := press_listKey.Length()
  for press_i, press_key in press_listKey {
    press_i := press_i - 1
    if (press_i == press_len - 1) {
      press_listResult[__ci_z__.Call(press_i)] := __rf_z__.Call(press_split, "#rf/z/46").Call(press_key, ":")
      continue
    }
    if (__rf_z__.Call(press_includes, "#rf/z/47").Call(press_key, ":")) {
      press_listResult[__ci_z__.Call(press_i)] := __rf_z__.Call(press_split, "#rf/z/48").Call(press_key, ":")
      press_listResult[__ci_z__.Call((press_len - 1) * 2 - press_i)] := __rf_z__.Call(press_split, "#rf/z/49").Call(press_key, ":")
    } else {
      press_listResult[__ci_z__.Call(press_i)] := [press_key, "down"]
      press_listResult[__ci_z__.Call((press_len - 1) * 2 - press_i)] := [press_key, "up"]
    }
  }
  for press_i, press_it in press_listResult {
    press_i := press_i - 1
    if (press_it[1] == "win") {
      press_it[1] := "lwin"
    }
    press_listResult[__ci_z__.Call(press_i)] := __rf_z__.Call(press_trim, "#rf/z/50").Call("" . (press_it[1]) . " " . (press_it[2]) . "")
  }
  press_result := ""
  for __index_for__, press_it in press_listResult {
    press_result := "" . (press_result) . "{" . (press_it) . "}"
  }
  Send, % press_result
  return
}
z_6(press_includes, press_replace, press_click, listInput) {
  if !(listInput.Length()) {
    return false
  }
  press_key := listInput[1]
  if (__rf_z__.Call(press_includes, "#rf/z/51").Call(press_key, "-button")) {
    press_key := __rf_z__.Call(press_replace, "#rf/z/52").Call(press_key, "l-button", "left")
    press_key := __rf_z__.Call(press_replace, "#rf/z/53").Call(press_key, "m-button", "middle")
    press_key := __rf_z__.Call(press_replace, "#rf/z/54").Call(press_key, "r-button", "right")
    __rf_z__.Call(press_click, "#rf/z/55").Call(press_key)
    return false
  }
  return true
}
z_7(press_toLowerCase, press_replace, press_split, listInput) {
  press_listKey := []
  for __index_for__, press_input in listInput {
    press_ipt := __rf_z__.Call(press_toLowerCase, "#rf/z/56").Call(press_input)
    press_ipt := __rf_z__.Call(press_replace, "#rf/z/57").Call(press_ipt, " ", "")
    press_ipt := __rf_z__.Call(press_replace, "#rf/z/58").Call(press_ipt, "-", "")
    press_listKey.Push((__rf_z__.Call(press_split, "#rf/z/59").Call(press_ipt, "+"))*)
  }
  return press_listKey
}
z_8() {
  press_click := __z_module_26__
  press_includes := __z_module_27__
  press_replace := __z_module_28__
  press_split := __z_module_29__
  press_toLowerCase := __z_module_30__
  press_trim := __z_module_31__
  press_formatInputPress := Func("z_7").Bind(press_toLowerCase, press_replace, press_split)
  press_validateInputPress := Func("z_6").Bind(press_includes, press_replace, press_click)
  return Func("z_5").Bind(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim)
}
z_9() {
  on_keyBinding := __z_module_25__
  return on_keyBinding.add
}
z_10(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray, ipt, needle) {
  includes_type := __rf_z__.Call(includes_getType, "#rf/z/60").Call(ipt)
  if ((__rf_z__.Call(includes_isString, "#rf/z/61").Call(ipt)) || __rf_z__.Call(includes_isNumber, "#rf/z/62").Call(ipt)) {
    if !(__rf_z__.Call(includes_isString, "#rf/z/63").Call(needle)) {
      return false
    }
    return (InStr((__rf_z__.Call(includes_toString, "#rf/z/64").Call(ipt)), needle)) > 0
  }
  if (__rf_z__.Call(includes_isArray, "#rf/z/65").Call(ipt)) {
    for __index_for__, includes_it in ipt {
      if (includes_it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("includes: invalid type '" . (includes_type) . "'")
}
z_11() {
  includes_getType := __z_module_33__
  includes_isArray := __z_module_34__
  includes_isNumber := __z_module_35__
  includes_isString := __z_module_36__
  includes_toString := __z_module_37__
  return Func("z_10").Bind(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray)
}
z_12() {
  return new KeyBindingShell()
}
z_13(toString_isArray, toString_trim, toString_isObject, ipt) {
  if (__rf_z__.Call(toString_isArray, "#rf/z/66").Call(ipt)) {
    toString_result := ""
    for __index_for__, toString_it in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_it) . ""
    }
    return "[" . (__rf_z__.Call(toString_trim, "#rf/z/67").Call(toString_result, " ,")) . "]"
  }
  if (__rf_z__.Call(toString_isObject, "#rf/z/68").Call(ipt)) {
    toString_result := ""
    for toString_key, toString_value in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_key) . ": " . (toString_value) . ""
    }
    return "{" . (__rf_z__.Call(toString_trim, "#rf/z/69").Call(toString_result, " ,")) . "}"
  }
  return ipt
}
z_14() {
  toString_isArray := __z_module_34__
  toString_isObject := __z_module_42__
  toString_trim := __z_module_31__
  return Func("z_13").Bind(toString_isArray, toString_trim, toString_isObject)
}
z_15(keyBindingShell_name, it) {
  return it[1] != keyBindingShell_name
}
z_16(this, keyMixed) {
  __array__ := __rf_z__.Call(keyBindingShell_split, "#rf/z/70").Call((__rf_z__.Call(keyBindingShell_replace, "#rf/z/71").Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := []
    return
  }
  keyBindingShell_listNew := __rf_z__.Call(keyBindingShell_filter, "#rf/z/72").Call(this.mapCallback[__ci_z__.Call(keyBindingShell_key)], Func("z_15").Bind(keyBindingShell_name))
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := keyBindingShell_listNew
  return
}
z_17(this, key) {
  __rf_z__.Call(this.prepare, "#rf/z/73").Call(key)
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := __rf_z__.Call(this.formatKey, "#rf/z/74").Call(key, "~")
  if (this.mapPrevented[__ci_z__.Call(key)]) {
    keyBindingShell_key := __rf_z__.Call(this.formatKey, "#rf/z/75").Call(key)
  }
  __rf_z__.Call(keyBindingShell_noop, "#rf/z/76").Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_18(this, key, isPrevented) {
  __rf_z__.Call(this.prepare, "#rf/z/77").Call(key)
  this.mapPrevented[__ci_z__.Call(key)] := isPrevented
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := __rf_z__.Call(this.formatKey, "#rf/z/78").Call(key, "~")
  if (isPrevented) {
    keyBindingShell_key := __rf_z__.Call(this.formatKey, "#rf/z/79").Call(key)
  }
  __rf_z__.Call(keyBindingShell_noop, "#rf/z/80").Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_19(key, this) {
  return __rf_z__.Call(this.fire, "#rf/z/81").Call(key)
}
z_20(this, key) {
  if (this.mapCallback[__ci_z__.Call(key)]) {
    return
  }
  this.mapBound[__ci_z__.Call(key)] := Func("z_19").Bind(key, this)
  this.mapCallback[__ci_z__.Call(key)] := []
  this.mapPrevented[__ci_z__.Call(key)] := false
  return
}
z_21(this, key) {
  return this.mapPrevented[__ci_z__.Call(key)] == true
}
z_22(keyBindingShell_name, it) {
  return it[1] == keyBindingShell_name
}
z_23(this, keyMixed) {
  __array__ := __rf_z__.Call(keyBindingShell_split, "#rf/z/82").Call((__rf_z__.Call(keyBindingShell_replace, "#rf/z/83").Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  keyBindingShell_list := this.mapCallback[__ci_z__.Call(keyBindingShell_key)]
  if !(keyBindingShell_list) {
    return []
  }
  if (keyBindingShell_name) {
    keyBindingShell_list := __rf_z__.Call(keyBindingShell_filter, "#rf/z/84").Call(keyBindingShell_list, Func("z_22").Bind(keyBindingShell_name))
  }
  return keyBindingShell_list
}
z_24(this, key, prefix := "") {
  keyBindingShell_key := __rf_z__.Call(keyBindingShell_formatHotkey, "#rf/z/85").Call(__rf_z__.Call(keyBindingShell_replace, "#rf/z/86").Call(key, ":down", ""))
  if !(prefix) {
    return keyBindingShell_key
  }
  return "" . (prefix) . "" . (keyBindingShell_key) . ""
}
z_25(keyMixed, it) {
  if !(__rf_z__.Call(keyBindingShell_isFunction, "#rf/z/87").Call(it[2])) {
    throw Exception("KeyBindingShell.fire: Callback is not a function for key: " . (keyMixed) . "")
  }
  __rf_z__.Call(it[2], "#rf/z/88").Call()
}
z_26(this, keyMixed) {
  __rf_z__.Call(keyBindingShell_forEach, "#rf/z/89").Call((__rf_z__.Call(this.getListItem, "#rf/z/90").Call(keyMixed)), Func("z_25").Bind(keyMixed))
  return
}
z_27(this, keyMixed, callback) {
  if !(__rf_z__.Call(keyBindingShell_isFunction, "#rf/z/91").Call(callback)) {
    throw Exception("KeyBindingShell.add: Callback is not a function for key: " . (keyMixed) . "")
  }
  __array__ := __rf_z__.Call(keyBindingShell_split, "#rf/z/92").Call((__rf_z__.Call(keyBindingShell_replace, "#rf/z/93").Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    keyBindingShell_name := ""
  }
  __rf_z__.Call(this.register, "#rf/z/94").Call(keyBindingShell_key)
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)].Push([keyBindingShell_name, callback])
  return
}
z_28(isObject_getType, ipt) {
  isObject_type := __rf_z__.Call(isObject_getType, "#rf/z/95").Call(ipt)
  if !(isObject_type == "object") {
    return false
  }
  return true
}
z_29() {
  isObject_getType := __z_module_33__
  return Func("z_28").Bind(isObject_getType)
}
z_30(isFunction_getType, ipt) {
  return (__rf_z__.Call(isFunction_getType, "#rf/z/96").Call(ipt)) == "function"
}
z_31() {
  isFunction_getType := __z_module_33__
  return Func("z_30").Bind(isFunction_getType)
}
z_32(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim, key) {
  formatHotkey_listKey := __rf_z__.Call(formatHotkey_formatKeyFormatHotkey, "#rf/z/97").Call(key)
  __array__ := __rf_z__.Call(formatHotkey_pickPrefixFormatHotkey, "#rf/z/98").Call(formatHotkey_listKey)
  formatHotkey_prefix := __array__[1]
  formatHotkey_listKey := __array__[2]
  formatHotkey_result := ""
  for __index_for__, formatHotkey_it in formatHotkey_listKey {
    formatHotkey_result := "" . (formatHotkey_result) . " & " . (formatHotkey_it) . ""
  }
  return __rf_z__.Call(formatHotkey_replace, "#rf/z/99").Call("" . (formatHotkey_prefix) . "" . (__rf_z__.Call(formatHotkey_trim, "#rf/z/100").Call(formatHotkey_result, " &")) . "", ":", " ")
}
z_33(listKey) {
  if (listKey.Length() == 1) {
    return ["", listKey]
  }
  formatHotkey_prefix := ""
  formatHotkey_listNew := []
  for __index_for__, formatHotkey_key in listKey {
    if (formatHotkey_key == "alt") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "!"
      continue
    }
    if (formatHotkey_key == "ctrl") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "^"
      continue
    }
    if (formatHotkey_key == "shift") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "+"
      continue
    }
    if (formatHotkey_key == "win") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "#"
      continue
    }
    formatHotkey_listNew.Push(formatHotkey_key)
  }
  return [formatHotkey_prefix, formatHotkey_listNew]
}
z_34(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split, key) {
  formatHotkey_listKey := []
  formatHotkey_key := __rf_z__.Call(formatHotkey_toLowerCase, "#rf/z/101").Call(key)
  formatHotkey_key := __rf_z__.Call(formatHotkey_replace, "#rf/z/102").Call(formatHotkey_key, " ", "")
  formatHotkey_key := __rf_z__.Call(formatHotkey_replace, "#rf/z/103").Call(formatHotkey_key, "-", "")
  formatHotkey_listSplit := __rf_z__.Call(formatHotkey_split, "#rf/z/104").Call(formatHotkey_key, "+")
  if (formatHotkey_listSplit.Length()) {
    formatHotkey_listKey.Push(formatHotkey_listSplit*)
  }
  return formatHotkey_listKey
}
z_35() {
  formatHotkey_replace := __z_module_28__
  formatHotkey_split := __z_module_29__
  formatHotkey_toLowerCase := __z_module_30__
  formatHotkey_trim := __z_module_31__
  formatHotkey_formatKeyFormatHotkey := Func("z_34").Bind(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split)
  formatHotkey_pickPrefixFormatHotkey := Func("z_33")
  return Func("z_32").Bind(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim)
}
z_36() {
  forEach_each := __z_module_43__
  return forEach_each
}
z_37(isString_getType, ipt) {
  isString_type := __rf_z__.Call(isString_getType, "#rf/z/105").Call(ipt)
  if !(isString_type == "string") {
    return false
  }
  return true
}
z_38() {
  isString_getType := __z_module_33__
  return Func("z_37").Bind(isString_getType)
}
z_39(isNumber_getType, ipt) {
  isNumber_type := __rf_z__.Call(isNumber_getType, "#rf/z/106").Call(ipt)
  if !(isNumber_type == "number") {
    return false
  }
  return true
}
z_40() {
  isNumber_getType := __z_module_33__
  return Func("z_39").Bind(isNumber_getType)
}
z_41(isArray_getType, ipt) {
  isArray_type := __rf_z__.Call(isArray_getType, "#rf/z/107").Call(ipt)
  if !(isArray_type == "array") {
    return false
  }
  return true
}
z_42() {
  isArray_getType := __z_module_33__
  return Func("z_41").Bind(isArray_getType)
}
z_43(click_replace, key := "left") {
  key := __rf_z__.Call(click_replace, "#rf/z/108").Call(key, "-", "")
  key := __rf_z__.Call(click_replace, "#rf/z/109").Call(key, ":", " ")
  Click, % key
  return
}
z_44() {
  click_replace := __z_module_28__
  return Func("z_43").Bind(click_replace)
}
z_45(sleep_noop, time := 1000) {
  __rf_z__.Call(sleep_noop, "#rf/z/110").Call(time)
  Sleep, % time
  return
}
z_46() {
  sleep_noop := __z_module_32__
  return Func("z_45").Bind(sleep_noop)
}
z_47(list, cb) {
  for each_i, each_item in list {
    each_i := each_i - 1
    __rf_z__.Call(cb, "#rf/z/111").Call(each_item, each_i)
  }
  return
}
z_48() {
  return Func("z_47")
}
z_49(list, cb) {
  filter_listNew := []
  for filter_i, filter_item in list {
    filter_i := filter_i - 1
    if !(__rf_z__.Call(cb, "#rf/z/112").Call(filter_item, filter_i)) {
      continue
    }
    filter_listNew.Push(filter_item)
  }
  return filter_listNew
}
z_50() {
  return Func("z_49")
}
z_51(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
z_52() {
  return Func("z_51")
}
z_53(_args*) {
  return
}
z_54() {
  return Func("z_53")
}
z_55(ipt, omitting := " `n`r`t") {
  return Trim(ipt, omitting)
}
z_56() {
  return Func("z_55")
}
z_57(ipt) {
  toLowerCase_result := ipt
  StringLower, toLowerCase_result, ipt
  return toLowerCase_result
}
z_58() {
  return Func("z_57")
}
z_59(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
z_60() {
  return Func("z_59")
}
z_61(original, searchment, replacement, count := -1) {
  return StrReplace(original, searchment, replacement, count)
}
z_62() {
  return Func("z_61")
}
z_63() {
  Reload
  return
}
z_64() {
  return Func("z_63")
}
z_65() {
  ExitApp
  return
}
z_66() {
  return Func("z_65")
}
z_67() {
  SoundBeep
  return
}
z_68() {
  return Func("z_67")
}
z_69(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}
z_70(__fn__, __token__) {
  if (__fn__) {
    return __fn__
  }
  throw Exception("invalid function: " . (__token__) . "")
}
