; Generated by Coffee-AHK/0.0.69
global __ci_z__ := Func("salt_1")
salt_1(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}

#KeyHistory, 0
#MaxThreads, 20
#NoEnv
#Persistent
#SingleInstance, Force
#UseHook, On

CoordMode, Mouse, Client
CoordMode, Pixel, Client
CoordMode, ToolTip, Client
SendMode, Event
SetBatchLines, 100ms
SetKeyDelay, 0, 50
SetMouseDelay, 0, 50
StringCaseSense, On

global __z_module_33__ := (Func("z_68")).Call()
global __z_module_34__ := (Func("z_66")).Call()
global __z_module_37__ := (Func("z_64")).Call()
global __z_module_42__ := (Func("z_62")).Call()
global __z_module_43__ := (Func("z_60")).Call()
global __z_module_44__ := (Func("z_58")).Call()
global __z_module_45__ := (Func("z_56")).Call()
global __z_module_46__ := (Func("z_54")).Call()
global __z_module_47__ := (Func("z_52")).Call()
global __z_module_52__ := (Func("z_50")).Call()
global __z_module_57__ := (Func("z_48")).Call()
global __z_module_38__ := (Func("z_46")).Call()
global __z_module_40__ := (Func("z_44")).Call()
global __z_module_48__ := (Func("z_42")).Call()
global __z_module_49__ := (Func("z_40")).Call()
global __z_module_50__ := (Func("z_38")).Call()
global __z_module_53__ := (Func("z_36")).Call()
global __z_module_54__ := (Func("z_35")).Call()
global __z_module_55__ := (Func("z_31")).Call()
global __z_module_56__ := (Func("z_29")).Call()
global keyBindingShell_filter := __z_module_52__.default
global keyBindingShell_forEach := __z_module_53__.default
global keyBindingShell_formatHotkey := __z_module_54__.default
global keyBindingShell_isFunction := __z_module_55__.default
global keyBindingShell_noop := __z_module_46__.default
global keyBindingShell_replace := __z_module_42__.default
global keyBindingShell_split := __z_module_43__.default
class ＫeyＢindingＳhell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
    this.mapPrevented := {}
  }
  add := Func("z_27").Bind(this)
  fire := Func("z_26").Bind(this)
  formatKey := Func("z_24").Bind(this)
  getListItem := Func("z_23").Bind(this)
  isPrevented := Func("z_21").Bind(this)
  prepare := Func("z_20").Bind(this)
  prevent := Func("z_18").Bind(this)
  register := Func("z_17").Bind(this)
  remove := Func("z_16").Bind(this)
}
keyBindingShell_noop.Call(ＫeyＢindingＳhell)
global __z_module_51__ := (Func("z_14")).Call()
global __z_module_39__ := (Func("z_12")).Call()
global __z_module_41__ := (Func("z_11")).Call()
global __z_module_35__ := (Func("z_9")).Call()
global __z_module_36__ := (Func("z_8")).Call()
global $beep := __z_module_33__.default
global $exit := __z_module_34__.default
global $on := __z_module_35__.default
global $press := __z_module_36__.default
global $reload := __z_module_37__.default
global $sleep := __z_module_38__.default
global resetKyes := Func("z_4")
global main := Func("z_3")
$on.Call("f1", main)
$on.Call("f4", Func("z_2"))
$on.Call("f5", Func("z_1"))
z_1() {
  $beep.Call()
  resetKyes.Call()
  $reload.Call()
}
z_2() {
  $beep.Call()
  resetKyes.Call()
  $exit.Call()
}
z_3() {
  $beep.Call()
  $press.Call("e")
  $sleep.Call(200)
  $press.Call("e")
  $press.Call("w:down")
  $press.Call("space:down")
  $sleep.Call(2000)
  $press.Call("a:down")
  $sleep.Call(750)
  $press.Call("a:up")
  $sleep.Call(750)
  $press.Call("space:up")
  $press.Call("w:up")
  $press.Call("t")
  $sleep.Call(3000)
  $press.Call("t")
  $sleep.Call(3000)
  $press.Call("g")
  $sleep.Call(200)
  $press.Call("s")
  $sleep.Call(200)
  $press.Call("e")
  $sleep.Call(500)
  $press.Call("e")
  $sleep.Call(5000)
  main.Call()
  return
}
z_4() {
  $press.Call("a:up")
  $press.Call("e:up")
  $press.Call("g:up")
  $press.Call("s:up")
  $press.Call("space:up")
  $press.Call("t:up")
  $press.Call("w:up")
}
z_5(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim, listInput*) {
  if !(press_validateInputPress.Call(listInput)) {
    return
  }
  press_listKey := press_formatInputPress.Call(listInput)
  press_listResult := []
  press_len := press_listKey.Length()
  for press_i, press_key in press_listKey {
    press_i := press_i - 1
    if (press_i == press_len - 1) {
      press_listResult[__ci_z__.Call(press_i)] := press_split.Call(press_key, ":")
      continue
    }
    if (press_includes.Call(press_key, ":")) {
      press_listResult[__ci_z__.Call(press_i)] := press_split.Call(press_key, ":")
      press_listResult[__ci_z__.Call((press_len - 1) * 2 - press_i)] := press_split.Call(press_key, ":")
    } else {
      press_listResult[__ci_z__.Call(press_i)] := [press_key, "down"]
      press_listResult[__ci_z__.Call((press_len - 1) * 2 - press_i)] := [press_key, "up"]
    }
  }
  for press_i, press_it in press_listResult {
    press_i := press_i - 1
    if (press_it[1] == "win") {
      press_it[1] := "lwin"
    }
    press_listResult[__ci_z__.Call(press_i)] := press_trim.Call("" . (press_it[1]) . " " . (press_it[2]) . "")
  }
  press_result := ""
  for __index_for__, press_it in press_listResult {
    press_result := "" . (press_result) . "{" . (press_it) . "}"
  }
  Send, % press_result
  return
}
z_6(press_includes, press_replace, press_click, listInput) {
  if !(listInput.Length()) {
    return false
  }
  press_key := listInput[1]
  if (press_includes.Call(press_key, "-button")) {
    press_key := press_replace.Call(press_key, "l-button", "left")
    press_key := press_replace.Call(press_key, "m-button", "middle")
    press_key := press_replace.Call(press_key, "r-button", "right")
    press_click.Call(press_key)
    return false
  }
  return true
}
z_7(press_toLowerCase, press_replace, press_split, listInput) {
  press_listKey := []
  for __index_for__, press_input in listInput {
    press_ipt := press_toLowerCase.Call(press_input)
    press_ipt := press_replace.Call(press_ipt, " ", "")
    press_ipt := press_replace.Call(press_ipt, "-", "")
    press_listKey.Push((press_split.Call(press_ipt, "+"))*)
  }
  return press_listKey
}
z_8() {
  press_click := __z_module_40__.default
  press_includes := __z_module_41__.default
  press_replace := __z_module_42__.default
  press_split := __z_module_43__.default
  press_toLowerCase := __z_module_44__.default
  press_trim := __z_module_45__.default
  press_formatInputPress := Func("z_7").Bind(press_toLowerCase, press_replace, press_split)
  press_validateInputPress := Func("z_6").Bind(press_includes, press_replace, press_click)
  return {default: Func("z_5").Bind(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim)}
}
z_9() {
  on_keyBinding := __z_module_39__.default
  return {default: on_keyBinding.add}
}
z_10(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray, ipt, needle) {
  includes_type := includes_getType.Call(ipt)
  if ((includes_isString.Call(ipt)) || includes_isNumber.Call(ipt)) {
    if !(includes_isString.Call(needle)) {
      return false
    }
    return (InStr((includes_toString.Call(ipt)), needle)) > 0
  }
  if (includes_isArray.Call(ipt)) {
    for __index_for__, includes_it in ipt {
      if (includes_it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("includes: invalid type '" . (includes_type) . "'")
}
z_11() {
  includes_getType := __z_module_47__.default
  includes_isArray := __z_module_48__.default
  includes_isNumber := __z_module_49__.default
  includes_isString := __z_module_50__.default
  includes_toString := __z_module_51__.default
  return {default: Func("z_10").Bind(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray)}
}
z_12() {
  return {default: new ＫeyＢindingＳhell()}
}
z_13(toString_isArray, toString_trim, toString_isObject, ipt) {
  if (toString_isArray.Call(ipt)) {
    toString_result := ""
    for __index_for__, toString_it in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_it) . ""
    }
    return "[" . (toString_trim.Call(toString_result, " ,")) . "]"
  }
  if (toString_isObject.Call(ipt)) {
    toString_result := ""
    for toString_key, toString_value in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_key) . ": " . (toString_value) . ""
    }
    return "{" . (toString_trim.Call(toString_result, " ,")) . "}"
  }
  return ipt
}
z_14() {
  toString_isArray := __z_module_48__.default
  toString_isObject := __z_module_56__.default
  toString_trim := __z_module_45__.default
  return {default: Func("z_13").Bind(toString_isArray, toString_trim, toString_isObject)}
}
z_15(keyBindingShell_name, it) {
  return it[1] != keyBindingShell_name
}
z_16(this, keyMixed) {
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := []
    return
  }
  keyBindingShell_listNew := keyBindingShell_filter.Call(this.mapCallback[__ci_z__.Call(keyBindingShell_key)], Func("z_15").Bind(keyBindingShell_name))
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := keyBindingShell_listNew
  return
}
z_17(this, key) {
  this.prepare.Call(key)
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := this.formatKey.Call(key, "~")
  if (this.mapPrevented[__ci_z__.Call(key)]) {
    keyBindingShell_key := this.formatKey.Call(key)
  }
  keyBindingShell_noop.Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_18(this, key, isPrevented) {
  this.prepare.Call(key)
  this.mapPrevented[__ci_z__.Call(key)] := isPrevented
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := this.formatKey.Call(key, "~")
  if (isPrevented) {
    keyBindingShell_key := this.formatKey.Call(key)
  }
  keyBindingShell_noop.Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_19(key, this) {
  return this.fire.Call(key)
}
z_20(this, key) {
  if (this.mapCallback[__ci_z__.Call(key)]) {
    return
  }
  this.mapBound[__ci_z__.Call(key)] := Func("z_19").Bind(key, this)
  this.mapCallback[__ci_z__.Call(key)] := []
  this.mapPrevented[__ci_z__.Call(key)] := false
  return
}
z_21(this, key) {
  return this.mapPrevented[__ci_z__.Call(key)] == true
}
z_22(keyBindingShell_name, it) {
  return it[1] == keyBindingShell_name
}
z_23(this, keyMixed) {
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  keyBindingShell_list := this.mapCallback[__ci_z__.Call(keyBindingShell_key)]
  if !(keyBindingShell_list) {
    return []
  }
  if (keyBindingShell_name) {
    keyBindingShell_list := keyBindingShell_filter.Call(keyBindingShell_list, Func("z_22").Bind(keyBindingShell_name))
  }
  return keyBindingShell_list
}
z_24(this, key, prefix := "") {
  keyBindingShell_key := keyBindingShell_formatHotkey.Call(keyBindingShell_replace.Call(key, ":down", ""))
  if !(prefix) {
    return keyBindingShell_key
  }
  return "" . (prefix) . "" . (keyBindingShell_key) . ""
}
z_25(keyMixed, it) {
  if !(keyBindingShell_isFunction.Call(it[2])) {
    throw Exception("KeyBindingShell.fire: Callback is not a function for key: " . (keyMixed) . "")
  }
  it[2].Call()
  return
}
z_26(this, keyMixed) {
  keyBindingShell_forEach.Call((this.getListItem.Call(keyMixed)), Func("z_25").Bind(keyMixed))
  return
}
z_27(this, keyMixed, callback) {
  if !(keyBindingShell_isFunction.Call(callback)) {
    throw Exception("KeyBindingShell.add: Callback is not a function for key: " . (keyMixed) . "")
  }
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    keyBindingShell_name := ""
  }
  this.register.Call(keyBindingShell_key)
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)].Push([keyBindingShell_name, callback])
  return
}
z_28(isObject_getType, ipt) {
  isObject_type := isObject_getType.Call(ipt)
  if !(isObject_type == "object") {
    return false
  }
  return true
}
z_29() {
  isObject_getType := __z_module_47__.default
  return {default: Func("z_28").Bind(isObject_getType)}
}
z_30(isFunction_getType, ipt) {
  return (isFunction_getType.Call(ipt)) == "function"
}
z_31() {
  isFunction_getType := __z_module_47__.default
  return {default: Func("z_30").Bind(isFunction_getType)}
}
z_32(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim, key) {
  formatHotkey_listKey := formatHotkey_formatKeyFormatHotkey.Call(key)
  __array__ := formatHotkey_pickPrefixFormatHotkey.Call(formatHotkey_listKey)
  formatHotkey_prefix := __array__[1]
  formatHotkey_listKey := __array__[2]
  formatHotkey_result := ""
  for __index_for__, formatHotkey_it in formatHotkey_listKey {
    formatHotkey_result := "" . (formatHotkey_result) . " & " . (formatHotkey_it) . ""
  }
  return formatHotkey_replace.Call("" . (formatHotkey_prefix) . "" . (formatHotkey_trim.Call(formatHotkey_result, " &")) . "", ":", " ")
}
z_33(listKey) {
  if (listKey.Length() == 1) {
    return ["", listKey]
  }
  formatHotkey_prefix := ""
  formatHotkey_listNew := []
  for __index_for__, formatHotkey_key in listKey {
    if (formatHotkey_key == "alt") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "!"
      continue
    }
    if (formatHotkey_key == "ctrl") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "^"
      continue
    }
    if (formatHotkey_key == "shift") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "+"
      continue
    }
    if (formatHotkey_key == "win") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "#"
      continue
    }
    formatHotkey_listNew.Push(formatHotkey_key)
  }
  return [formatHotkey_prefix, formatHotkey_listNew]
}
z_34(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split, key) {
  formatHotkey_listKey := []
  formatHotkey_key := formatHotkey_toLowerCase.Call(key)
  formatHotkey_key := formatHotkey_replace.Call(formatHotkey_key, " ", "")
  formatHotkey_key := formatHotkey_replace.Call(formatHotkey_key, "-", "")
  formatHotkey_listSplit := formatHotkey_split.Call(formatHotkey_key, "+")
  if (formatHotkey_listSplit.Length()) {
    formatHotkey_listKey.Push(formatHotkey_listSplit*)
  }
  return formatHotkey_listKey
}
z_35() {
  formatHotkey_replace := __z_module_42__.default
  formatHotkey_split := __z_module_43__.default
  formatHotkey_toLowerCase := __z_module_44__.default
  formatHotkey_trim := __z_module_45__.default
  formatHotkey_formatKeyFormatHotkey := Func("z_34").Bind(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split)
  formatHotkey_pickPrefixFormatHotkey := Func("z_33")
  return {default: Func("z_32").Bind(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim)}
}
z_36() {
  forEach_each := __z_module_57__.default
  return {default: forEach_each}
}
z_37(isString_getType, ipt) {
  isString_type := isString_getType.Call(ipt)
  if !(isString_type == "string") {
    return false
  }
  return true
}
z_38() {
  isString_getType := __z_module_47__.default
  return {default: Func("z_37").Bind(isString_getType)}
}
z_39(isNumber_getType, ipt) {
  isNumber_type := isNumber_getType.Call(ipt)
  if !(isNumber_type == "number") {
    return false
  }
  return true
}
z_40() {
  isNumber_getType := __z_module_47__.default
  return {default: Func("z_39").Bind(isNumber_getType)}
}
z_41(isArray_getType, ipt) {
  isArray_type := isArray_getType.Call(ipt)
  if !(isArray_type == "array") {
    return false
  }
  return true
}
z_42() {
  isArray_getType := __z_module_47__.default
  return {default: Func("z_41").Bind(isArray_getType)}
}
z_43(click_replace, key := "left") {
  key := click_replace.Call(key, "-", "")
  key := click_replace.Call(key, ":", " ")
  Click, % key
  return
}
z_44() {
  click_replace := __z_module_42__.default
  return {default: Func("z_43").Bind(click_replace)}
}
z_45(sleep_noop, time := 1000) {
  sleep_noop.Call(time)
  Sleep, % time
  return
}
z_46() {
  sleep_noop := __z_module_46__.default
  return {default: Func("z_45").Bind(sleep_noop)}
}
z_47(list, cb) {
  for each_i, each_item in list {
    each_i := each_i - 1
    cb.Call(each_item, each_i)
  }
  return
}
z_48() {
  return {default: Func("z_47")}
}
z_49(list, cb) {
  filter_listNew := []
  for filter_i, filter_item in list {
    filter_i := filter_i - 1
    if !(cb.Call(filter_item, filter_i)) {
      continue
    }
    filter_listNew.Push(filter_item)
  }
  return filter_listNew
}
z_50() {
  return {default: Func("z_49")}
}
z_51(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
z_52() {
  return {default: Func("z_51")}
}
z_53(_args*) {
  return
}
z_54() {
  return {default: Func("z_53")}
}
z_55(ipt, omitting := " `n`r`t") {
  return Trim(ipt, omitting)
}
z_56() {
  return {default: Func("z_55")}
}
z_57(ipt) {
  toLowerCase_result := ipt
  StringLower, toLowerCase_result, ipt
  return toLowerCase_result
}
z_58() {
  return {default: Func("z_57")}
}
z_59(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
z_60() {
  return {default: Func("z_59")}
}
z_61(original, searchment, replacement, count := -1) {
  return StrReplace(original, searchment, replacement, count)
}
z_62() {
  return {default: Func("z_61")}
}
z_63() {
  Reload
  return
}
z_64() {
  return {default: Func("z_63")}
}
z_65() {
  ExitApp
  return
}
z_66() {
  return {default: Func("z_65")}
}
z_67() {
  SoundBeep
  return
}
z_68() {
  return {default: Func("z_67")}
}