; Generated by Coffee-AHK/0.0.36
global __ci_z__ := Func("z_64")

#KeyHistory, 0
#MaxThreads, 20
#NoEnv
#Persistent
#SingleInstance, Force
#UseHook, On

CoordMode, Mouse, Client
CoordMode, Pixel, Client
CoordMode, ToolTip, Client
SendMode, Event
SetBatchLines, 100ms
SetKeyDelay, 0, 50
SetMouseDelay, 0, 50
StringCaseSense, On

global __z_module_1__ := (Func("z_63")).Call()
global __z_module_3__ := (Func("z_61")).Call()
global __z_module_6__ := (Func("z_59")).Call()
global __z_module_7__ := (Func("z_57")).Call()
global __z_module_11__ := (Func("z_55")).Call()
global __z_module_12__ := (Func("z_53")).Call()
global __z_module_13__ := (Func("z_51")).Call()
global __z_module_14__ := (Func("z_49")).Call()
global __z_module_15__ := (Func("z_47")).Call()
global __z_module_16__ := (Func("z_45")).Call()
global __z_module_17__ := (Func("z_43")).Call()
global $noop := __z_module_6__
class WindowShell {
  __New(exe) {
    this.exe := "ahk_exe " . (exe) . ""
  }
  blur := Func("z_41").Bind(this)
  close := Func("z_40").Bind(this)
  focus := Func("z_39").Bind(this)
  getBounds := Func("z_38").Bind(this)
  hide := Func("z_37").Bind(this)
  isActive := Func("z_36").Bind(this)
  isExists := Func("z_35").Bind(this)
  isFullScreen := Func("z_34").Bind(this)
  kill := Func("z_33").Bind(this)
  maximize := Func("z_32").Bind(this)
  minimize := Func("z_31").Bind(this)
  restore := Func("z_30").Bind(this)
  setPriority := Func("z_29").Bind(this)
  setStyle := Func("z_28").Bind(this)
  show := Func("z_27").Bind(this)
  wait := Func("z_26").Bind(this)
}
$noop.Call(WindowShell)
global __z_module_8__ := (Func("z_25")).Call()
global __z_module_9__ := (Func("z_24")).Call()
global __z_module_10__ := (Func("z_20")).Call()
global __z_module_4__ := (Func("z_18")).Call()
global keyBindingShell_filter := __z_module_7__
global keyBindingShell_forEach := __z_module_8__
global keyBindingShell_formatHotkey := __z_module_9__
global keyBindingShell_isFunction := __z_module_10__
global keyBindingShell_noop := __z_module_11__
global keyBindingShell_replace := __z_module_12__
global keyBindingShell_split := __z_module_13__
class KeyBindingShell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
    this.mapPrevented := {}
  }
  add := Func("z_16").Bind(this)
  fire := Func("z_15").Bind(this)
  formatKey := Func("z_13").Bind(this)
  getListItem := Func("z_12").Bind(this)
  isPrevented := Func("z_10").Bind(this)
  prepare := Func("z_9").Bind(this)
  prevent := Func("z_7").Bind(this)
  register := Func("z_6").Bind(this)
  remove := Func("z_5").Bind(this)
}
keyBindingShell_noop.Call(KeyBindingShell)
global __z_module_5__ := (Func("z_3")).Call()
global __z_module_2__ := (Func("z_2")).Call()
global $beep := __z_module_1__
global $on := __z_module_2__
global $reload := __z_module_3__
global $window := __z_module_4__
$on.Call("esc", Func("z_1"))
z_1() {
  $beep.Call()
  $reload.Call()
}
z_2() {
  on_keyBinding := __z_module_5__
  return on_keyBinding.add
}
z_3() {
  return new KeyBindingShell()
}
z_4(keyBindingShell_name, it) {
  return it[1] != keyBindingShell_name
}
z_5(this, keyMixed) {
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := []
    return
  }
  keyBindingShell_listNew := keyBindingShell_filter.Call(this.mapCallback[__ci_z__.Call(keyBindingShell_key)], Func("z_4").Bind(keyBindingShell_name))
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := keyBindingShell_listNew
  return
}
z_6(this, key) {
  this.prepare.Call(key)
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := this.formatKey.Call(key, "~")
  if (this.mapPrevented[__ci_z__.Call(key)]) {
    keyBindingShell_key := this.formatKey.Call(key)
  }
  keyBindingShell_noop.Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_7(this, key, isPrevented) {
  this.prepare.Call(key)
  this.mapPrevented[__ci_z__.Call(key)] := isPrevented
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := this.formatKey.Call(key, "~")
  if (isPrevented) {
    keyBindingShell_key := this.formatKey.Call(key)
  }
  keyBindingShell_noop.Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_8(key, this) {
  return this.fire.Call(key)
}
z_9(this, key) {
  if (this.mapCallback[__ci_z__.Call(key)]) {
    return
  }
  this.mapBound[__ci_z__.Call(key)] := Func("z_8").Bind(key, this)
  this.mapCallback[__ci_z__.Call(key)] := []
  this.mapPrevented[__ci_z__.Call(key)] := false
  return
}
z_10(this, key) {
  return this.mapPrevented[__ci_z__.Call(key)] == true
}
z_11(keyBindingShell_name, it) {
  return it[1] == keyBindingShell_name
}
z_12(this, keyMixed) {
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  keyBindingShell_list := this.mapCallback[__ci_z__.Call(keyBindingShell_key)]
  if !(keyBindingShell_list) {
    return []
  }
  if (keyBindingShell_name) {
    keyBindingShell_list := keyBindingShell_filter.Call(keyBindingShell_list, Func("z_11").Bind(keyBindingShell_name))
  }
  return keyBindingShell_list
}
z_13(this, key, prefix := "") {
  keyBindingShell_key := keyBindingShell_formatHotkey.Call(keyBindingShell_replace.Call(key, ":down", ""))
  if !(prefix) {
    return keyBindingShell_key
  }
  return "" . (prefix) . "" . (keyBindingShell_key) . ""
}
z_14(keyMixed, it) {
  if !(keyBindingShell_isFunction.Call(it[2])) {
    throw Exception("KeyBindingShell.fire: Callback is not a function for key: " . (keyMixed) . "")
  }
  it[2].Call()
  return
}
z_15(this, keyMixed) {
  keyBindingShell_forEach.Call((this.getListItem.Call(keyMixed)), Func("z_14").Bind(keyMixed))
  return
}
z_16(this, keyMixed, callback) {
  if !(keyBindingShell_isFunction.Call(callback)) {
    throw Exception("KeyBindingShell.add: Callback is not a function for key: " . (keyMixed) . "")
  }
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    keyBindingShell_name := ""
  }
  this.register.Call(keyBindingShell_key)
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)].Push([keyBindingShell_name, callback])
  return
}
z_17(exe) {
  return new WindowShell(exe)
}
z_18() {
  return Func("z_17")
}
z_19(isFunction_getType, ipt) {
  return (isFunction_getType.Call(ipt)) == "function"
}
z_20() {
  isFunction_getType := __z_module_17__
  return Func("z_19").Bind(isFunction_getType)
}
z_21(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim, key) {
  formatHotkey_listKey := formatHotkey_formatKeyFormatHotkey.Call(key)
  __array__ := formatHotkey_pickPrefixFormatHotkey.Call(formatHotkey_listKey)
  formatHotkey_prefix := __array__[1]
  formatHotkey_listKey := __array__[2]
  formatHotkey_result := ""
  for __index_for__, formatHotkey_it in formatHotkey_listKey {
    formatHotkey_result := "" . (formatHotkey_result) . " & " . (formatHotkey_it) . ""
  }
  return formatHotkey_replace.Call("" . (formatHotkey_prefix) . "" . (formatHotkey_trim.Call(formatHotkey_result, " &")) . "", ":", " ")
}
z_22(listKey) {
  if (listKey.Length() == 1) {
    return ["", listKey]
  }
  formatHotkey_prefix := ""
  formatHotkey_listNew := []
  for __index_for__, formatHotkey_key in listKey {
    if (formatHotkey_key == "alt") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "!"
      continue
    }
    if (formatHotkey_key == "ctrl") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "^"
      continue
    }
    if (formatHotkey_key == "shift") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "+"
      continue
    }
    if (formatHotkey_key == "win") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "#"
      continue
    }
    formatHotkey_listNew.Push(formatHotkey_key)
  }
  return [formatHotkey_prefix, formatHotkey_listNew]
}
z_23(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split, key) {
  formatHotkey_listKey := []
  formatHotkey_key := formatHotkey_toLowerCase.Call(key)
  formatHotkey_key := formatHotkey_replace.Call(formatHotkey_key, " ", "")
  formatHotkey_key := formatHotkey_replace.Call(formatHotkey_key, "-", "")
  formatHotkey_listSplit := formatHotkey_split.Call(formatHotkey_key, "+")
  if (formatHotkey_listSplit.Length()) {
    formatHotkey_listKey.Push(formatHotkey_listSplit*)
  }
  return formatHotkey_listKey
}
z_24() {
  formatHotkey_replace := __z_module_12__
  formatHotkey_split := __z_module_13__
  formatHotkey_toLowerCase := __z_module_15__
  formatHotkey_trim := __z_module_16__
  formatHotkey_formatKeyFormatHotkey := Func("z_23").Bind(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split)
  formatHotkey_pickPrefixFormatHotkey := Func("z_22")
  return Func("z_21").Bind(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim)
}
z_25() {
  forEach_each := __z_module_14__
  return forEach_each
}
z_26(this, callback) {
  WinWait, % this.exe
  if (callback) {
    callback.Call()
  }
  return
}
z_27(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinShow, % this.exe
  return
}
z_28(this, style) {
  if !(this.isExists.Call()) {
    return
  }
  $noop.Call(style)
  WinSet, Style, % style, % this.exe
  return
}
z_29(this, level) {
  if !(this.isExists.Call()) {
    return
  }
  $noop.Call(level)
  Process, Priority, % this.exe, % level
  return
}
z_30(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinRestore, % this.exe
  return
}
z_31(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinMinimize, % this.exe
  return
}
z_32(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinMaximize, % this.exe
  return
}
z_33(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinKill, % this.exe
  return
}
z_34(this) {
  if !(this.isExists.Call()) {
    return false
  }
  __object__ := this.getBounds.Call()
  x := __object__["x"]
  y := __object__["y"]
  width := __object__["width"]
  height := __object__["height"]
  return x == 0 && y == 0 && width == A_ScreenWidth && height == A_ScreenHeight
}
z_35(this) {
  return WinExist(this.exe)
}
z_36(this) {
  return WinActive(this.exe)
}
z_37(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinHide, % this.exe
  return
}
z_38(this) {
  __array__ := [0, 0, 0, 0]
  $x := __array__[1]
  $y := __array__[2]
  $w := __array__[3]
  $h := __array__[4]
  if !(this.isExists.Call()) {
    return {x: $x, y: $y, width: $w, height: $h}
  }
  WinGetPos, $x, $y, $w, $h, % this.exe
  return {x: $x, y: $y, width: $w, height: $h}
}
z_39(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinActivate, % this.exe
  return
}
z_40(this) {
  if !(this.isExists.Call()) {
    return
  }
  WinClose, % this.exe
  return
}
z_41(this) {
  name := "ahk_class Shell_TrayWnd"
  $noop.Call(name)
  WinActivate, % name
  return
}
z_42(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
z_43() {
  return Func("z_42")
}
z_44(ipt, omitting := " `n`r`t") {
  return Trim(ipt, omitting)
}
z_45() {
  return Func("z_44")
}
z_46(ipt) {
  toLowerCase_result := ipt
  StringLower, toLowerCase_result, ipt
  return toLowerCase_result
}
z_47() {
  return Func("z_46")
}
z_48(list, cb) {
  for each_i, each_item in list {
    each_i := each_i - 1
    cb.Call(each_item, each_i)
  }
  return
}
z_49() {
  return Func("z_48")
}
z_50(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
z_51() {
  return Func("z_50")
}
z_52(original, searchment, replacement, count := -1) {
  return StrReplace(original, searchment, replacement, count)
}
z_53() {
  return Func("z_52")
}
z_54(_args*) {
  return
}
z_55() {
  return Func("z_54")
}
z_56(list, cb) {
  filter_listNew := []
  for filter_i, filter_item in list {
    filter_i := filter_i - 1
    if !(cb.Call(filter_item, filter_i)) {
      continue
    }
    filter_listNew.Push(filter_item)
  }
  return filter_listNew
}
z_57() {
  return Func("z_56")
}
z_58(_args*) {
  return
}
z_59() {
  return Func("z_58")
}
z_60() {
  Reload
  return
}
z_61() {
  return Func("z_60")
}
z_62() {
  SoundBeep
  return
}
z_63() {
  return Func("z_62")
}
z_64(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}
