; Generated by Coffee-AHK/0.0.67
global __ci_z__ := Func("salt_1")
salt_1(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}

#KeyHistory, 0
#MaxThreads, 20
#NoEnv
#Persistent
#SingleInstance, Force
#UseHook, On

CoordMode, Mouse, Client
CoordMode, Pixel, Client
CoordMode, ToolTip, Client
SendMode, Event
SetBatchLines, 100ms
SetKeyDelay, 0, 50
SetMouseDelay, 0, 50
StringCaseSense, On


if (A_IsAdmin != true) {
  Run *RunAs "%A_ScriptFullPath%"
  ExitApp
}

global __z_module_2__ := (Func("z_115")).Call()
global __z_module_3__ := (Func("z_113")).Call()
global __z_module_4__ := (Func("z_111")).Call()
global __z_module_7__ := (Func("z_109")).Call()
global __z_module_11__ := (Func("z_107")).Call()
global __z_module_17__ := (Func("z_105")).Call()
global __z_module_18__ := (Func("z_103")).Call()
global __z_module_19__ := (Func("z_101")).Call()
global __z_module_20__ := (Func("z_99")).Call()
global __z_module_21__ := (Func("z_97")).Call()
global __z_module_26__ := (Func("z_95")).Call()
global __z_module_27__ := (Func("z_93")).Call()
global __z_module_32__ := (Func("z_91")).Call()
global __z_module_1__ := (Func("z_89")).Call()
global __z_module_6__ := (Func("z_87")).Call()
global __z_module_12__ := (Func("z_85")).Call()
global mathShell_noop := __z_module_7__.default
class MathShell {
  abs := Func("z_83").Bind(this)
  ceil := Func("z_82").Bind(this)
  floor := Func("z_81").Bind(this)
  max := Func("z_80").Bind(this)
  min := Func("z_79").Bind(this)
  round := Func("z_78").Bind(this)
}
mathShell_noop.Call(MathShell)
global __z_module_15__ := (Func("z_77")).Call()
global windowShell_endsWith := __z_module_26__.default
global windowShell_noop := __z_module_7__.default
class WindowShell {
  __New(exe, title := "") {
    this.exe := ""
    if (windowShell_endsWith.Call(exe, ".exe")) {
      this.exe := exe
    } else {
      this.exe := "" . (exe) . ".exe"
    }
    this.title := ""
    if (title) {
      this.title := title
    }
  }
  getWindowIdString := Func("z_75").Bind(this)
  blur := Func("z_74").Bind(this)
  close := Func("z_73").Bind(this)
  focus := Func("z_72").Bind(this)
  getBounds := Func("z_71").Bind(this)
  getProcessId := Func("z_70").Bind(this)
  getTitle := Func("z_69").Bind(this)
  getWindowId := Func("z_68").Bind(this)
  hide := Func("z_67").Bind(this)
  isActive := Func("z_66").Bind(this)
  isExists := Func("z_65").Bind(this)
  isFullScreen := Func("z_64").Bind(this)
  kill := Func("z_63").Bind(this)
  maximize := Func("z_62").Bind(this)
  minimize := Func("z_61").Bind(this)
  restore := Func("z_60").Bind(this)
  setPriority := Func("z_59").Bind(this)
  setStyle := Func("z_58").Bind(this)
  show := Func("z_57").Bind(this)
  wait := Func("z_56").Bind(this)
}
windowShell_noop.Call(WindowShell)
global __z_module_22__ := (Func("z_55")).Call()
global __z_module_23__ := (Func("z_53")).Call()
global __z_module_24__ := (Func("z_51")).Call()
global __z_module_28__ := (Func("z_49")).Call()
global __z_module_29__ := (Func("z_48")).Call()
global __z_module_30__ := (Func("z_44")).Call()
global __z_module_31__ := (Func("z_42")).Call()
global __z_module_5__ := (Func("z_40")).Call()
global __z_module_13__ := (Func("z_39")).Call()
global keyBindingShell_filter := __z_module_27__.default
global keyBindingShell_forEach := __z_module_28__.default
global keyBindingShell_formatHotkey := __z_module_29__.default
global keyBindingShell_isFunction := __z_module_30__.default
global keyBindingShell_noop := __z_module_7__.default
global keyBindingShell_replace := __z_module_17__.default
global keyBindingShell_split := __z_module_18__.default
class KeyBindingShell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
    this.mapPrevented := {}
  }
  add := Func("z_37").Bind(this)
  fire := Func("z_36").Bind(this)
  formatKey := Func("z_34").Bind(this)
  getListItem := Func("z_33").Bind(this)
  isPrevented := Func("z_31").Bind(this)
  prepare := Func("z_30").Bind(this)
  prevent := Func("z_28").Bind(this)
  register := Func("z_27").Bind(this)
  remove := Func("z_26").Bind(this)
}
keyBindingShell_noop.Call(KeyBindingShell)
global __z_module_25__ := (Func("z_24")).Call()
global __z_module_14__ := (Func("z_22")).Call()
global __z_module_16__ := (Func("z_21")).Call()
global __z_module_8__ := (Func("z_19")).Call()
global __z_module_9__ := (Func("z_18")).Call()
global __z_module_10__ := (Func("z_17")).Call()
global $alert := __z_module_1__.default
global $beep := __z_module_2__.default
global $exit := __z_module_3__.default
global $getPosition := __z_module_4__.default
global $math := __z_module_5__.default
global $move := __z_module_6__.default
global $noop := __z_module_7__.default
global $off := __z_module_8__.default
global $on := __z_module_9__.default
global $press := __z_module_10__.default
global $reload := __z_module_11__.default
global $sleep := __z_module_12__.default
global $window := __z_module_13__.default
global ps := $window.Call("Photoshop")
global qst := $window.Call("QQScreenShot")
global qsr := $window.Call("QQScreenShot", "屏幕识图")
global checkProcessExists := Func("z_13")
global clickOCRButton := Func("z_12")
global clickCopyButton := Func("z_9")
global addPhotoshopLayer := Func("z_8")
global main := Func("z_7")
$on.Call("alt + 1", Func("z_3"))
$on.Call("esc", Func("z_2"))
$on.Call("ctrl + q", Func("z_1"))
z_1() {
  $beep.Call()
  $exit.Call()
}
z_2() {
  $beep.Call()
  $reload.Call()
}
z_3() {
  return main.Call()
}
z_4(d) {
  return addPhotoshopLayer.Call(d.points)
}
z_5(d) {
  return clickCopyButton.Call(Func("z_4").Bind(d))
}
z_6(points) {
  d := {points: points}
  qsr.wait.Call(Func("z_5").Bind(d))
}
z_7() {
  if !(ps.isExists.Call()) {
    $alert.Call("请先打开 Photoshop")
    return
  }
  if !(checkProcessExists.Call("QQScreenShot.exe")) {
    $alert.Call("请先打开截图工具")
    return
  }
  ps.focus.Call()
  $sleep.Call(100)
  $press.Call("ctrl + alt + f9")
  $sleep.Call(100)
  clickOCRButton.Call(Func("z_6"))
}
z_8(points) {
  ps.focus.Call()
  $sleep.Call(100)
  $move.Call(points[1])
  $sleep.Call(100)
  $press.Call("space")
  SetCapsLockState, On
  $press.Call("t")
  $sleep.Call(100)
  $press.Call("l-button:down")
  $sleep.Call(100)
  $move.Call(points[2])
  $sleep.Call(100)
  $press.Call("l-button:up")
  $sleep.Call(100)
  $press.Call("ctrl + v")
  $sleep.Call(100)
  $press.Call("esc")
  $sleep.Call(100)
  $press.Call("v")
  SetCapsLockState, Off
  return
}
z_9(callback) {
  __object__ := qst.getBounds.Call()
  x := __object__["x"]
  y := __object__["y"]
  width := __object__["width"]
  height := __object__["height"]
  $move.Call([x + width - 85, y + height - 35])
  $sleep.Call(100)
  $press.Call("l-button")
  $press.Call("l-button")
  $sleep.Call(100)
  qsr.close.Call()
  callback.Call()
}
z_10(p, callback) {
  $off.Call("l-button:down")
  $off.Call("l-button:up")
  p.b := $getPosition.Call()
  if (p.a[1] == p.b[1] || p.a[2] == p.b[2]) {
    $press.Call("esc")
    return
  }
  a := [$math.min.Call(p.a[1], p.b[1]), $math.min.Call(p.a[2], p.b[2])]
  b := [$math.max.Call(p.a[1], p.b[1]), $math.max.Call(p.a[2], p.b[2])]
  if (b[1] >= 482) {
    $move.Call([b[1] - 190, b[2] + 20])
  } else {
    $move.Call([290, b[2] + 20])
  }
  $sleep.Call(100)
  $press.Call("l-button")
  $sleep.Call(100)
  callback.Call([a, b])
}
z_11(p) {
  return p.a := $getPosition.Call()
}
z_12(callback) {
  p := {a: [0, 0], b: [0, 0]}
  $on.Call("l-button:down", Func("z_11").Bind(p))
  $on.Call("l-button:up", Func("z_10").Bind(p, callback))
}
z_13(exe) {
  Process, Exist, % exe
  return, % ErrorLevel
  $noop.Call(exe)
  return false
}
z_14(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim, listInput*) {
  if !(press_validateInputPress.Call(listInput)) {
    return
  }
  press_listKey := press_formatInputPress.Call(listInput)
  press_listResult := []
  press_len := press_listKey.Length()
  for press_i, press_key in press_listKey {
    press_i := press_i - 1
    if (press_i == press_len - 1) {
      press_listResult[__ci_z__.Call(press_i)] := press_split.Call(press_key, ":")
      continue
    }
    if (press_includes.Call(press_key, ":")) {
      press_listResult[__ci_z__.Call(press_i)] := press_split.Call(press_key, ":")
      press_listResult[__ci_z__.Call((press_len - 1) * 2 - press_i)] := press_split.Call(press_key, ":")
    } else {
      press_listResult[__ci_z__.Call(press_i)] := [press_key, "down"]
      press_listResult[__ci_z__.Call((press_len - 1) * 2 - press_i)] := [press_key, "up"]
    }
  }
  for press_i, press_it in press_listResult {
    press_i := press_i - 1
    if (press_it[1] == "win") {
      press_it[1] := "lwin"
    }
    press_listResult[__ci_z__.Call(press_i)] := press_trim.Call("" . (press_it[1]) . " " . (press_it[2]) . "")
  }
  press_result := ""
  for __index_for__, press_it in press_listResult {
    press_result := "" . (press_result) . "{" . (press_it) . "}"
  }
  Send, % press_result
  return
}
z_15(press_includes, press_replace, press_click, listInput) {
  if !(listInput.Length()) {
    return false
  }
  press_key := listInput[1]
  if (press_includes.Call(press_key, "-button")) {
    press_key := press_replace.Call(press_key, "l-button", "left")
    press_key := press_replace.Call(press_key, "m-button", "middle")
    press_key := press_replace.Call(press_key, "r-button", "right")
    press_click.Call(press_key)
    return false
  }
  return true
}
z_16(press_toLowerCase, press_replace, press_split, listInput) {
  press_listKey := []
  for __index_for__, press_input in listInput {
    press_ipt := press_toLowerCase.Call(press_input)
    press_ipt := press_replace.Call(press_ipt, " ", "")
    press_ipt := press_replace.Call(press_ipt, "-", "")
    press_listKey.Push((press_split.Call(press_ipt, "+"))*)
  }
  return press_listKey
}
z_17() {
  press_click := __z_module_15__.default
  press_includes := __z_module_16__.default
  press_replace := __z_module_17__.default
  press_split := __z_module_18__.default
  press_toLowerCase := __z_module_19__.default
  press_trim := __z_module_20__.default
  press_formatInputPress := Func("z_16").Bind(press_toLowerCase, press_replace, press_split)
  press_validateInputPress := Func("z_15").Bind(press_includes, press_replace, press_click)
  return {default: Func("z_14").Bind(press_validateInputPress, press_formatInputPress, press_split, press_includes, press_trim)}
}
z_18() {
  on_keyBinding := __z_module_14__.default
  return {default: on_keyBinding.add}
}
z_19() {
  off_keyBinding := __z_module_14__.default
  return {default: off_keyBinding.remove}
}
z_20(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray, ipt, needle) {
  includes_type := includes_getType.Call(ipt)
  if ((includes_isString.Call(ipt)) || includes_isNumber.Call(ipt)) {
    if !(includes_isString.Call(needle)) {
      return false
    }
    return (InStr((includes_toString.Call(ipt)), needle)) > 0
  }
  if (includes_isArray.Call(ipt)) {
    for __index_for__, includes_it in ipt {
      if (includes_it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("includes: invalid type '" . (includes_type) . "'")
}
z_21() {
  includes_getType := __z_module_21__.default
  includes_isArray := __z_module_22__.default
  includes_isNumber := __z_module_23__.default
  includes_isString := __z_module_24__.default
  includes_toString := __z_module_25__.default
  return {default: Func("z_20").Bind(includes_getType, includes_isString, includes_isNumber, includes_toString, includes_isArray)}
}
z_22() {
  return {default: new KeyBindingShell()}
}
z_23(toString_isArray, toString_trim, toString_isObject, ipt) {
  if (toString_isArray.Call(ipt)) {
    toString_result := ""
    for __index_for__, toString_it in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_it) . ""
    }
    return "[" . (toString_trim.Call(toString_result, " ,")) . "]"
  }
  if (toString_isObject.Call(ipt)) {
    toString_result := ""
    for toString_key, toString_value in ipt {
      toString_result := "" . (toString_result) . ", " . (toString_key) . ": " . (toString_value) . ""
    }
    return "{" . (toString_trim.Call(toString_result, " ,")) . "}"
  }
  return ipt
}
z_24() {
  toString_isArray := __z_module_22__.default
  toString_isObject := __z_module_31__.default
  toString_trim := __z_module_20__.default
  return {default: Func("z_23").Bind(toString_isArray, toString_trim, toString_isObject)}
}
z_25(keyBindingShell_name, it) {
  return it[1] != keyBindingShell_name
}
z_26(this, keyMixed) {
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := []
    return
  }
  keyBindingShell_listNew := keyBindingShell_filter.Call(this.mapCallback[__ci_z__.Call(keyBindingShell_key)], Func("z_25").Bind(keyBindingShell_name))
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)] := keyBindingShell_listNew
  return
}
z_27(this, key) {
  this.prepare.Call(key)
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := this.formatKey.Call(key, "~")
  if (this.mapPrevented[__ci_z__.Call(key)]) {
    keyBindingShell_key := this.formatKey.Call(key)
  }
  keyBindingShell_noop.Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_28(this, key, isPrevented) {
  this.prepare.Call(key)
  this.mapPrevented[__ci_z__.Call(key)] := isPrevented
  keyBindingShell_callback := this.mapBound[__ci_z__.Call(key)]
  keyBindingShell_key := this.formatKey.Call(key, "~")
  if (isPrevented) {
    keyBindingShell_key := this.formatKey.Call(key)
  }
  keyBindingShell_noop.Call(keyBindingShell_callback, keyBindingShell_key)
  Hotkey, % keyBindingShell_key, % keyBindingShell_callback, On
  return
}
z_29(key, this) {
  return this.fire.Call(key)
}
z_30(this, key) {
  if (this.mapCallback[__ci_z__.Call(key)]) {
    return
  }
  this.mapBound[__ci_z__.Call(key)] := Func("z_29").Bind(key, this)
  this.mapCallback[__ci_z__.Call(key)] := []
  this.mapPrevented[__ci_z__.Call(key)] := false
  return
}
z_31(this, key) {
  return this.mapPrevented[__ci_z__.Call(key)] == true
}
z_32(keyBindingShell_name, it) {
  return it[1] == keyBindingShell_name
}
z_33(this, keyMixed) {
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  keyBindingShell_list := this.mapCallback[__ci_z__.Call(keyBindingShell_key)]
  if !(keyBindingShell_list) {
    return []
  }
  if (keyBindingShell_name) {
    keyBindingShell_list := keyBindingShell_filter.Call(keyBindingShell_list, Func("z_32").Bind(keyBindingShell_name))
  }
  return keyBindingShell_list
}
z_34(this, key, prefix := "") {
  keyBindingShell_key := keyBindingShell_formatHotkey.Call(keyBindingShell_replace.Call(key, ":down", ""))
  if !(prefix) {
    return keyBindingShell_key
  }
  return "" . (prefix) . "" . (keyBindingShell_key) . ""
}
z_35(keyMixed, it) {
  if !(keyBindingShell_isFunction.Call(it[2])) {
    throw Exception("KeyBindingShell.fire: Callback is not a function for key: " . (keyMixed) . "")
  }
  it[2].Call()
  return
}
z_36(this, keyMixed) {
  keyBindingShell_forEach.Call((this.getListItem.Call(keyMixed)), Func("z_35").Bind(keyMixed))
  return
}
z_37(this, keyMixed, callback) {
  if !(keyBindingShell_isFunction.Call(callback)) {
    throw Exception("KeyBindingShell.add: Callback is not a function for key: " . (keyMixed) . "")
  }
  __array__ := keyBindingShell_split.Call((keyBindingShell_replace.Call(keyMixed, ":down", "")), ".")
  keyBindingShell_key := __array__[1]
  keyBindingShell_name := __array__[2]
  if !(keyBindingShell_name) {
    keyBindingShell_name := ""
  }
  this.register.Call(keyBindingShell_key)
  this.mapCallback[__ci_z__.Call(keyBindingShell_key)].Push([keyBindingShell_name, callback])
  return
}
z_38(exe, title := "") {
  return new WindowShell(exe, title)
}
z_39() {
  return {default: Func("z_38")}
}
z_40() {
  return {default: new MathShell()}
}
z_41(isObject_getType, ipt) {
  isObject_type := isObject_getType.Call(ipt)
  if !(isObject_type == "object") {
    return false
  }
  return true
}
z_42() {
  isObject_getType := __z_module_21__.default
  return {default: Func("z_41").Bind(isObject_getType)}
}
z_43(isFunction_getType, ipt) {
  return (isFunction_getType.Call(ipt)) == "function"
}
z_44() {
  isFunction_getType := __z_module_21__.default
  return {default: Func("z_43").Bind(isFunction_getType)}
}
z_45(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim, key) {
  formatHotkey_listKey := formatHotkey_formatKeyFormatHotkey.Call(key)
  __array__ := formatHotkey_pickPrefixFormatHotkey.Call(formatHotkey_listKey)
  formatHotkey_prefix := __array__[1]
  formatHotkey_listKey := __array__[2]
  formatHotkey_result := ""
  for __index_for__, formatHotkey_it in formatHotkey_listKey {
    formatHotkey_result := "" . (formatHotkey_result) . " & " . (formatHotkey_it) . ""
  }
  return formatHotkey_replace.Call("" . (formatHotkey_prefix) . "" . (formatHotkey_trim.Call(formatHotkey_result, " &")) . "", ":", " ")
}
z_46(listKey) {
  if (listKey.Length() == 1) {
    return ["", listKey]
  }
  formatHotkey_prefix := ""
  formatHotkey_listNew := []
  for __index_for__, formatHotkey_key in listKey {
    if (formatHotkey_key == "alt") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "!"
      continue
    }
    if (formatHotkey_key == "ctrl") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "^"
      continue
    }
    if (formatHotkey_key == "shift") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "+"
      continue
    }
    if (formatHotkey_key == "win") {
      formatHotkey_prefix := "" . (formatHotkey_prefix) . "#"
      continue
    }
    formatHotkey_listNew.Push(formatHotkey_key)
  }
  return [formatHotkey_prefix, formatHotkey_listNew]
}
z_47(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split, key) {
  formatHotkey_listKey := []
  formatHotkey_key := formatHotkey_toLowerCase.Call(key)
  formatHotkey_key := formatHotkey_replace.Call(formatHotkey_key, " ", "")
  formatHotkey_key := formatHotkey_replace.Call(formatHotkey_key, "-", "")
  formatHotkey_listSplit := formatHotkey_split.Call(formatHotkey_key, "+")
  if (formatHotkey_listSplit.Length()) {
    formatHotkey_listKey.Push(formatHotkey_listSplit*)
  }
  return formatHotkey_listKey
}
z_48() {
  formatHotkey_replace := __z_module_17__.default
  formatHotkey_split := __z_module_18__.default
  formatHotkey_toLowerCase := __z_module_19__.default
  formatHotkey_trim := __z_module_20__.default
  formatHotkey_formatKeyFormatHotkey := Func("z_47").Bind(formatHotkey_toLowerCase, formatHotkey_replace, formatHotkey_split)
  formatHotkey_pickPrefixFormatHotkey := Func("z_46")
  return {default: Func("z_45").Bind(formatHotkey_formatKeyFormatHotkey, formatHotkey_pickPrefixFormatHotkey, formatHotkey_replace, formatHotkey_trim)}
}
z_49() {
  forEach_each := __z_module_32__.default
  return {default: forEach_each}
}
z_50(isString_getType, ipt) {
  isString_type := isString_getType.Call(ipt)
  if !(isString_type == "string") {
    return false
  }
  return true
}
z_51() {
  isString_getType := __z_module_21__.default
  return {default: Func("z_50").Bind(isString_getType)}
}
z_52(isNumber_getType, ipt) {
  isNumber_type := isNumber_getType.Call(ipt)
  if !(isNumber_type == "number") {
    return false
  }
  return true
}
z_53() {
  isNumber_getType := __z_module_21__.default
  return {default: Func("z_52").Bind(isNumber_getType)}
}
z_54(isArray_getType, ipt) {
  isArray_type := isArray_getType.Call(ipt)
  if !(isArray_type == "array") {
    return false
  }
  return true
}
z_55() {
  isArray_getType := __z_module_21__.default
  return {default: Func("z_54").Bind(isArray_getType)}
}
z_56(this, callback) {
  windowShell_selector := ""
  windowShell_noop.Call(windowShell_selector)
  if (this.title) {
    windowShell_selector := "" . (this.title) . " ahk_exe " . (this.exe) . ""
  } else {
    windowShell_selector := "ahk_exe " . (this.exe) . ""
  }
  WinWait, % windowShell_selector
  if (callback) {
    callback.Call()
  }
  return
}
z_57(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinShow, % windowShell_idString
  return
}
z_58(this, style) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  windowShell_noop.Call(style)
  WinSet, Style, % style, % windowShell_idString
  return
}
z_59(this, level) {
  windowShell_id := this.getWindowId.Call()
  if !(windowShell_id) {
    return
  }
  windowShell_noop.Call(level)
  Process, Priority, % this.exe, % level
  return
}
z_60(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinRestore, % windowShell_idString
  return
}
z_61(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinMinimize, % windowShell_idString
  return
}
z_62(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinMaximize, % windowShell_idString
  return
}
z_63(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinKill, % windowShell_idString
  return
}
z_64(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return false
  }
  __object__ := this.getBounds.Call()
  x := __object__["x"]
  y := __object__["y"]
  width := __object__["width"]
  height := __object__["height"]
  return x == 0 && y == 0 && width == A_ScreenWidth && height == A_ScreenHeight
}
z_65(this) {
  windowShell_id := this.getWindowId.Call()
  return windowShell_id > 0
}
z_66(this) {
  windowShell_id := this.getWindowId.Call()
  if !(windowShell_id) {
    return false
  }
  windowShell_activeId := WinActive("ahk_id " . (windowShell_id) . "")
  return windowShell_activeId == windowShell_id
}
z_67(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinHide, % windowShell_idString
  return
}
z_68(this) {
  windowShell_id := 0
  windowShell_selector := ""
  windowShell_noop.Call(windowShell_selector)
  if (this.title) {
    windowShell_selector := "" . (this.title) . " ahk_exe " . (this.exe) . ""
  } else {
    windowShell_selector := "ahk_exe " . (this.exe) . ""
  }
  WinGet, windowShell_id, ID, % windowShell_selector
  return windowShell_id
}
z_69(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return ""
  }
  if (this.title) {
    return this.title
  }
  windowShell_title := ""
  WinGetTitle, windowShell_title, % windowShell_idString
  return windowShell_title
}
z_70(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return 0
  }
  windowShell_pid := 0
  WinGet, windowShell_pid, PID, % windowShell_idString
  return windowShell_pid
}
z_71(this) {
  __array__ := [0, 0, 0, 0]
  windowShell_x := __array__[1]
  windowShell_y := __array__[2]
  windowShell_w := __array__[3]
  windowShell_h := __array__[4]
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return {x: windowShell_x, y: windowShell_y, width: windowShell_w, height: windowShell_h}
  }
  WinGetPos, windowShell_x, windowShell_y, windowShell_w, windowShell_h, % windowShell_idString
  return {x: windowShell_x, y: windowShell_y, width: windowShell_w, height: windowShell_h}
}
z_72(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinActivate, % windowShell_idString
  return
}
z_73(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  WinClose, % windowShell_idString
  return
}
z_74(this) {
  windowShell_idString := this.getWindowIdString.Call()
  if !(windowShell_idString) {
    return
  }
  name := "ahk_class Shell_TrayWnd"
  windowShell_noop.Call(name)
  WinActivate, %name%
  return
}
z_75(this) {
  windowShell_id := this.getWindowId.Call()
  if !(windowShell_id) {
    return ""
  }
  return "ahk_id " . (windowShell_id) . ""
}
z_76(click_replace, key := "left") {
  key := click_replace.Call(key, "-", "")
  key := click_replace.Call(key, ":", " ")
  Click, % key
  return
}
z_77() {
  click_replace := __z_module_17__.default
  return {default: Func("z_76").Bind(click_replace)}
}
z_78(this, n) {
  return Round(n)
}
z_79(this, numbers*) {
  return Min(numbers*)
}
z_80(this, numbers*) {
  return Max(numbers*)
}
z_81(this, n) {
  return Floor(n)
}
z_82(this, n) {
  return Ceil(n)
}
z_83(this, n) {
  return Abs(n)
}
z_84(sleep_noop, time := 1000) {
  sleep_noop.Call(time)
  Sleep, % time
  return
}
z_85() {
  sleep_noop := __z_module_7__.default
  return {default: Func("z_84").Bind(sleep_noop)}
}
z_86(move_noop, p := "", speed := 0) {
  if !(p) {
    return
  }
  move_noop.Call(speed)
  MouseMove, p[1], p[2], speed
  return
}
z_87() {
  move_noop := __z_module_7__.default
  return {default: Func("z_86").Bind(move_noop)}
}
z_88(alert_noop, message) {
  alert_noop.Call(message)
  MsgBox, % message
  return
}
z_89() {
  alert_noop := __z_module_7__.default
  return {default: Func("z_88").Bind(alert_noop)}
}
z_90(list, cb) {
  for each_i, each_item in list {
    each_i := each_i - 1
    cb.Call(each_item, each_i)
  }
  return
}
z_91() {
  return {default: Func("z_90")}
}
z_92(list, cb) {
  filter_listNew := []
  for filter_i, filter_item in list {
    filter_i := filter_i - 1
    if !(cb.Call(filter_item, filter_i)) {
      continue
    }
    filter_listNew.Push(filter_item)
  }
  return filter_listNew
}
z_93() {
  return {default: Func("z_92")}
}
z_94(haystack, needle) {
  return SubStr(haystack, StrLen(haystack) - StrLen(needle) + 1) == needle
}
z_95() {
  return {default: Func("z_94")}
}
z_96(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
z_97() {
  return {default: Func("z_96")}
}
z_98(ipt, omitting := " `n`r`t") {
  return Trim(ipt, omitting)
}
z_99() {
  return {default: Func("z_98")}
}
z_100(ipt) {
  toLowerCase_result := ipt
  StringLower, toLowerCase_result, ipt
  return toLowerCase_result
}
z_101() {
  return {default: Func("z_100")}
}
z_102(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
z_103() {
  return {default: Func("z_102")}
}
z_104(original, searchment, replacement, count := -1) {
  return StrReplace(original, searchment, replacement, count)
}
z_105() {
  return {default: Func("z_104")}
}
z_106() {
  Reload
  return
}
z_107() {
  return {default: Func("z_106")}
}
z_108(_args*) {
  return
}
z_109() {
  return {default: Func("z_108")}
}
z_110() {
  getPosition_x := 0
  getPosition_y := 0
  MouseGetPos, getPosition_x, getPosition_y
  return [getPosition_x, getPosition_y]
}
z_111() {
  return {default: Func("z_110")}
}
z_112() {
  ExitApp
  return
}
z_113() {
  return {default: Func("z_112")}
}
z_114() {
  SoundBeep
  return
}
z_115() {
  return {default: Func("z_114")}
}