# @ts-check

import $abs from './module/abs'
import $add from './module/add'
import $admin from './module/admin'
import $alert from './module/alert'
import $beep from './module/beep'
import $bind from './module/bind'
import $blockInput from './module/blockInput'
import $ceil from './module/ceil'
import $chunk from './module/chunk'
import $clearInterval from './module/clearInterval'
import $clearTimeout from './module/clearTimeout'
import $click from './module/click'
import $clone from './module/clone'
import $compact from './module/compact'
import $concat from './module/concat'
import $confirm from './module/confirm'
import $debounce from './module/debounce'
import $defer from './module/defer'
import $delay from './module/delay'
import $drop from './module/drop'
import $each from './module/each'
import $echo from './module/echo'
import $emitter from './module/emitter'
import $eq from './module/eq'
import $exec from './module/exec'
import $exit from './module/exit'
import $file from './module/file'
import $filter from './module/filter'
import $findColor from './module/findColor'
import $findImage from './module/findImage'
import $first from './module/first'
import $floor from './module/floor'
import $forEach from './module/forEach'
import $formatHotkey from './module/formatHotkey'
import $get from './module/get'
import $getColor from './module/getColor'
import $getPosition from './module/getPosition'
import $getState from './module/getState'
import $getType from './module/getType'
import $gt from './module/gt'
import $gte from './module/gte'
import $head from './module/head'
import $includes from './module/includes'
import $isArray from './module/isArray'
import $isFunction from './module/isFunction'
import $isNumber from './module/isNumber'
import $isObject from './module/isObject'
import $isString from './module/isString'
import $join from './module/join'
import $keys from './module/keys'
import $last from './module/last'
import $length from './module/length'
import $lt from './module/lt'
import $lte from './module/lte'
import $map from './module/map'
import $mixin from './module/mixin'
import $mod from './module/mod'
import $move from './module/move'
import $noop from './module/noop'
import $now from './module/now'
import $nth from './module/nth'
import $off from './module/off'
import $on from './module/on'
import $once from './module/once'
import $open from './module/open'
import $play from './module/play'
import $pop from './module/pop'
import $press from './module/press'
import $push from './module/push'
import $random from './module/random'
import $range from './module/range'
import $reload from './module/reload'
import $replace from './module/replace'
import $reverse from './module/reverse'
import $round from './module/round'
import $setFixed from './module/setFixed'
import $setInterval from './module/setInterval'
import $setTimeout from './module/setTimeout'
import $shift from './module/shift'
import $shuffle from './module/shuffle'
import $sleep from './module/sleep'
import $slice from './module/slice'
import $sort from './module/sort'
import $split from './module/split'
import $startsWith from './module/startsWith'
import $subString from './module/subString'
import $sum from './module/sum'
import $suspend from './module/suspend'
import $tail from './module/tail'
import $take from './module/take'
import $throttle from './module/throttle'
import $tip from './module/tip'
import $toLower from './module/toLower'
import $toLowerCase from './module/toLowerCase'
import $toNumber from './module/toNumber'
import $toString from './module/toString'
import $toUpper from './module/toUpper'
import $toUpperCase from './module/toUpperCase'
import $trigger from './module/trigger'
import $trim from './module/trim'
import $trimEnd from './module/trimEnd'
import $trimStart from './module/trimStart'
import $uniq from './module/uniq'
import $unshift from './module/unshift'
import $values from './module/values'
import $version from './module/version'
import $window from './module/window'
import './module/emitterShell'
import './module/fileShell'
import './module/windowShell'

$ = {}

$mixin $, VERSION: $version
$mixin $, abs: $abs
$mixin $, add: $add
$mixin $, admin: $admin
$mixin $, alert: $alert
$mixin $, beep: $beep
$mixin $, bind: $bind
$mixin $, blockInput: $blockInput
$mixin $, ceil: $ceil
$mixin $, chunk: $chunk
$mixin $, clearInterval: $clearInterval
$mixin $, clearTimeout: $clearTimeout
$mixin $, click: $click
$mixin $, clone: $clone
$mixin $, compact: $compact
$mixin $, concat: $concat
$mixin $, confirm: $confirm
$mixin $, debounce: $debounce
$mixin $, defer: $defer
$mixin $, delay: $delay
$mixin $, drop: $drop
$mixin $, each: $each
$mixin $, echo: $echo
$mixin $, emitter: $emitter
$mixin $, eq: $eq
$mixin $, exec: $exec
$mixin $, exit: $exit
$mixin $, file: $file
$mixin $, filter: $filter
$mixin $, findColor: $findColor
$mixin $, findImage: $findImage
$mixin $, first: $first
$mixin $, floor: $floor
$mixin $, forEach: $forEach
$mixin $, formatHotkey: $formatHotkey
$mixin $, get: $get
$mixin $, getColor: $getColor
$mixin $, getPosition: $getPosition
$mixin $, getState: $getState
$mixin $, getType: $getType
$mixin $, gt: $gt
$mixin $, gte: $gte
$mixin $, head: $head
$mixin $, includes: $includes
$mixin $, isArray: $isArray
$mixin $, isFunction: $isFunction
$mixin $, isNumber: $isNumber
$mixin $, isObject: $isObject
$mixin $, isString: $isString
$mixin $, join: $join
$mixin $, keys: $keys
$mixin $, last: $last
$mixin $, length: $length
$mixin $, lt: $lt
$mixin $, lte: $lte
$mixin $, map: $map
$mixin $, mixin: $mixin
$mixin $, mod: $mod
$mixin $, move: $move
$mixin $, noop: $noop
$mixin $, now: $now
$mixin $, nth: $nth
$mixin $, off: $off
$mixin $, on: $on
$mixin $, once: $once
$mixin $, open: $open
$mixin $, play: $play
$mixin $, pop: $pop
$mixin $, press: $press
$mixin $, push: $push
$mixin $, random: $random
$mixin $, range: $range
$mixin $, reload: $reload
$mixin $, replace: $replace
$mixin $, reverse: $reverse
$mixin $, round: $round
$mixin $, setFixed: $setFixed
$mixin $, setInterval: $setInterval
$mixin $, setTimeout: $setTimeout
$mixin $, shift: $shift
$mixin $, shuffle: $shuffle
$mixin $, sleep: $sleep
$mixin $, slice: $slice
$mixin $, sort: $sort
$mixin $, split: $split
$mixin $, startsWith: $startsWith
$mixin $, subString: $subString
$mixin $, sum: $sum
$mixin $, suspend: $suspend
$mixin $, tail: $tail
$mixin $, take: $take
$mixin $, throttle: $throttle
$mixin $, tip: $tip
$mixin $, toLower: $toLower
$mixin $, toLowerCase: $toLowerCase
$mixin $, toNumber: $toNumber
$mixin $, toString: $toString
$mixin $, toUpper: $toUpper
$mixin $, toUpperCase: $toUpperCase
$mixin $, trigger: $trigger
$mixin $, trim: $trim
$mixin $, trimEnd: $trimEnd
$mixin $, trimStart: $trimStart
$mixin $, uniq: $uniq
$mixin $, unshift: $unshift
$mixin $, values: $values
$mixin $, window: $window
