; Generated by Coffee-AHK/0.0.52
global __rf_shell__ := Func("shell_270")
global __ci_shell__ := Func("shell_269")
global __shell_module_1__ := (Func("shell_268")).Call()
global __shell_module_3__ := (Func("shell_266")).Call()
global __shell_module_5__ := (Func("shell_264")).Call()
global __shell_module_7__ := (Func("shell_262")).Call()
global __shell_module_8__ := (Func("shell_260")).Call()
global __shell_module_14__ := (Func("shell_258")).Call()
global __shell_module_18__ := (Func("shell_256")).Call()
global __shell_module_20__ := (Func("shell_254")).Call()
global __shell_module_25__ := (Func("shell_252")).Call()
global __shell_module_30__ := (Func("shell_250")).Call()
global __shell_module_36__ := (Func("shell_248")).Call()
global __shell_module_37__ := (Func("shell_246")).Call()
global __shell_module_38__ := (Func("shell_244")).Call()
global __shell_module_40__ := (Func("shell_242")).Call()
global __shell_module_51__ := (Func("shell_240")).Call()
global __shell_module_52__ := (Func("shell_238")).Call()
global __shell_module_55__ := (Func("shell_236")).Call()
global __shell_module_56__ := (Func("shell_234")).Call()
global __shell_module_58__ := (Func("shell_232")).Call()
global __shell_module_60__ := (Func("shell_230")).Call()
global __shell_module_61__ := (Func("shell_228")).Call()
global __shell_module_65__ := (Func("shell_226")).Call()
global __shell_module_74__ := (Func("shell_223")).Call()
global __shell_module_75__ := (Func("shell_221")).Call()
global __shell_module_77__ := (Func("shell_219")).Call()
global __shell_module_82__ := (Func("shell_217")).Call()
global __shell_module_85__ := (Func("shell_215")).Call()
global __shell_module_86__ := (Func("shell_213")).Call()
global __shell_module_88__ := (Func("shell_211")).Call()
global __shell_module_89__ := (Func("shell_209")).Call()
global __shell_module_95__ := (Func("shell_207")).Call()
global __shell_module_96__ := (Func("shell_205")).Call()
global __shell_module_98__ := (Func("shell_203")).Call()
global __shell_module_100__ := (Func("shell_201")).Call()
global __shell_module_102__ := (Func("shell_199")).Call()
global __shell_module_103__ := (Func("shell_197")).Call()
global __shell_module_104__ := (Func("shell_195")).Call()
global __shell_module_2__ := (Func("shell_193")).Call()
global __shell_module_9__ := (Func("shell_191")).Call()
global __shell_module_13__ := (Func("shell_189")).Call()
global __shell_module_28__ := (Func("shell_187")).Call()
global __shell_module_29__ := (Func("shell_185")).Call()
global __shell_module_31__ := (Func("shell_183")).Call()
global __shell_module_34__ := (Func("shell_182")).Call()
global __shell_module_39__ := (Func("shell_180")).Call()
global __shell_module_42__ := (Func("shell_179")).Call()
global __shell_module_43__ := (Func("shell_177")).Call()
global __shell_module_44__ := (Func("shell_175")).Call()
global __shell_module_45__ := (Func("shell_173")).Call()
global __shell_module_46__ := (Func("shell_171")).Call()
global __shell_module_59__ := (Func("shell_169")).Call()
global __shell_module_66__ := (Func("shell_167")).Call()
global __shell_module_67__ := (Func("shell_165")).Call()
global __shell_module_72__ := (Func("shell_163")).Call()
global __shell_module_87__ := (Func("shell_161")).Call()
global __shell_module_94__ := (Func("shell_159")).Call()
global __shell_module_99__ := (Func("shell_158")).Call()
global __replace__ := __shell_module_75__
global __noop__ := __shell_module_60__
class FileShell {
  __New(source) {
    this.source := source
  }
  append := Func("shell_157").Bind(this)
  isExists := Func("shell_156").Bind(this)
  read := Func("shell_155").Bind(this)
  remove := Func("shell_154").Bind(this)
  write := Func("shell_153").Bind(this)
}
__rf_shell__.Call(__noop__, "#rf/shell/1").Call(FileShell)
__noop__ := __shell_module_60__
class MathShell {
  abs := Func("shell_152").Bind(this)
  ceil := Func("shell_151").Bind(this)
  floor := Func("shell_150").Bind(this)
  max := Func("shell_149").Bind(this)
  min := Func("shell_148").Bind(this)
  round := Func("shell_147").Bind(this)
}
__rf_shell__.Call(__noop__, "#rf/shell/2").Call(MathShell)
__noop__ := __shell_module_60__
class WindowShell {
  __New(exe) {
    this.exe := "ahk_exe " . (exe) . ""
  }
  blur := Func("shell_146").Bind(this)
  close := Func("shell_145").Bind(this)
  focus := Func("shell_144").Bind(this)
  getBounds := Func("shell_143").Bind(this)
  hide := Func("shell_142").Bind(this)
  isActive := Func("shell_141").Bind(this)
  isExists := Func("shell_140").Bind(this)
  isFullScreen := Func("shell_139").Bind(this)
  kill := Func("shell_138").Bind(this)
  maximize := Func("shell_137").Bind(this)
  minimize := Func("shell_136").Bind(this)
  restore := Func("shell_135").Bind(this)
  setPriority := Func("shell_134").Bind(this)
  setStyle := Func("shell_133").Bind(this)
  show := Func("shell_132").Bind(this)
  wait := Func("shell_131").Bind(this)
}
__rf_shell__.Call(__noop__, "#rf/shell/3").Call(WindowShell)
global __shell_module_26__ := (Func("shell_130")).Call()
global __shell_module_33__ := (Func("shell_128")).Call()
global __shell_module_50__ := (Func("shell_126")).Call()
global __shell_module_54__ := (Func("shell_124")).Call()
global __shell_module_68__ := (Func("shell_123")).Call()
global __shell_module_71__ := (Func("shell_121")).Call()
global __shell_module_80__ := (Func("shell_119")).Call()
global __shell_module_97__ := (Func("shell_117")).Call()
global __shell_module_106__ := (Func("shell_115")).Call()
global __shell_module_108__ := (Func("shell_113")).Call()
global __shell_module_4__ := (Func("shell_111")).Call()
global __shell_module_6__ := (Func("shell_109")).Call()
global __shell_module_27__ := (Func("shell_107")).Call()
global __shell_module_32__ := (Func("shell_105")).Call()
global __shell_module_41__ := (Func("shell_101")).Call()
global __shell_module_47__ := (Func("shell_99")).Call()
global __shell_module_49__ := (Func("shell_97")).Call()
global __shell_module_53__ := (Func("shell_95")).Call()
global __shell_module_62__ := (Func("shell_93")).Call()
global __shell_module_73__ := (Func("shell_91")).Call()
global __shell_module_76__ := (Func("shell_89")).Call()
global __shell_module_91__ := (Func("shell_87")).Call()
global __shell_module_93__ := (Func("shell_85")).Call()
global __shell_module_11__ := (Func("shell_83")).Call()
global __shell_module_19__ := (Func("shell_80")).Call()
global __shell_module_21__ := (Func("shell_77")).Call()
global __shell_module_23__ := (Func("shell_75")).Call()
global __shell_module_24__ := (Func("shell_73")).Call()
global __shell_module_35__ := (Func("shell_71")).Call()
global __shell_module_69__ := (Func("shell_69")).Call()
global __shell_module_78__ := (Func("shell_65")).Call()
global __shell_module_79__ := (Func("shell_63")).Call()
global __shell_module_81__ := (Func("shell_61")).Call()
global __shell_module_83__ := (Func("shell_59")).Call()
global __shell_module_84__ := (Func("shell_57")).Call()
global __shell_module_105__ := (Func("shell_55")).Call()
global __each__ := __shell_module_20__
global __filter__ := __shell_module_27__
__noop__ := __shell_module_60__
global __push__ := __shell_module_71__
global __split__ := __shell_module_85__
class EmitterShell {
  __New() {
    this.bus := []
  }
  emit := Func("shell_53").Bind(this)
  off := Func("shell_48").Bind(this)
  on := Func("shell_45").Bind(this)
  once := Func("shell_44").Bind(this)
}
__rf_shell__.Call(__noop__, "#rf/shell/4").Call(EmitterShell)
__filter__ := __shell_module_27__
global __forEach__ := __shell_module_31__
global __formatHotkey__ := __shell_module_32__
__noop__ := __shell_module_60__
__push__ := __shell_module_71__
__replace__ := __shell_module_75__
__split__ := __shell_module_85__
class KeyBindingShell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
  }
  add := Func("shell_43").Bind(this)
  fire := Func("shell_42").Bind(this)
  formatKey := Func("shell_39").Bind(this)
  prepare := Func("shell_38").Bind(this)
  prevent := Func("shell_36").Bind(this)
  register := Func("shell_35").Bind(this)
  remove := Func("shell_34").Bind(this)
}
__rf_shell__.Call(__noop__, "#rf/shell/5").Call(KeyBindingShell)
global __shell_module_10__ := (Func("shell_32")).Call()
global __shell_module_15__ := (Func("shell_30")).Call()
global __shell_module_17__ := (Func("shell_27")).Call()
global __shell_module_22__ := (Func("shell_24")).Call()
global __shell_module_48__ := (Func("shell_22")).Call()
global __shell_module_90__ := (Func("shell_20")).Call()
global __shell_module_92__ := (Func("shell_18")).Call()
global __shell_module_109__ := (Func("shell_14")).Call()
global __shell_module_12__ := (Func("shell_13")).Call()
global __shell_module_16__ := (Func("shell_11")).Call()
global __shell_module_57__ := (Func("shell_8")).Call()
global __shell_module_63__ := (Func("shell_6")).Call()
global __shell_module_64__ := (Func("shell_5")).Call()
global __shell_module_70__ := (Func("shell_4")).Call()
global __shell_module_101__ := (Func("shell_3")).Call()
global __shell_module_107__ := (Func("shell_2")).Call()
global __add__ := __shell_module_1__
global __alert__ := __shell_module_2__
global __beep__ := __shell_module_3__
global __bind__ := __shell_module_4__
global __blockInput__ := __shell_module_5__
global __chunk__ := __shell_module_6__
global __clearInterval__ := __shell_module_7__
global __clearTimeout__ := __shell_module_8__
global __click__ := __shell_module_9__
global __clone__ := __shell_module_10__
global __compact__ := __shell_module_11__
global __concat__ := __shell_module_12__
global __confirm__ := __shell_module_13__
global __createList__ := __shell_module_14__
global __debounce__ := __shell_module_15__
global __defer__ := __shell_module_16__
global __delay__ := __shell_module_17__
global __delete__ := __shell_module_18__
global __drop__ := __shell_module_19__
__each__ := __shell_module_20__
global __echo__ := __shell_module_21__
global __emitter__ := __shell_module_22__
global __eq__ := __shell_module_23__
global __exec__ := __shell_module_24__
global __exit__ := __shell_module_25__
global __file__ := __shell_module_26__
__filter__ := __shell_module_27__
global __findColor__ := __shell_module_28__
global __findImage__ := __shell_module_29__
global __first__ := __shell_module_30__
__forEach__ := __shell_module_31__
__formatHotkey__ := __shell_module_32__
global __getColor__ := __shell_module_33__
global __getPosition__ := __shell_module_34__
global __getState__ := __shell_module_35__
global __getType__ := __shell_module_36__
global __gt__ := __shell_module_37__
global __gte__ := __shell_module_38__
global __head__ := __shell_module_39__
global __httpGet__ := __shell_module_40__
global __includes__ := __shell_module_41__
global __isArray__ := __shell_module_42__
global __isFunction__ := __shell_module_43__
global __isNumber__ := __shell_module_44__
global __isObject__ := __shell_module_45__
global __isString__ := __shell_module_46__
global __join__ := __shell_module_47__
global __keys__ := __shell_module_48__
global __last__ := __shell_module_49__
global __length__ := __shell_module_50__
global __lt__ := __shell_module_51__
global __lte__ := __shell_module_52__
global __map__ := __shell_module_53__
global __math__ := __shell_module_54__
global __max__ := __shell_module_55__
global __min__ := __shell_module_56__
global __mixin__ := __shell_module_57__
global __mod__ := __shell_module_58__
global __move__ := __shell_module_59__
__noop__ := __shell_module_60__
global __now__ := __shell_module_61__
global __nth__ := __shell_module_62__
global __off__ := __shell_module_63__
global __on__ := __shell_module_64__
global __once__ := __shell_module_65__
global __open__ := __shell_module_66__
global __play__ := __shell_module_67__
global __pop__ := __shell_module_68__
global __press__ := __shell_module_69__
global __preventInput__ := __shell_module_70__
__push__ := __shell_module_71__
global __random__ := __shell_module_72__
global __range__ := __shell_module_73__
global __reload__ := __shell_module_74__
__replace__ := __shell_module_75__
global __reverse__ := __shell_module_76__
global __setFixed__ := __shell_module_77__
global __setInterval__ := __shell_module_78__
global __setTimeout__ := __shell_module_79__
global __shift__ := __shell_module_80__
global __shuffle__ := __shell_module_81__
global __sleep__ := __shell_module_82__
global __slice__ := __shell_module_83__
global __sort__ := __shell_module_84__
__split__ := __shell_module_85__
global __startsWith__ := __shell_module_86__
global __subString__ := __shell_module_87__
global __sum__ := __shell_module_88__
global __suspend__ := __shell_module_89__
global __tail__ := __shell_module_90__
global __take__ := __shell_module_91__
global __throttle__ := __shell_module_92__
global __tip__ := __shell_module_93__
global __toLower__ := __shell_module_94__
global __toLowerCase__ := __shell_module_95__
global __toNumber__ := __shell_module_96__
global __toString__ := __shell_module_97__
global __toTuple__ := __shell_module_98__
global __toUpper__ := __shell_module_99__
global __toUpperCase__ := __shell_module_100__
global __trigger__ := __shell_module_101__
global __trim__ := __shell_module_102__
global __trimEnd__ := __shell_module_103__
global __trimStart__ := __shell_module_104__
global __uniq__ := __shell_module_105__
global __unshift__ := __shell_module_106__
global __values__ := __shell_module_107__
global __window__ := __shell_module_108__
global $ := {}
__rf_shell__.Call(__mixin__, "#rf/shell/6").Call($, {add: __add__})
__rf_shell__.Call(__mixin__, "#rf/shell/7").Call($, {alert: __alert__})
__rf_shell__.Call(__mixin__, "#rf/shell/8").Call($, {beep: __beep__})
__rf_shell__.Call(__mixin__, "#rf/shell/9").Call($, {bind: __bind__})
__rf_shell__.Call(__mixin__, "#rf/shell/10").Call($, {blockInput: __blockInput__})
__rf_shell__.Call(__mixin__, "#rf/shell/11").Call($, {chunk: __chunk__})
__rf_shell__.Call(__mixin__, "#rf/shell/12").Call($, {clearInterval: __clearInterval__})
__rf_shell__.Call(__mixin__, "#rf/shell/13").Call($, {clearTimeout: __clearTimeout__})
__rf_shell__.Call(__mixin__, "#rf/shell/14").Call($, {click: __click__})
__rf_shell__.Call(__mixin__, "#rf/shell/15").Call($, {clone: __clone__})
__rf_shell__.Call(__mixin__, "#rf/shell/16").Call($, {compact: __compact__})
__rf_shell__.Call(__mixin__, "#rf/shell/17").Call($, {concat: __concat__})
__rf_shell__.Call(__mixin__, "#rf/shell/18").Call($, {confirm: __confirm__})
__rf_shell__.Call(__mixin__, "#rf/shell/19").Call($, {createList: __createList__})
__rf_shell__.Call(__mixin__, "#rf/shell/20").Call($, {debounce: __debounce__})
__rf_shell__.Call(__mixin__, "#rf/shell/21").Call($, {defer: __defer__})
__rf_shell__.Call(__mixin__, "#rf/shell/22").Call($, {delay: __delay__})
__rf_shell__.Call(__mixin__, "#rf/shell/23").Call($, {delete: __delete__})
__rf_shell__.Call(__mixin__, "#rf/shell/24").Call($, {drop: __drop__})
__rf_shell__.Call(__mixin__, "#rf/shell/25").Call($, {each: __each__})
__rf_shell__.Call(__mixin__, "#rf/shell/26").Call($, {echo: __echo__})
__rf_shell__.Call(__mixin__, "#rf/shell/27").Call($, {emitter: __emitter__})
__rf_shell__.Call(__mixin__, "#rf/shell/28").Call($, {eq: __eq__})
__rf_shell__.Call(__mixin__, "#rf/shell/29").Call($, {exec: __exec__})
__rf_shell__.Call(__mixin__, "#rf/shell/30").Call($, {exit: __exit__})
__rf_shell__.Call(__mixin__, "#rf/shell/31").Call($, {file: __file__})
__rf_shell__.Call(__mixin__, "#rf/shell/32").Call($, {filter: __filter__})
__rf_shell__.Call(__mixin__, "#rf/shell/33").Call($, {findColor: __findColor__})
__rf_shell__.Call(__mixin__, "#rf/shell/34").Call($, {findImage: __findImage__})
__rf_shell__.Call(__mixin__, "#rf/shell/35").Call($, {first: __first__})
__rf_shell__.Call(__mixin__, "#rf/shell/36").Call($, {forEach: __forEach__})
__rf_shell__.Call(__mixin__, "#rf/shell/37").Call($, {formatHotkey: __formatHotkey__})
__rf_shell__.Call(__mixin__, "#rf/shell/38").Call($, {getColor: __getColor__})
__rf_shell__.Call(__mixin__, "#rf/shell/39").Call($, {getPosition: __getPosition__})
__rf_shell__.Call(__mixin__, "#rf/shell/40").Call($, {getState: __getState__})
__rf_shell__.Call(__mixin__, "#rf/shell/41").Call($, {getType: __getType__})
__rf_shell__.Call(__mixin__, "#rf/shell/42").Call($, {gt: __gt__})
__rf_shell__.Call(__mixin__, "#rf/shell/43").Call($, {gte: __gte__})
__rf_shell__.Call(__mixin__, "#rf/shell/44").Call($, {head: __head__})
__rf_shell__.Call(__mixin__, "#rf/shell/45").Call($, {httpGet: __httpGet__})
__rf_shell__.Call(__mixin__, "#rf/shell/46").Call($, {includes: __includes__})
__rf_shell__.Call(__mixin__, "#rf/shell/47").Call($, {isArray: __isArray__})
__rf_shell__.Call(__mixin__, "#rf/shell/48").Call($, {isFunction: __isFunction__})
__rf_shell__.Call(__mixin__, "#rf/shell/49").Call($, {isNumber: __isNumber__})
__rf_shell__.Call(__mixin__, "#rf/shell/50").Call($, {isObject: __isObject__})
__rf_shell__.Call(__mixin__, "#rf/shell/51").Call($, {isString: __isString__})
__rf_shell__.Call(__mixin__, "#rf/shell/52").Call($, {join: __join__})
__rf_shell__.Call(__mixin__, "#rf/shell/53").Call($, {keys: __keys__})
__rf_shell__.Call(__mixin__, "#rf/shell/54").Call($, {last: __last__})
__rf_shell__.Call(__mixin__, "#rf/shell/55").Call($, {length: __length__})
__rf_shell__.Call(__mixin__, "#rf/shell/56").Call($, {lt: __lt__})
__rf_shell__.Call(__mixin__, "#rf/shell/57").Call($, {lte: __lte__})
__rf_shell__.Call(__mixin__, "#rf/shell/58").Call($, {map: __map__})
__rf_shell__.Call(__mixin__, "#rf/shell/59").Call($, {math: __math__})
__rf_shell__.Call(__mixin__, "#rf/shell/60").Call($, {max: __max__})
__rf_shell__.Call(__mixin__, "#rf/shell/61").Call($, {min: __min__})
__rf_shell__.Call(__mixin__, "#rf/shell/62").Call($, {mixin: __mixin__})
__rf_shell__.Call(__mixin__, "#rf/shell/63").Call($, {mod: __mod__})
__rf_shell__.Call(__mixin__, "#rf/shell/64").Call($, {move: __move__})
__rf_shell__.Call(__mixin__, "#rf/shell/65").Call($, {noop: __noop__})
__rf_shell__.Call(__mixin__, "#rf/shell/66").Call($, {now: __now__})
__rf_shell__.Call(__mixin__, "#rf/shell/67").Call($, {nth: __nth__})
__rf_shell__.Call(__mixin__, "#rf/shell/68").Call($, {off: __off__})
__rf_shell__.Call(__mixin__, "#rf/shell/69").Call($, {on: __on__})
__rf_shell__.Call(__mixin__, "#rf/shell/70").Call($, {once: __once__})
__rf_shell__.Call(__mixin__, "#rf/shell/71").Call($, {open: __open__})
__rf_shell__.Call(__mixin__, "#rf/shell/72").Call($, {play: __play__})
__rf_shell__.Call(__mixin__, "#rf/shell/73").Call($, {pop: __pop__})
__rf_shell__.Call(__mixin__, "#rf/shell/74").Call($, {press: __press__})
__rf_shell__.Call(__mixin__, "#rf/shell/75").Call($, {preventInput: __preventInput__})
__rf_shell__.Call(__mixin__, "#rf/shell/76").Call($, {push: __push__})
__rf_shell__.Call(__mixin__, "#rf/shell/77").Call($, {random: __random__})
__rf_shell__.Call(__mixin__, "#rf/shell/78").Call($, {range: __range__})
__rf_shell__.Call(__mixin__, "#rf/shell/79").Call($, {reload: __reload__})
__rf_shell__.Call(__mixin__, "#rf/shell/80").Call($, {replace: __replace__})
__rf_shell__.Call(__mixin__, "#rf/shell/81").Call($, {reverse: __reverse__})
__rf_shell__.Call(__mixin__, "#rf/shell/82").Call($, {setFixed: __setFixed__})
__rf_shell__.Call(__mixin__, "#rf/shell/83").Call($, {setInterval: __setInterval__})
__rf_shell__.Call(__mixin__, "#rf/shell/84").Call($, {setTimeout: __setTimeout__})
__rf_shell__.Call(__mixin__, "#rf/shell/85").Call($, {shift: __shift__})
__rf_shell__.Call(__mixin__, "#rf/shell/86").Call($, {shuffle: __shuffle__})
__rf_shell__.Call(__mixin__, "#rf/shell/87").Call($, {sleep: __sleep__})
__rf_shell__.Call(__mixin__, "#rf/shell/88").Call($, {slice: __slice__})
__rf_shell__.Call(__mixin__, "#rf/shell/89").Call($, {sort: __sort__})
__rf_shell__.Call(__mixin__, "#rf/shell/90").Call($, {split: __split__})
__rf_shell__.Call(__mixin__, "#rf/shell/91").Call($, {startsWith: __startsWith__})
__rf_shell__.Call(__mixin__, "#rf/shell/92").Call($, {subString: __subString__})
__rf_shell__.Call(__mixin__, "#rf/shell/93").Call($, {sum: __sum__})
__rf_shell__.Call(__mixin__, "#rf/shell/94").Call($, {suspend: __suspend__})
__rf_shell__.Call(__mixin__, "#rf/shell/95").Call($, {tail: __tail__})
__rf_shell__.Call(__mixin__, "#rf/shell/96").Call($, {take: __take__})
__rf_shell__.Call(__mixin__, "#rf/shell/97").Call($, {throttle: __throttle__})
__rf_shell__.Call(__mixin__, "#rf/shell/98").Call($, {tip: __tip__})
__rf_shell__.Call(__mixin__, "#rf/shell/99").Call($, {toLower: __toLower__})
__rf_shell__.Call(__mixin__, "#rf/shell/100").Call($, {toLowerCase: __toLowerCase__})
__rf_shell__.Call(__mixin__, "#rf/shell/101").Call($, {toNumber: __toNumber__})
__rf_shell__.Call(__mixin__, "#rf/shell/102").Call($, {toString: __toString__})
__rf_shell__.Call(__mixin__, "#rf/shell/103").Call($, {toTuple: __toTuple__})
__rf_shell__.Call(__mixin__, "#rf/shell/104").Call($, {toUpper: __toUpper__})
__rf_shell__.Call(__mixin__, "#rf/shell/105").Call($, {toUpperCase: __toUpperCase__})
__rf_shell__.Call(__mixin__, "#rf/shell/106").Call($, {trigger: __trigger__})
__rf_shell__.Call(__mixin__, "#rf/shell/107").Call($, {trim: __trim__})
__rf_shell__.Call(__mixin__, "#rf/shell/108").Call($, {trimEnd: __trimEnd__})
__rf_shell__.Call(__mixin__, "#rf/shell/109").Call($, {trimStart: __trimStart__})
__rf_shell__.Call(__mixin__, "#rf/shell/110").Call($, {uniq: __uniq__})
__rf_shell__.Call(__mixin__, "#rf/shell/111").Call($, {unshift: __unshift__})
__rf_shell__.Call(__mixin__, "#rf/shell/112").Call($, {values: __values__})
__rf_shell__.Call(__mixin__, "#rf/shell/113").Call($, {window: __window__})
shell_1(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/114").Call(ipt)
  if !(__type__ == "object") {
    throw "$.values: invalid type '" . (__type__) . "'"
  }
  __listResult__ := []
  for __index_for__, __key__ in __rf_shell__.Call(__keys__, "#rf/shell/115").Call(ipt) {
    __rf_shell__.Call(__push__, "#rf/shell/116").Call(__listResult__, ipt[__ci_shell__.Call(__key__)])
  }
  return __listResult__
}
shell_2() {
  __getType__ := __shell_module_36__
  __keys__ := __shell_module_48__
  __push__ := __shell_module_71__
  return Func("shell_1")
}
shell_3() {
  __keyBindingXShell__ := __shell_module_109__
  return __keyBindingXShell__.fire
}
shell_4() {
  __keyBindingXShell__ := __shell_module_109__
  return __keyBindingXShell__.prevent
}
shell_5() {
  __keyBindingXShell__ := __shell_module_109__
  return __keyBindingXShell__.add
}
shell_6() {
  __keyBindingXShell__ := __shell_module_109__
  return __keyBindingXShell__.remove
}
shell_7(args*) {
  if !(__rf_shell__.Call(__length__, "#rf/shell/117").Call(args)) {
    throw "$.mixin: invalid arguments"
  }
  __result__ := args[1]
  for __index_for__, __item__ in __rf_shell__.Call(__tail__, "#rf/shell/118").Call(args) {
    for __key__, __value__ in __item__ {
      __result__[__ci_shell__.Call(__key__)] := __value__
    }
  }
  return __result__
}
shell_8() {
  __length__ := __shell_module_50__
  __tail__ := __shell_module_90__
  return Func("shell_7")
}
shell_9(__func__, __args__) {
  return __rf_shell__.Call(__func__, "#rf/shell/119").Call(__args__*)
}
shell_10(__func__, __args__*) {
  return __rf_shell__.Call(__delay__, "#rf/shell/120").Call(Func("shell_9").Bind(__func__, __args__), 1)
}
shell_11() {
  __delay__ := __shell_module_17__
  return Func("shell_10")
}
shell_12(__list__, __values__*) {
  __listNew__ := __rf_shell__.Call(__clone__, "#rf/shell/121").Call(__list__)
  for __index_for__, __value__ in __values__ {
    if (__rf_shell__.Call(__isArray__, "#rf/shell/122").Call(__value__)) {
      for __index_for__, __item__ in __value__ {
        __rf_shell__.Call(__push__, "#rf/shell/123").Call(__listNew__, __item__)
      }
    } else {
      __rf_shell__.Call(__push__, "#rf/shell/124").Call(__listNew__, __value__)
    }
  }
  return __listNew__
}
shell_13() {
  __clone__ := __shell_module_10__
  __isArray__ := __shell_module_42__
  __push__ := __shell_module_71__
  return Func("shell_12")
}
shell_14() {
  return new KeyBindingShell()
}
shell_15(__func__, __tsThrottle__, __index__) {
  __rf_shell__.Call(__func__, "#rf/shell/125").Call()
  __tsThrottle__[__ci_shell__.Call(__index__)] := __rf_shell__.Call(__now__, "#rf/shell/126").Call()
}
shell_16(__tThrottle__, __func__, __tsThrottle__, __wait__, __index__) {
  __rf_shell__.Call(__clearTimeout__, "#rf/shell/127").Call(__tThrottle__[__ci_shell__.Call(__index__)])
  __tThrottle__[__ci_shell__.Call(__index__)] := __rf_shell__.Call(__setTimeout__, "#rf/shell/128").Call(Func("shell_15").Bind(__func__, __tsThrottle__, __index__), __tsThrottle__[__ci_shell__.Call(__index__)] - __rf_shell__.Call(__now__, "#rf/shell/129").Call() + __wait__)
}
shell_17(__tsThrottle__, __tThrottle__, __func__, __wait__) {
  __iThrottle__++
  __tsThrottle__[__ci_shell__.Call(__iThrottle__)] := 0
  return Func("shell_16").Bind(__tThrottle__, __func__, __tsThrottle__, __wait__, __iThrottle__)
}
shell_18() {
  __clearTimeout__ := __shell_module_8__
  __now__ := __shell_module_61__
  __setTimeout__ := __shell_module_79__
  __iThrottle__ := 0
  __tThrottle__ := {}
  __tsThrottle__ := {}
  return Func("shell_17").Bind(__tsThrottle__, __tThrottle__)
}
shell_19(list) {
  return __rf_shell__.Call(__drop__, "#rf/shell/130").Call(list, 1)
}
shell_20() {
  __drop__ := __shell_module_19__
  return Func("shell_19")
}
shell_21(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/131").Call(ipt)
  if !(__type__ == "object") {
    throw "$.keys: invalid type '" . (__type__) . "'"
  }
  __listResult__ := []
  for __key__, __value__ in ipt {
    __rf_shell__.Call(__push__, "#rf/shell/132").Call(__listResult__, __key__)
  }
  return __rf_shell__.Call(__sort__, "#rf/shell/133").Call(__listResult__)
}
shell_22() {
  __getType__ := __shell_module_36__
  __push__ := __shell_module_71__
  __sort__ := __shell_module_84__
  return Func("shell_21")
}
shell_23() {
  return new EmitterShell()
}
shell_24() {
  return Func("shell_23")
}
shell_25(__func__, __args__) {
  return __rf_shell__.Call(__func__, "#rf/shell/134").Call(__args__*)
}
shell_26(__func__, __wait__, __args__*) {
  __timer__ := __rf_shell__.Call(__setTimeout__, "#rf/shell/135").Call(Func("shell_25").Bind(__func__, __args__), __wait__)
  return __timer__
}
shell_27() {
  __setTimeout__ := __shell_module_79__
  return Func("shell_26")
}
shell_28(__tDebounce__, __func__, __wait__, __index__) {
  __rf_shell__.Call(__clearTimeout__, "#rf/shell/136").Call(__tDebounce__[__ci_shell__.Call(__index__)])
  __tDebounce__[__ci_shell__.Call(__index__)] := __rf_shell__.Call(__setTimeout__, "#rf/shell/137").Call(__func__, __wait__)
}
shell_29(__tDebounce__, __func__, __wait__) {
  __iDebounce__++
  return Func("shell_28").Bind(__tDebounce__, __func__, __wait__, __iDebounce__)
}
shell_30() {
  __clearTimeout__ := __shell_module_8__
  __setTimeout__ := __shell_module_79__
  __iDebounce__ := 0
  __tDebounce__ := {}
  return Func("shell_29").Bind(__tDebounce__)
}
shell_31(ipt) {
  if (__rf_shell__.Call(__isArray__, "#rf/shell/138").Call(ipt)) {
    return __rf_shell__.Call(__slice__, "#rf/shell/139").Call(ipt)
  }
  if (__rf_shell__.Call(__isObject__, "#rf/shell/140").Call(ipt)) {
    __mapNew__ := {}
    for __key__, __value__ in ipt {
      __mapNew__[__ci_shell__.Call(__key__)] := __value__
    }
    return __mapNew__
  }
  throw "$.clone: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/141").Call(ipt)) . "'"
}
shell_32() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  __isObject__ := __shell_module_45__
  __slice__ := __shell_module_83__
  return Func("shell_31")
}
shell_33(__name__, __item__) {
  return __item__[1] != __name__
}
shell_34(this, key) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/142").Call((__rf_shell__.Call(__replace__, "#rf/shell/143").Call(key, ":down", "")), ".")
  __key__ := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    this.mapCallback[__ci_shell__.Call(__key__)] := []
    return
  }
  __listNew__ := __rf_shell__.Call(__filter__, "#rf/shell/144").Call(this.mapCallback[__ci_shell__.Call(__key__)], Func("shell_33").Bind(__name__))
  this.mapCallback[__ci_shell__.Call(__key__)] := __listNew__
  return
}
shell_35(this, key, action) {
  __rf_shell__.Call(this.prepare, "#rf/shell/145").Call(key)
  __callback__ := this.mapBound[__ci_shell__.Call(key)]
  __key__ := __rf_shell__.Call(this.formatKey, "#rf/shell/146").Call(key, "~")
  __rf_shell__.Call(__noop__, "#rf/shell/147").Call(__callback__, __key__)
  if (action) {
    Hotkey, % __key__, % __callback__, On
  } else {
    Hotkey, % __key__, % __callback__, Off
  }
  return
}
shell_36(this, key, isPrevented) {
  __rf_shell__.Call(this.prepare, "#rf/shell/148").Call(key)
  __callback__ := this.mapBound[__ci_shell__.Call(key)]
  __key__ := __rf_shell__.Call(this.formatKey, "#rf/shell/149").Call(key)
  __rf_shell__.Call(__noop__, "#rf/shell/150").Call(__callback__, __key__)
  if (isPrevented) {
    Hotkey, % __key__, % __callback__, On
  } else {
    Hotkey, % __key__, % __callback__, Off
  }
  return
}
shell_37(key, this) {
  return __rf_shell__.Call(this.fire, "#rf/shell/151").Call(key)
}
shell_38(this, key) {
  if (this.mapCallback[__ci_shell__.Call(key)]) {
    return
  }
  this.mapBound[__ci_shell__.Call(key)] := Func("shell_37").Bind(key, this)
  this.mapCallback[__ci_shell__.Call(key)] := []
  return
}
shell_39(this, key, prefix := "") {
  __key__ := __rf_shell__.Call(__formatHotkey__, "#rf/shell/152").Call(__rf_shell__.Call(__replace__, "#rf/shell/153").Call(key, ":down", ""))
  if !(prefix) {
    return __key__
  }
  return "" . (prefix) . "" . (__key__) . ""
}
shell_40(it) {
  return __rf_shell__.Call(it[2], "#rf/shell/154").Call()
}
shell_41(__name__, it) {
  return it[1] == __name__
}
shell_42(this, key) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/155").Call((__rf_shell__.Call(__replace__, "#rf/shell/156").Call(key, ":down", "")), ".")
  __key__ := __array__[1]
  __name__ := __array__[2]
  __list__ := this.mapCallback[__ci_shell__.Call(__key__)]
  if (__name__) {
    __list__ := __rf_shell__.Call(__filter__, "#rf/shell/157").Call(__list__, Func("shell_41").Bind(__name__))
  }
  __rf_shell__.Call(__forEach__, "#rf/shell/158").Call(__list__, Func("shell_40"))
}
shell_43(this, key, callback) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/159").Call((__rf_shell__.Call(__replace__, "#rf/shell/160").Call(key, ":down", "")), ".")
  __key__ := __array__[1]
  __name__ := __array__[2]
  __rf_shell__.Call(this.register, "#rf/shell/161").Call(__key__, true)
  __rf_shell__.Call(__push__, "#rf/shell/162").Call(this.mapCallback[__ci_shell__.Call(__key__)], [__name__, callback])
  return
}
shell_44(this, key, callback) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/163").Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  __rf_shell__.Call(__push__, "#rf/shell/164").Call(this.bus, [__type__, __name__, callback, "once"])
  return
}
shell_45(this, key, callback) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/165").Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  __rf_shell__.Call(__push__, "#rf/shell/166").Call(this.bus, [__type__, __name__, callback, "always"])
  return
}
shell_46(__type__, __it__) {
  return __it__[1] != __type__
}
shell_47(__type__, __name__, __it__) {
  return !(__it__[1] == __type__ && __it__[2] == __name__)
}
shell_48(this, key) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/167").Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    this.bus := []
    return
  }
  if (__name__) {
    this.bus := __rf_shell__.Call(__filter__, "#rf/shell/168").Call(this.bus, Func("shell_47").Bind(__type__, __name__))
  } else {
    this.bus := __rf_shell__.Call(__filter__, "#rf/shell/169").Call(this.bus, Func("shell_46").Bind(__type__))
  }
  return
}
shell_49(__it__) {
  return __it__[4] != "expired"
}
shell_50(args, __it__) {
  __rf_shell__.Call(__it__[3], "#rf/shell/170").Call(args*)
  if (__it__[4] == "once") {
    __it__[4] := "expired"
  }
  return
}
shell_51(__type__, __it__) {
  return __it__[1] == __type__
}
shell_52(__type__, __name__, __it__) {
  return __it__[1] == __type__ && __it__[2] == __name__
}
shell_53(this, key, args*) {
  __array__ := __rf_shell__.Call(__split__, "#rf/shell/171").Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    return
  }
  if (__name__) {
    __list__ := __rf_shell__.Call(__filter__, "#rf/shell/172").Call(this.bus, Func("shell_52").Bind(__type__, __name__))
  } else {
    __list__ := __rf_shell__.Call(__filter__, "#rf/shell/173").Call(this.bus, Func("shell_51").Bind(__type__))
  }
  __rf_shell__.Call(__each__, "#rf/shell/174").Call(__list__, Func("shell_50").Bind(args))
  this.bus := __rf_shell__.Call(__filter__, "#rf/shell/175").Call(this.bus, Func("shell_49"))
  return
}
shell_54(list) {
  __hasString__ := false
  for __index_for__, __item__ in list {
    if (__rf_shell__.Call(__isString__, "#rf/shell/176").Call(__item__)) {
      __hasString__ := true
      break
    }
  }
  __string__ := __rf_shell__.Call(__join__, "#rf/shell/177").Call(list, ",")
  if (__hasString__) {
    Sort, __string__, C U D,
  } else {
    Sort, __string__, N U D,
  }
  return __rf_shell__.Call(__split__, "#rf/shell/178").Call(__string__, ",")
}
shell_55() {
  __isString__ := __shell_module_46__
  __join__ := __shell_module_47__
  __split__ := __shell_module_85__
  return Func("shell_54")
}
shell_56(list) {
  __string__ := __rf_shell__.Call(__join__, "#rf/shell/179").Call(list, ",")
  Sort, __string__, C D,
  return __rf_shell__.Call(__split__, "#rf/shell/180").Call(__string__, ",")
}
shell_57() {
  __join__ := __shell_module_47__
  __split__ := __shell_module_85__
  return Func("shell_56")
}
shell_58(list, start := 0, end := 0) {
  if !(__rf_shell__.Call(__getType__, "#rf/shell/181").Call(list)) {
    throw "$.slice: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/182").Call(list)) . "'"
  }
  __len__ := __rf_shell__.Call(__length__, "#rf/shell/183").Call(list)
  if !(end) {
    end := __len__
  }
  if (start > __len__) {
    start := __len__
  }
  if (start < 0) {
    start := __len__ + start
  }
  if (end > __len__) {
    end := __len__
  }
  if (end < 0) {
    end := __len__ + end
  }
  __isReverse__ := false
  if (start > end) {
    __isReverse__ := true
    __array__ := [end, start]
    start := __array__[1]
    end := __array__[2]
  }
  __listNew__ := []
  __n__ := 0
  __max__ := end - start
  while (__n__ < __max__) {
    __rf_shell__.Call(__push__, "#rf/shell/184").Call(__listNew__, list[__ci_shell__.Call(start + __n__)])
    __n__++
  }
  if (__isReverse__) {
    return __rf_shell__.Call(__reverse__, "#rf/shell/185").Call(__listNew__)
  }
  return __listNew__
}
shell_59() {
  __getType__ := __shell_module_36__
  __length__ := __shell_module_50__
  __push__ := __shell_module_71__
  __reverse__ := __shell_module_76__
  return Func("shell_58")
}
shell_60(list) {
  __string__ := __rf_shell__.Call(__join__, "#rf/shell/186").Call(list, ",")
  Sort, __string__, Random D,
  return __rf_shell__.Call(__split__, "#rf/shell/187").Call(__string__, ",")
}
shell_61() {
  __join__ := __shell_module_47__
  __split__ := __shell_module_85__
  return Func("shell_60")
}
shell_62(callback, time) {
  callback := __rf_shell__.Call(__bind__, "#rf/shell/188").Call(callback)
  if !(__rf_shell__.Call(__isNumber__, "#rf/shell/189").Call(time)) {
    throw "$.setTimeout: invalid type"
  }
  if (time < 1) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
shell_63() {
  __bind__ := __shell_module_4__
  __isNumber__ := __shell_module_44__
  return Func("shell_62")
}
shell_64(callback, time) {
  callback := __rf_shell__.Call(__bind__, "#rf/shell/190").Call(callback)
  if !(time > 0) {
    throw "$.setInterval: invalid value"
  }
  SetTimer, % callback, % time
  return callback
}
shell_65() {
  __bind__ := __shell_module_4__
  return Func("shell_64")
}
shell_66(__validateInputPress__, __formatInputPress__, listInput*) {
  if !(__rf_shell__.Call(__validateInputPress__, "#rf/shell/191").Call(listInput)) {
    return
  }
  __listKey__ := __rf_shell__.Call(__formatInputPress__, "#rf/shell/192").Call(listInput)
  __listResult__ := []
  __len__ := __rf_shell__.Call(__length__, "#rf/shell/193").Call(__listKey__)
  for __i__, __key__ in __listKey__ {
    __i__ := __i__ - 1
    if (__i__ == __len__ - 1) {
      __listResult__[__ci_shell__.Call(__i__)] := __rf_shell__.Call(__split__, "#rf/shell/194").Call(__key__, ":")
      continue
    }
    if (__rf_shell__.Call(__includes__, "#rf/shell/195").Call(__key__, ":")) {
      __listResult__[__ci_shell__.Call(__i__)] := __rf_shell__.Call(__split__, "#rf/shell/196").Call(__key__, ":")
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := __rf_shell__.Call(__split__, "#rf/shell/197").Call(__key__, ":")
    } else {
      __listResult__[__ci_shell__.Call(__i__)] := [__key__, "down"]
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := [__key__, "up"]
    }
  }
  for __i__, __it__ in __listResult__ {
    __i__ := __i__ - 1
    if (__it__[1] == "win") {
      __it__[1] := "lwin"
    }
    __listResult__[__ci_shell__.Call(__i__)] := __rf_shell__.Call(__trim__, "#rf/shell/198").Call("" . (__it__[1]) . " " . (__it__[2]) . "")
  }
  __result__ := ""
  for __index_for__, __it__ in __listResult__ {
    __result__ := "" . (__result__) . "{" . (__it__) . "}"
  }
  Send, % __result__
  return
}
shell_67(listInput) {
  if !(__rf_shell__.Call(__length__, "#rf/shell/199").Call(listInput)) {
    return false
  }
  __key__ := listInput[1]
  if (__rf_shell__.Call(__includes__, "#rf/shell/200").Call(__key__, "-button")) {
    __key__ := __rf_shell__.Call(__replace__, "#rf/shell/201").Call(__key__, "l-button", "left")
    __key__ := __rf_shell__.Call(__replace__, "#rf/shell/202").Call(__key__, "m-button", "middle")
    __key__ := __rf_shell__.Call(__replace__, "#rf/shell/203").Call(__key__, "r-button", "right")
    __rf_shell__.Call(__click__, "#rf/shell/204").Call(__key__)
    return false
  }
  return true
}
shell_68(listInput) {
  __listKey__ := __rf_shell__.Call(__createList__, "#rf/shell/205").Call("string")
  for __index_for__, __input__ in listInput {
    __ipt__ := __rf_shell__.Call(__toLowerCase__, "#rf/shell/206").Call(__input__)
    __ipt__ := __rf_shell__.Call(__replace__, "#rf/shell/207").Call(__ipt__, " ", "")
    __ipt__ := __rf_shell__.Call(__replace__, "#rf/shell/208").Call(__ipt__, "-", "")
    __rf_shell__.Call(__push__, "#rf/shell/209").Call(__listKey__, (__rf_shell__.Call(__split__, "#rf/shell/210").Call(__ipt__, "+"))*)
  }
  return __listKey__
}
shell_69() {
  __click__ := __shell_module_9__
  __createList__ := __shell_module_14__
  __includes__ := __shell_module_41__
  __length__ := __shell_module_50__
  __push__ := __shell_module_71__
  __replace__ := __shell_module_75__
  __split__ := __shell_module_85__
  __toLowerCase__ := __shell_module_95__
  __trim__ := __shell_module_102__
  __formatInputPress__ := Func("shell_68")
  __validateInputPress__ := Func("shell_67")
  return Func("shell_66").Bind(__validateInputPress__, __formatInputPress__)
}
shell_70(key) {
  key := __rf_shell__.Call(__formatHotkey__, "#rf/shell/211").Call(key)
  return GetKeyState(key, "P")
}
shell_71() {
  __formatHotkey__ := __shell_module_32__
  return Func("shell_70")
}
shell_72(__input__, __callback__) {
  if (__rf_shell__.Call(__isString__, "#rf/shell/212").Call(__input__)) {
    __input__ := [__input__]
  }
  __input__ := __rf_shell__.Call(__join__, "#rf/shell/213").Call(__input__, " && ")
  RunWait, %comSpec% /c %__input__%,, Hide UseErrorLevel
  __rf_shell__.Call(__callback__, "#rf/shell/214").Call(ErrorLevel)
}
shell_73() {
  __isString__ := __shell_module_46__
  __join__ := __shell_module_47__
  __noop__ := __shell_module_60__
  return Func("shell_72").Bind(__noop__)
}
shell_74(value, other) {
  __typeA__ := __rf_shell__.Call(__getType__, "#rf/shell/215").Call(value)
  __typeB__ := __rf_shell__.Call(__getType__, "#rf/shell/216").Call(other)
  if !(__typeA__ == __typeB__) {
    return false
  }
  if (__rf_shell__.Call(__includes__, "#rf/shell/217").Call(["function", "number", "string"], __typeA__)) {
    return value == other
  }
  __lengthA__ := __rf_shell__.Call(__length__, "#rf/shell/218").Call(value)
  __lengthB__ := __rf_shell__.Call(__length__, "#rf/shell/219").Call(other)
  if !(__lengthA__ == __lengthB__) {
    return false
  }
  if (__rf_shell__.Call(__isArray__, "#rf/shell/220").Call(value)) {
    for __i__, __it__ in value {
      __i__ := __i__ - 1
      if !(__rf_shell__.Call(__eq__, "#rf/shell/221").Call(__it__, other[__ci_shell__.Call(__i__)])) {
        return false
      }
    }
    return true
  }
  if (__rf_shell__.Call(__isObject__, "#rf/shell/222").Call(value)) {
    for __k__, __v__ in value {
      if !(__rf_shell__.Call(__eq__, "#rf/shell/223").Call(__v__, other[__ci_shell__.Call(__k__)])) {
        return false
      }
    }
    return true
  }
  throw "$.eq: invalid type '" . (__typeA__) . "'"
}
shell_75() {
  __getType__ := __shell_module_36__
  __includes__ := __shell_module_41__
  __isArray__ := __shell_module_42__
  __isObject__ := __shell_module_45__
  __length__ := __shell_module_50__
  __eq__ := Func("shell_74")
  return __eq__
}
shell_76(message) {
  __rf_shell__.Call(__tip__, "#rf/shell/224").Call("[" . (__rf_shell__.Call(__now__, "#rf/shell/225").Call()) . "] " . (__rf_shell__.Call(__toString__, "#rf/shell/226").Call(message)) . "", [0, 0])
  return message
}
shell_77() {
  __now__ := __shell_module_61__
  __tip__ := __shell_module_93__
  __toString__ := __shell_module_97__
  return Func("shell_76")
}
shell_78(n, _it, i) {
  return i >= n
}
shell_79(list, n := 1) {
  return __rf_shell__.Call(__filter__, "#rf/shell/227").Call(list, Func("shell_78").Bind(n))
}
shell_80() {
  __filter__ := __shell_module_27__
  return Func("shell_79")
}
shell_81(it) {
  return !!it
}
shell_82(list) {
  return __rf_shell__.Call(__filter__, "#rf/shell/228").Call(list, Func("shell_81"))
}
shell_83() {
  __filter__ := __shell_module_27__
  return Func("shell_82")
}
shell_84(message, p := "") {
  if !(message) {
    return message
  }
  if !(p) {
    p := __rf_shell__.Call(__getPosition__, "#rf/shell/229").Call()
  }
  __msg__ := __rf_shell__.Call(__toString__, "#rf/shell/230").Call(message)
  __rf_shell__.Call(__noop__, "#rf/shell/231").Call(__msg__)
  ToolTip, % __msg__, % p[1], % p[2]
  return message
}
shell_85() {
  __getPosition__ := __shell_module_34__
  __noop__ := __shell_module_60__
  __toString__ := __shell_module_97__
  return Func("shell_84")
}
shell_86(list, count := 1) {
  __len__ := __rf_shell__.Call(__length__, "#rf/shell/232").Call(list)
  if !(__len__) {
    return []
  }
  if !(count >= 0) {
    return []
  }
  if (count >= __len__) {
    count := __len__
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if (__i__ >= count) {
      break
    }
    __rf_shell__.Call(__push__, "#rf/shell/233").Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_87() {
  __length__ := __shell_module_50__
  __push__ := __shell_module_71__
  return Func("shell_86")
}
shell_88(list) {
  __len__ := __rf_shell__.Call(__length__, "#rf/shell/234").Call(list)
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    __listNew__[__ci_shell__.Call(__len__ - 1 - __i__)] := __item__
  }
  for __i__, __item__ in __listNew__ {
    __i__ := __i__ - 1
    list[__ci_shell__.Call(__i__)] := __item__
  }
  return list
}
shell_89() {
  __length__ := __shell_module_50__
  return Func("shell_88")
}
shell_90(args*) {
  switch __rf_shell__.Call(__length__, "#rf/shell/235").Call(args) {
    case 1: {
      __array__ := [0, args[1], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 2: {
      __array__ := [args[1], args[2], 1]
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    case 3: {
      __array__ := args
      __start__ := __array__[1]
      __end__ := __array__[2]
      __step__ := __array__[3]
    }
    default: {
      throw "$.range: invalid arguments"
    }
  }
  if (__start__ == __end__) {
    return [__start__]
  }
  if (__start__ > __end__) {
    return []
  }
  __listResult__ := __rf_shell__.Call(__createList__, "#rf/shell/236").Call("number")
  __n__ := 0
  __max__ := __end__ - __start__
  while (__n__ < __max__) {
    __rf_shell__.Call(__push__, "#rf/shell/237").Call(__listResult__, __start__ + __step__ * __n__)
    __n__++
  }
  return __listResult__
}
shell_91() {
  __createList__ := __shell_module_14__
  __length__ := __shell_module_50__
  __push__ := __shell_module_71__
  return Func("shell_90")
}
shell_92(list, n := 0) {
  if (n >= 0) {
    return list[__ci_shell__.Call(n)]
  } else {
    return list[__ci_shell__.Call((__rf_shell__.Call(__length__, "#rf/shell/238").Call(list)) + n)]
  }
}
shell_93() {
  __length__ := __shell_module_50__
  return Func("shell_92")
}
shell_94(list, callback) {
  __listResult__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    __rf_shell__.Call(__push__, "#rf/shell/239").Call(__listResult__, __rf_shell__.Call(callback, "#rf/shell/240").Call(__item__, __i__))
  }
  return __listResult__
}
shell_95() {
  __push__ := __shell_module_71__
  return Func("shell_94")
}
shell_96(list) {
  return list[__ci_shell__.Call((__rf_shell__.Call(__length__, "#rf/shell/241").Call(list)) - 1)]
}
shell_97() {
  __length__ := __shell_module_50__
  return Func("shell_96")
}
shell_98(list, seperator := ",") {
  __result__ := ""
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__) {
      __result__ := __rf_shell__.Call(__toString__, "#rf/shell/242").Call(__item__)
      continue
    }
    __result__ := "" . (__result__) . "" . (seperator) . "" . (__item__) . ""
  }
  return __result__
}
shell_99() {
  __toString__ := __shell_module_97__
  return Func("shell_98")
}
shell_100(ipt, needle) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/243").Call(ipt)
  if ((__rf_shell__.Call(__isString__, "#rf/shell/244").Call(ipt)) || __rf_shell__.Call(__isNumber__, "#rf/shell/245").Call(ipt)) {
    if !(__rf_shell__.Call(__isString__, "#rf/shell/246").Call(needle)) {
      return false
    }
    return (InStr((__rf_shell__.Call(__toString__, "#rf/shell/247").Call(ipt)), needle)) > 0
  }
  if (__rf_shell__.Call(__isArray__, "#rf/shell/248").Call(ipt)) {
    for __index_for__, __it__ in ipt {
      if (__it__ == needle) {
        return true
      }
    }
    return false
  }
  throw "$.includes: invalid type '" . (__type__) . "'"
}
shell_101() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  __isNumber__ := __shell_module_44__
  __isString__ := __shell_module_46__
  __toString__ := __shell_module_97__
  return Func("shell_100")
}
shell_102(__formatKeyFormatHotkey__, __pickPrefixFormatHotkey__, key) {
  __listKey__ := __rf_shell__.Call(__formatKeyFormatHotkey__, "#rf/shell/249").Call(key)
  __array__ := __rf_shell__.Call(__pickPrefixFormatHotkey__, "#rf/shell/250").Call(__listKey__)
  __prefix__ := __array__[1]
  __listKey__ := __array__[2]
  __result__ := ""
  for __index_for__, __it__ in __listKey__ {
    __result__ := "" . (__result__) . " & " . (__it__) . ""
  }
  return __rf_shell__.Call(__replace__, "#rf/shell/251").Call("" . (__prefix__) . "" . (__rf_shell__.Call(__trim__, "#rf/shell/252").Call(__result__, " &")) . "", ":", " ")
}
shell_103(listKey) {
  if ((__rf_shell__.Call(__length__, "#rf/shell/253").Call(listKey)) == 1) {
    return ["", listKey]
  }
  __prefix__ := ""
  __listNew__ := __rf_shell__.Call(__createList__, "#rf/shell/254").Call("string")
  for __index_for__, __key__ in listKey {
    if (__key__ == "alt") {
      __prefix__ := "" . (__prefix__) . "!"
      continue
    }
    if (__key__ == "ctrl") {
      __prefix__ := "" . (__prefix__) . "^"
      continue
    }
    if (__key__ == "shift") {
      __prefix__ := "" . (__prefix__) . "+"
      continue
    }
    if (__key__ == "win") {
      __prefix__ := "" . (__prefix__) . "#"
      continue
    }
    __rf_shell__.Call(__push__, "#rf/shell/255").Call(__listNew__, __key__)
  }
  return [__prefix__, __listNew__]
}
shell_104(key) {
  __listKey__ := __rf_shell__.Call(__createList__, "#rf/shell/256").Call("string")
  __key__ := __rf_shell__.Call(__toLowerCase__, "#rf/shell/257").Call(key)
  __key__ := __rf_shell__.Call(__replace__, "#rf/shell/258").Call(__key__, " ", "")
  __key__ := __rf_shell__.Call(__replace__, "#rf/shell/259").Call(__key__, "-", "")
  __listSplit__ := __rf_shell__.Call(__split__, "#rf/shell/260").Call(__key__, "+")
  if (__rf_shell__.Call(__length__, "#rf/shell/261").Call(__listSplit__)) {
    __rf_shell__.Call(__push__, "#rf/shell/262").Call(__listKey__, __listSplit__*)
  }
  return __listKey__
}
shell_105() {
  __createList__ := __shell_module_14__
  __length__ := __shell_module_50__
  __push__ := __shell_module_71__
  __replace__ := __shell_module_75__
  __split__ := __shell_module_85__
  __toLowerCase__ := __shell_module_95__
  __trim__ := __shell_module_102__
  __formatKeyFormatHotkey__ := Func("shell_104")
  __pickPrefixFormatHotkey__ := Func("shell_103")
  return Func("shell_102").Bind(__formatKeyFormatHotkey__, __pickPrefixFormatHotkey__)
}
shell_106(list, callback) {
  __listResult__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__rf_shell__.Call(callback, "#rf/shell/263").Call(__item__, __i__)) {
      continue
    }
    __rf_shell__.Call(__push__, "#rf/shell/264").Call(__listResult__, __item__)
  }
  return __listResult__
}
shell_107() {
  __push__ := __shell_module_71__
  return Func("shell_106")
}
shell_108(__list__, __size__ := 1) {
  __listNew__ := []
  __len__ := __rf_shell__.Call(__length__, "#rf/shell/265").Call(__list__)
  __i__ := 0
  while (__i__ < __len__ / __size__) {
    __listTemp__ := []
    __j__ := 0
    while (__j__ < __size__) {
      __index__ := __i__ * __size__ + __j__
      if !(__index__ < __len__) {
        break
      }
      __rf_shell__.Call(__push__, "#rf/shell/266").Call(__listTemp__, __list__[__ci_shell__.Call(__index__)])
      __j__++
    }
    __rf_shell__.Call(__push__, "#rf/shell/267").Call(__listNew__, __listTemp__)
    __i__++
  }
  return __listNew__
}
shell_109() {
  __length__ := __shell_module_50__
  __push__ := __shell_module_71__
  return Func("shell_108")
}
shell_110(callback, args*) {
  if !(callback.Name) {
    if !(__rf_shell__.Call(__length__, "#rf/shell/268").Call(args)) {
      return callback
    }
    throw "$.bind: cannot bind a bound function"
  }
  return callback.Bind(args*)
}
shell_111() {
  __length__ := __shell_module_50__
  return Func("shell_110")
}
shell_112(exe) {
  return new WindowShell(exe)
}
shell_113() {
  return Func("shell_112")
}
shell_114(list, args*) {
  if !(__rf_shell__.Call(__isArray__, "#rf/shell/269").Call(list)) {
    throw "$.unshift: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/270").Call(list)) . "'"
  }
  list.InsertAt(1, args*)
  return list.Length()
}
shell_115() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  return Func("shell_114")
}
shell_116(ipt) {
  if (__rf_shell__.Call(__isString__, "#rf/shell/271").Call(ipt)) {
    return ipt
  }
  if (__rf_shell__.Call(__isNumber__, "#rf/shell/272").Call(ipt)) {
    return "" . (ipt) . ""
  }
  if (__rf_shell__.Call(__isArray__, "#rf/shell/273").Call(ipt)) {
    __result__ := ""
    for __index_for__, it in ipt {
      __result__ := "" . (__result__) . ", " . (__rf_shell__.Call(__toString__, "#rf/shell/274").Call(it)) . ""
    }
    return "[" . (__rf_shell__.Call(__trim__, "#rf/shell/275").Call(__result__, " ,")) . "]"
  }
  if (__rf_shell__.Call(__isObject__, "#rf/shell/276").Call(ipt)) {
    __result__ := ""
    for key, value in ipt {
      __result__ := "" . (__result__) . ", " . (key) . ": " . (__rf_shell__.Call(__toString__, "#rf/shell/277").Call(value)) . ""
    }
    return "{" . (__rf_shell__.Call(__trim__, "#rf/shell/278").Call(__result__, " ,")) . "}"
  }
  throw "__toString__: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/279").Call(ipt)) . "'"
}
shell_117() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  __isNumber__ := __shell_module_44__
  __isObject__ := __shell_module_45__
  __isString__ := __shell_module_46__
  __trim__ := __shell_module_102__
  __toString__ := Func("shell_116")
  return __toString__
}
shell_118(list) {
  if !(__rf_shell__.Call(__isArray__, "#rf/shell/280").Call(list)) {
    throw "$.shift: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/281").Call(list)) . "'"
  }
  __first__ := list[1]
  list.RemoveAt(1)
  return __first__
}
shell_119() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  return Func("shell_118")
}
shell_120(list, value*) {
  if !(__rf_shell__.Call(__isArray__, "#rf/shell/282").Call(list)) {
    throw "$.push: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/283").Call(list)) . "'"
  }
  for __index_for__, __v__ in value {
    list.Push(__v__)
  }
  return list.Length()
}
shell_121() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  return Func("shell_120")
}
shell_122(list) {
  if !(__rf_shell__.Call(__isArray__, "#rf/shell/284").Call(list)) {
    throw "$.pop: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/285").Call(list)) . "'"
  }
  return list.Pop()
}
shell_123() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  return Func("shell_122")
}
shell_124() {
  return new MathShell()
}
shell_125(ipt) {
  if (__rf_shell__.Call(__isArray__, "#rf/shell/286").Call(ipt)) {
    return ipt.Length()
  }
  if (__rf_shell__.Call(__isObject__, "#rf/shell/287").Call(ipt)) {
    return ipt.Count()
  }
  if (__rf_shell__.Call(__isString__, "#rf/shell/288").Call(ipt)) {
    return StrLen(ipt)
  }
  throw "$.length: invalid type '" . (__rf_shell__.Call(__getType__, "#rf/shell/289").Call(ipt)) . "'"
}
shell_126() {
  __getType__ := __shell_module_36__
  __isArray__ := __shell_module_42__
  __isObject__ := __shell_module_45__
  __isString__ := __shell_module_46__
  return Func("shell_125")
}
shell_127(p := "") {
  if !(p) {
    p := __rf_shell__.Call(__getPosition__, "#rf/shell/290").Call()
  }
  __result__ := 0
  PixelGetColor, __result__, % p[1], % p[2], RGB
  return __result__
}
shell_128() {
  __getPosition__ := __shell_module_34__
  return Func("shell_127")
}
shell_129(__source__) {
  return new FileShell(__source__)
}
shell_130() {
  return Func("shell_129")
}
shell_131(this, callback) {
  WinWait, % this.exe
  if (callback) {
    __rf_shell__.Call(callback, "#rf/shell/291").Call()
  }
  return
}
shell_132(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/292").Call()) {
    return
  }
  WinShow, % this.exe
  return
}
shell_133(this, style) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/293").Call()) {
    return
  }
  __rf_shell__.Call(__noop__, "#rf/shell/294").Call(style)
  WinSet, Style, % style, % this.exe
  return
}
shell_134(this, level) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/295").Call()) {
    return
  }
  __rf_shell__.Call(__noop__, "#rf/shell/296").Call(level)
  Process, Priority, % this.exe, % level
  return
}
shell_135(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/297").Call()) {
    return
  }
  WinRestore, % this.exe
  return
}
shell_136(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/298").Call()) {
    return
  }
  WinMinimize, % this.exe
  return
}
shell_137(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/299").Call()) {
    return
  }
  WinMaximize, % this.exe
  return
}
shell_138(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/300").Call()) {
    return
  }
  WinKill, % this.exe
  return
}
shell_139(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/301").Call()) {
    return false
  }
  __object__ := __rf_shell__.Call(this.getBounds, "#rf/shell/302").Call()
  x := __object__["x"]
  y := __object__["y"]
  width := __object__["width"]
  height := __object__["height"]
  return x == 0 && y == 0 && width == A_ScreenWidth && height == A_ScreenHeight
}
shell_140(this) {
  return WinExist(this.exe)
}
shell_141(this) {
  return WinActive(this.exe)
}
shell_142(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/303").Call()) {
    return
  }
  WinHide, % this.exe
  return
}
shell_143(this) {
  __array__ := [0, 0, 0, 0]
  __x__ := __array__[1]
  __y__ := __array__[2]
  __w__ := __array__[3]
  __h__ := __array__[4]
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/304").Call()) {
    return {x: __x__, y: __y__, width: __w__, height: __h__}
  }
  WinGetPos, __x__, __y__, __w__, __h__, % this.exe
  return {x: __x__, y: __y__, width: __w__, height: __h__}
}
shell_144(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/305").Call()) {
    return
  }
  WinActivate, % this.exe
  return
}
shell_145(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/306").Call()) {
    return
  }
  WinClose, % this.exe
  return
}
shell_146(this) {
  name := "ahk_class Shell_TrayWnd"
  __rf_shell__.Call(__noop__, "#rf/shell/307").Call(name)
  WinActivate, % name
  return
}
shell_147(this, __n__) {
  return Round(__n__)
}
shell_148(this, __number__*) {
  return Min(__number__*)
}
shell_149(this, __number__*) {
  return Max(__number__*)
}
shell_150(this, __n__) {
  return Floor(__n__)
}
shell_151(this, __n__) {
  return Ceil(__n__)
}
shell_152(this, __n__) {
  return Abs(__n__)
}
shell_153(this, content) {
  __rf_shell__.Call(this.remove, "#rf/shell/308").Call()
  __rf_shell__.Call(this.append, "#rf/shell/309").Call(content)
  return
}
shell_154(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/310").Call()) {
    return
  }
  FileDelete, % this.source
  return
}
shell_155(this) {
  if !(__rf_shell__.Call(this.isExists, "#rf/shell/311").Call()) {
    return ""
  }
  __result__ := ""
  FileRead, __result__, % this.source
  return __rf_shell__.Call(__replace__, "#rf/shell/312").Call(__result__, "`r", "")
}
shell_156(this) {
  return FileExist(this.source)
}
shell_157(this, content) {
  __rf_shell__.Call(__noop__, "#rf/shell/313").Call(content)
  FileAppend, % content, % this.source, UTF-8
  return
}
shell_158() {
  __toUpperCase__ := __shell_module_100__
  return __toUpperCase__
}
shell_159() {
  __toLowerCase__ := __shell_module_95__
  return __toLowerCase__
}
shell_160(text, iStart, iEnd := 0) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/314").Call(text)
  if !(__type__ == "string") {
    throw "$.subString: invalid type '" . (__type__) . "'"
  }
  if (iEnd) {
    __len__ := iEnd - iStart
  } else {
    __len__ := 0
  }
  if !(__len__) {
    return SubStr(text, iStart + 1)
  } else {
    return SubStr(text, iStart + 1, __len__)
  }
}
shell_161() {
  __getType__ := __shell_module_36__
  return Func("shell_160")
}
shell_162(__min__ := 0, __max__ := 1) {
  __result__ := 0
  __rf_shell__.Call(__noop__, "#rf/shell/315").Call(__min__, __max__)
  Random, __result__, __min__, __max__
  return __result__
}
shell_163() {
  __noop__ := __shell_module_60__
  return Func("shell_162")
}
shell_164(filename) {
  __rf_shell__.Call(__noop__, "#rf/shell/316").Call(filename)
  SoundPlay, % filename
  return
}
shell_165() {
  __noop__ := __shell_module_60__
  return Func("shell_164")
}
shell_166(source) {
  __rf_shell__.Call(__noop__, "#rf/shell/317").Call(source)
  Run, % source
  return
}
shell_167() {
  __noop__ := __shell_module_60__
  return Func("shell_166")
}
shell_168(p := "", speed := 0) {
  if !(p) {
    return
  }
  __rf_shell__.Call(__noop__, "#rf/shell/318").Call(speed)
  MouseMove, p[1], p[2], speed
  return
}
shell_169() {
  __noop__ := __shell_module_60__
  return Func("shell_168")
}
shell_170(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/319").Call(ipt)
  if !(__type__ == "string") {
    return false
  }
  return true
}
shell_171() {
  __getType__ := __shell_module_36__
  return Func("shell_170")
}
shell_172(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/320").Call(ipt)
  if !(__type__ == "object") {
    return false
  }
  return true
}
shell_173() {
  __getType__ := __shell_module_36__
  return Func("shell_172")
}
shell_174(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/321").Call(ipt)
  if !(__type__ == "number") {
    return false
  }
  return true
}
shell_175() {
  __getType__ := __shell_module_36__
  return Func("shell_174")
}
shell_176(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/322").Call(ipt)
  if !(__type__ == "function") {
    return false
  }
  return true
}
shell_177() {
  __getType__ := __shell_module_36__
  return Func("shell_176")
}
shell_178(ipt) {
  __type__ := __rf_shell__.Call(__getType__, "#rf/shell/323").Call(ipt)
  if !(__type__ == "array") {
    return false
  }
  return true
}
shell_179() {
  __getType__ := __shell_module_36__
  return Func("shell_178")
}
shell_180() {
  __first__ := __shell_module_30__
  return __first__
}
shell_181() {
  __array__ := [0, 0]
  __x__ := __array__[1]
  __y__ := __array__[2]
  MouseGetPos, __x__, __y__
  return __rf_shell__.Call(__toTuple__, "#rf/shell/324").Call([__x__, __y__])
}
shell_182() {
  __toTuple__ := __shell_module_98__
  return Func("shell_181")
}
shell_183() {
  __each__ := __shell_module_20__
  return __each__
}
shell_184(source, start, end) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  __array__ := [0, 0]
  __x__ := __array__[1]
  __y__ := __array__[2]
  __rf_shell__.Call(__noop__, "#rf/shell/325").Call(source)
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
shell_185() {
  __noop__ := __shell_module_60__
  return Func("shell_184")
}
shell_186(color, start, end, variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  __array__ := [0, 0]
  __x__ := __array__[1]
  __y__ := __array__[2]
  __rf_shell__.Call(__noop__, "#rf/shell/326").Call(color, variation)
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
shell_187() {
  __noop__ := __shell_module_60__
  return Func("shell_186")
}
shell_188(text, callback) {
  __rf_shell__.Call(__noop__, "#rf/shell/327").Call(text, callback)
  MsgBox, 0x4,, % text
  IfMsgBox Yes
    callback.Call(true)
  else
    callback.Call(false)
  return
}
shell_189() {
  __noop__ := __shell_module_60__
  return Func("shell_188")
}
shell_190(key := "left") {
  key := __rf_shell__.Call(__replace__, "#rf/shell/328").Call(key, "-", "")
  key := __rf_shell__.Call(__replace__, "#rf/shell/329").Call(key, ":", " ")
  Click, % key
  return
}
shell_191() {
  __replace__ := __shell_module_75__
  return Func("shell_190")
}
shell_192(message) {
  __rf_shell__.Call(__noop__, "#rf/shell/330").Call(message)
  MsgBox, % message
  return
}
shell_193() {
  __noop__ := __shell_module_60__
  return Func("shell_192")
}
shell_194(ipt, omitting := " `t") {
  return LTrim(ipt, omitting)
}
shell_195() {
  return Func("shell_194")
}
shell_196(ipt, omitting := " `t") {
  return RTrim(ipt, omitting)
}
shell_197() {
  return Func("shell_196")
}
shell_198(ipt, omitting := " `t") {
  return Trim(ipt, omitting)
}
shell_199() {
  return Func("shell_198")
}
shell_200(ipt) {
  __result__ := ipt
  StringUpper, __result__, ipt
  return __result__
}
shell_201() {
  return Func("shell_200")
}
shell_202(ipt) {
  return ipt
}
shell_203() {
  return Func("shell_202")
}
shell_204(ipt) {
  return ipt
}
shell_205() {
  return Func("shell_204")
}
shell_206(ipt) {
  __result__ := ipt
  StringLower, __result__, ipt
  return __result__
}
shell_207() {
  return Func("shell_206")
}
shell_208(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
  return
}
shell_209() {
  return Func("shell_208")
}
shell_210(list) {
  __result__ := 0
  for __index_for__, __n__ in list {
    __result__ := __result__ + __n__
  }
  return __result__
}
shell_211() {
  return Func("shell_210")
}
shell_212(text, string) {
  return (InStr(text, string)) == 1
}
shell_213() {
  return Func("shell_212")
}
shell_214(ipt, delimiter) {
  return StrSplit(ipt, delimiter)
}
shell_215() {
  return Func("shell_214")
}
shell_216(time) {
  if !(time > 0) {
    throw "$.sleep: time is required"
  }
  Sleep, % time
  return
}
shell_217() {
  return Func("shell_216")
}
shell_218(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
  return
}
shell_219() {
  return Func("shell_218")
}
shell_220(ipt, searchment, replacement, limit := -1) {
  return StrReplace(ipt, searchment, replacement, limit)
}
shell_221() {
  return Func("shell_220")
}
shell_222() {
  Reload
  return
}
shell_223() {
  return Func("shell_222")
}
shell_224(__cacheOnce__, __i__, callback, args*) {
  if (__cacheOnce__[__ci_shell__.Call(__i__)][1]) {
    return __cacheOnce__[__ci_shell__.Call(__i__)][2]
  }
  __result__ := __rf_shell__.Call(callback, "#rf/shell/331").Call(args*)
  __cacheOnce__[__ci_shell__.Call(__i__)] := [true, __result__]
  return __result__
}
shell_225(__indexOnce__, __cacheOnce__, callback) {
  __i__ := __indexOnce__
  __indexOnce__++
  __cacheOnce__[__ci_shell__.Call(__i__)] := [false, ""]
  return Func("shell_224").Bind(__cacheOnce__, __i__, callback)
}
shell_226() {
  __cacheOnce__ := {}
  __indexOnce__ := 0
  return Func("shell_225").Bind(__indexOnce__, __cacheOnce__)
}
shell_227() {
  return A_TickCount
}
shell_228() {
  return Func("shell_227")
}
shell_229(args*) {
  return
}
shell_230() {
  return Func("shell_229")
}
shell_231(dividend, divisor) {
  return Mod(dividend, divisor)
}
shell_232() {
  return Func("shell_231")
}
shell_233(list) {
  return Min(list*)
}
shell_234() {
  return Func("shell_233")
}
shell_235(list) {
  return Max(list*)
}
shell_236() {
  return Func("shell_235")
}
shell_237(value, other) {
  return value <= other
}
shell_238() {
  return Func("shell_237")
}
shell_239(value, other) {
  return value < other
}
shell_240() {
  return Func("shell_239")
}
shell_241(url, callback) {
  try {
    whr := ComObjCreate("WinHttp.WinHttpRequest.5.1")
    whr.Open("GET", url, true)
    whr.Send()
    whr.WaitForResponse()
    __rf_shell__.Call(callback, "#rf/shell/332").Call(whr.ResponseText)
  } catch {
    __rf_shell__.Call(callback, "#rf/shell/333").Call("")
  }
  return
}
shell_242() {
  return Func("shell_241")
}
shell_243(value, other) {
  return value >= other
}
shell_244() {
  return Func("shell_243")
}
shell_245(value, other) {
  return value > other
}
shell_246() {
  return Func("shell_245")
}
shell_247(ipt) {
  if ipt is Number
    return "number"
  if (IsFunc(ipt)) {
    return "function"
  }
  if (IsObject(ipt)) {
    if (ipt.Count() == ipt.Length()) {
      if !(ipt.Length() >= 0) {
        return "function"
      }
      return "array"
    }
    return "object"
  }
  return "string"
}
shell_248() {
  return Func("shell_247")
}
shell_249(list) {
  return list[1]
}
shell_250() {
  return Func("shell_249")
}
shell_251() {
  ExitApp
  return
}
shell_252() {
  return Func("shell_251")
}
shell_253(list, callback) {
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    __rf_shell__.Call(callback, "#rf/shell/334").Call(__item__, __i__)
  }
  return
}
shell_254() {
  return Func("shell_253")
}
shell_255(__target__, __keys__*) {
  for __index_for__, __k__ in __keys__ {
    __target__.Delete(__k__)
  }
  return
}
shell_256() {
  return Func("shell_255")
}
shell_257(__type__ := "unknown") {
  return []
}
shell_258() {
  return Func("shell_257")
}
shell_259(callback) {
  if !(callback) {
    return
  }
  setTimer, % callback, Delete
  return
}
shell_260() {
  return Func("shell_259")
}
shell_261(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
  return
}
shell_262() {
  return Func("shell_261")
}
shell_263(isBlocked) {
  if (isBlocked) {
    BlockInput, On
    return
  }
  BlockInput, Off
  return
}
shell_264() {
  return Func("shell_263")
}
shell_265() {
  SoundBeep
  return
}
shell_266() {
  return Func("shell_265")
}
shell_267(args*) {
  __result__ := 0
  for __index_for__, __arg__ in args {
    __result__ := __result__ + __arg__
  }
  return __result__
}
shell_268() {
  return Func("shell_267")
}
shell_269(__ipt__) {
  if __ipt__ is Number
    return __ipt__ + 1
  return __ipt__
}
shell_270(__fn__, __token__) {
  if (__fn__) {
    return __fn__
  }
  throw Exception("invalid function: " . (__token__) . "")
}
