; Generated by Coffee-AHK/0.0.37
global __ci_shell__ := Func("shell_83")
global $ := {}
$.abs := Func("shell_82")
$.alert := Func("shell_81")
$.beep := Func("shell_80")
$.blockInput := Func("shell_79")
$.ceil := Func("shell_78")
$.clearInterval := Func("shell_77")
$.clearTimeout := Func("shell_76")
$.click := Func("shell_75")
$.clone := Func("shell_74")
$.compact := Func("shell_73")
$.concat := Func("shell_72")
global __iDebounce__ := 0
global __tDebounce__ := {}
$.debounce := Func("shell_71")
$.delay := Func("shell_69")
$.drop := Func("shell_68")
class EmitterShellX {
  bus := []
  emit := Func("shell_67").Bind(this)
  off := Func("shell_66").Bind(this)
  on := Func("shell_65").Bind(this)
}
$.emitter := Func("shell_64")
$.exit := Func("shell_63")
class FileShellX {
  name := ""
  __New(name) {
    this.name := name
  }
  append := Func("shell_62").Bind(this)
  exist := Func("shell_61").Bind(this)
  delete := Func("shell_60").Bind(this)
  load := Func("shell_59").Bind(this)
  save := Func("shell_58").Bind(this)
}
$.file := Func("shell_57")
$.findColor := Func("shell_56")
$.findImage := Func("shell_55")
$.first := Func("shell_54")
$.floor := Func("shell_53")
$.formatHotkey := Func("shell_52")
$.getColor := Func("shell_51")
$.getPosition := Func("shell_50")
$.getState := Func("shell_49")
$.i := Func("shell_48")
$.includes := Func("shell_47")
$.info := Func("shell_46")
$.isArray := Func("shell_45")
$.isFunction := Func("shell_44")
$.isNumber := Func("shell_43")
$.isObject := Func("shell_42")
$.isString := Func("shell_41")
$.join := Func("shell_40")
class KeyBindingShellX {
  mapBound := {}
  mapCallback := {}
  add := Func("shell_39").Bind(this)
  fire := Func("shell_38").Bind(this)
  init := Func("shell_37").Bind(this)
  off := Func("shell_35").Bind(this)
  on := Func("shell_34").Bind(this)
  remove := Func("shell_33").Bind(this)
}
global keyBindingShell := new KeyBindingShellX()
$.off := keyBindingShell.remove
$.on := keyBindingShell.add
$.trigger := keyBindingShell.fire
$.last := Func("shell_32")
$.length := Func("shell_31")
$.move := Func("shell_30")
$.now := Func("shell_29")
$.nth := Func("shell_28")
$.open := Func("shell_27")
$.play := Func("shell_26")
$.press := Func("shell_25")
$.push := Func("shell_24")
$.random := Func("shell_23")
$.reload := Func("shell_22")
$.replace := Func("shell_21")
$.reverse := Func("shell_20")
$.round := Func("shell_19")
$.setFixed := Func("shell_18")
$.setInterval := Func("shell_17")
$.setTimeout := Func("shell_16")
$.sleep := Func("shell_15")
$.split := Func("shell_14")
$.suspend := Func("shell_13")
$.tail := Func("shell_12")
$.take := Func("shell_11")
global __iThrottle__ := 0
global __tThrottle__ := {}
global __tsThrottle__ := {}
$.throttle := Func("shell_10")
$.toLowerCase := Func("shell_7")
$.toString := Func("shell_6")
$.toUpperCase := Func("shell_5")
$.trim := Func("shell_4")
$.trimEnd := Func("shell_3")
$.trimStart := Func("shell_2")
$.type := Func("shell_1")
$.VERSION := "0.0.3"
shell_1(input) {
  if input is Number
    return "number"
  if (IsFunc(input)) {
    return "function"
  }
  if (IsObject(input)) {
    if (input.Count() == input.Length()) {
      return "array"
    }
    return "object"
  }
  return "string"
}
shell_2(input, omitting := " `t") {
  return LTrim(input, omitting)
}
shell_3(input, omitting := " `t") {
  return RTrim(input, omitting)
}
shell_4(input, omitting := " `t") {
  return Trim(input, omitting)
}
shell_5(input) {
  StringUpper, __result__, input
  return __result__
}
shell_6(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in input {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in input {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return input
}
shell_7(input) {
  StringLower, __result__, input
  return __result__
}
shell_8(callback, index) {
  callback.Call()
  __tsThrottle__[__ci_shell__.Call(index)] := $.now.Call()
}
shell_9(callback, time, index) {
  $.clearTimeout.Call(__tThrottle__[__ci_shell__.Call(index)])
  __tThrottle__[__ci_shell__.Call(index)] := $.setTimeout.Call(Func("shell_8").Bind(callback, index), __tsThrottle__[__ci_shell__.Call(index)] - $.now.Call() + time)
}
shell_10(time, callback) {
  __iThrottle__++
  __tsThrottle__[__ci_shell__.Call(__iThrottle__)] := 0
  return Func("shell_9").Bind(callback, time, __iThrottle__)
}
shell_11(list, count := 1) {
  if !($.isArray.Call(list)) {
    throw Exception("$.take: invalid type")
  }
  __len__ := $.length.Call(list)
  if !(__len__) {
    return []
  }
  if !(count >= 0) {
    return []
  }
  if (count >= __len__) {
    count := __len__
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if (__i__ >= count) {
      break
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_12(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.tail: invalid type")
  }
  return $.drop.Call(list, 1)
}
shell_13(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
shell_14(input, delimiter) {
  return StrSplit(input, delimiter)
}
shell_15(time) {
  Sleep, % time
}
shell_16(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if (time <= 0) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
shell_17(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if !(time > 0) {
    throw Exception("setTimeout: invalid time value '" . (time) . "'")
  }
  SetTimer, % callback, % time
  return callback
}
shell_18(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
shell_19(n) {
  return Round(n)
}
shell_20(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.reverse: invalid type")
  }
  __len__ := $.length.Call(list)
  __listNew__ := []
  for __i__, __key__ in list {
    __i__ := __i__ - 1
    __listNew__[__ci_shell__.Call(__len__ - 1 - __i__)] := __key__
  }
  return __listNew__
}
shell_21(input, searchment, replacement, limit := -1) {
  return StrReplace(input, searchment, replacement, limit)
}
shell_22() {
  Reload
}
shell_23(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
shell_24(list, args*) {
  if !($.isArray.Call(list)) {
    throw Exception("$.push: invalid type")
  }
  for __index_for__, __arg__ in args {
    list.Push(__arg__)
  }
  return list
}
shell_25(listInput*) {
  if !($.length.Call(listInput)) {
    throw Exception("$.press: invalid key")
  }
  __listKey__ := []
  for __index_for__, __input__ in listInput {
    __ipt__ := $.toLowerCase.Call(__input__)
    __ipt__ := $.replace.Call(__ipt__, " ", "")
    __ipt__ := $.replace.Call(__ipt__, "-", "")
    __list__ := $.split.Call(__ipt__, "+")
    for __index_for__, __it__ in __list__ {
      $.push.Call(__listKey__, __it__)
    }
  }
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for __i__, __key__ in __listKey__ {
    __i__ := __i__ - 1
    if (__i__ == __len__ - 1) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      continue
    }
    if ($.includes.Call(__key__, ":")) {
      __listResult__[__ci_shell__.Call(__i__)] := $.split.Call(__key__, ":")
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := $.split.Call(__key__, ":")
    } else {
      __listResult__[__ci_shell__.Call(__i__)] := [__key__, "down"]
      __listResult__[__ci_shell__.Call((__len__ - 1) * 2 - __i__)] := [__key__, "up"]
    }
  }
  for __i__, __it__ in __listResult__ {
    __i__ := __i__ - 1
    if (__it__[1] == "win") {
      __it__[1] := "lwin"
    }
    __listResult__[__ci_shell__.Call(__i__)] := $.trim.Call("" . (__it__[1]) . " " . (__it__[2]) . "")
  }
  __result__ := ""
  for __index_for__, __it__ in __listResult__ {
    __result__ := "" . (__result__) . "{" . (__it__) . "}"
  }
  Send, % __result__
}
shell_26(filename) {
  SoundPlay, % filename
}
shell_27(source) {
  Run, % source
}
shell_28(list, n := 0) {
  if !($.isArray.Call(list)) {
    throw Exception("$.nth: invalid type")
  }
  if !($.isNumber.Call(n)) {
    throw Exception("$.nth: invalid type")
  }
  if (n >= 0) {
    return list[__ci_shell__.Call(n)]
  } else {
    return list[__ci_shell__.Call(($.length.Call(list)) + n)]
  }
}
shell_29() {
  return A_TickCount
}
shell_30(point := "", speed := 0) {
  if !(point) {
    throw Exception("$.move: invalid point")
  }
  MouseMove, point[1], point[2], speed
}
shell_31(input) {
  __type__ := $.type.Call(input)
  switch __type__ {
    case "array": {
      return input.Length()
    }
    case "object": {
      return input.Count()
    }
    case "string": {
      return StrLen(input)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
shell_32(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.last: invalid type")
  }
  return list[__ci_shell__.Call(($.length.Call(list)) - 1)]
}
shell_33(this, key) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return $
  }
  __listNew__ := []
  for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
    if (__item__[1] == __name__) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  if !($.length.Call(__listNew__)) {
    this.mapCallback[__ci_shell__.Call(key)] := ""
    this.off.Call(key, this.mapBound[__ci_shell__.Call(key)])
    return $
  }
  this.mapCallback[__ci_shell__.Call(key)] := __listNew__
  return $
}
shell_34(this, key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, On
  return $
}
shell_35(this, key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, Off
  return $
}
shell_36(key, this) {
  this.fire.Call(key)
}
shell_37(this, key) {
  if (this.mapCallback[__ci_shell__.Call(key)]) {
    return $
  }
  this.mapCallback[__ci_shell__.Call(key)] := []
  __fn__ := Func("shell_36").Bind(key, this)
  this.mapBound[__ci_shell__.Call(key)] := __fn__
  this.on.Call(key, __fn__)
}
shell_38(this, key) {
  __array__ := $.split.Call(($.replace.Call(key, ":down", "")), ".")
  key := __array__[1]
  __name__ := __array__[2]
  if !(__name__) {
    for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
      __item__[2].Call()
    }
    return $
  }
  for __index_for__, __item__ in this.mapCallback[__ci_shell__.Call(key)] {
    if !(__item__[1] == __name__) {
      continue
    }
    __item__[2].Call()
  }
  return $
}
shell_39(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  key := __array__[1]
  __name__ := __array__[2]
  this.init.Call(key)
  $.push.Call(this.mapCallback[__ci_shell__.Call(key)], [__name__, callback])
  return $
}
shell_40(list, seperator := "") {
  if !($.isArray.Call(list)) {
    throw Exception("$.join: invalid type")
  }
  __result__ := ""
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__) {
      __result__ := __item__
      continue
    }
    __result__ := "" . (__result__) . "" . (seperator) . "" . (__item__) . ""
  }
  return __result__
}
shell_41(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "string") {
    return false
  }
  return true
}
shell_42(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "object") {
    return false
  }
  return true
}
shell_43(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "number") {
    return false
  }
  return true
}
shell_44(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "function") {
    return false
  }
  return true
}
shell_45(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "array") {
    return false
  }
  return true
}
shell_46(message, point := "") {
  if !(message) {
    return message
  }
  if !(point) {
    point := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % point[1], % point[2]
  return message
}
shell_47(input, needle) {
  __type__ := $.type.Call(input)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(input, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, __it__ in input {
      if (__it__ == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
shell_48(message) {
  $.info.Call("[" . ($.now.Call()) . "] " . ($.toString.Call(message)) . "", [0, 0])
  return message
}
shell_49(key) {
  key := $.formatHotkey.Call(key)
  return GetKeyState(key, "P")
}
shell_50() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
shell_51(point := "") {
  if !(point) {
    point := $.getPosition.Call()
  }
  PixelGetColor, __result__, % point[1], % point[2], RGB
  return __result__
}
shell_52(key) {
  __listKey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  for __index_for__, __it__ in $.split.Call(__key__, "+") {
    $.push.Call(__listKey__, __it__)
  }
  __isAlt__ := false
  __isCtrl__ := false
  __isShift__ := false
  __isWin__ := false
  __listResult__ := []
  for __index_for__, key in __listKey__ {
    if (key == "alt") {
      __isAlt__ := true
      continue
    }
    if (key == "ctrl") {
      __isCtrl__ := true
      continue
    }
    if (key == "shift") {
      __isShift__ := true
      continue
    }
    if (key == "win") {
      __isWin__ := true
      continue
    }
    $.push.Call(__listResult__, key)
  }
  __prefix__ := ""
  if (__isAlt__) {
    __prefix__ := "" . (__prefix__) . "!"
  }
  if (__isCtrl__) {
    __prefix__ := "" . (__prefix__) . "^"
  }
  if (__isShift__) {
    __prefix__ := "" . (__prefix__) . "+"
  }
  if (__isWin__) {
    __prefix__ := "" . (__prefix__) . "#"
  }
  __result__ := ""
  for __index_for__, __it__ in __listResult__ {
    __result__ := "" . (__result__) . " & " . (__it__) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
shell_53(n) {
  return Floor(n)
}
shell_54(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.first: invalid type")
  }
  return list[1]
}
shell_55(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
shell_56(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
shell_57(name) {
  return new FileShellX(name)
}
shell_58(this, content) {
  this.delete.Call()
  return this.append.Call(content)
}
shell_59(this) {
  if !(this.exist.Call()) {
    return ""
  }
  FileRead, __result__, % this.name
  return $.replace.Call(__result__, "`r", "")
}
shell_60(this) {
  if !(this.exist.Call()) {
    return this
  }
  FileDelete, % this.name
  return this
}
shell_61(this) {
  if !(FileExist(this.name)) {
    return false
  }
  return true
}
shell_62(this, content) {
  FileAppend, % content, % this.name, UTF-8
  return content
}
shell_63() {
  ExitApp
}
shell_64() {
  return new EmitterShellX
}
shell_65(this, key, callback) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  $.push.Call(this.bus, [__type__, __name__, callback])
  return this
}
shell_66(this, key) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    this.bus := []
    return this
  }
  if !(__name__) {
    __busNew__ := []
    for __index_for__, __item__ in this.bus {
      if (__item__[1] == __type__) {
        continue
      }
      $.push.Call(__busNew__, __item__)
    }
    this.bus := __busNew__
    return this
  }
  __busNew__ := []
  for __index_for__, __item__ in this.bus {
    if (__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    $.push.Call(__busNew__, __item__)
  }
  this.bus := __busNew__
  return this
}
shell_67(this, key, args*) {
  __array__ := $.split.Call(key, ".")
  __type__ := __array__[1]
  __name__ := __array__[2]
  if !(__type__) {
    return this
  }
  if !(__name__) {
    for __index_for__, __item__ in this.bus {
      if !(__item__[1] == __type__) {
        continue
      }
      __item__[3].Call(args*)
    }
    return this
  }
  for __index_for__, __item__ in this.bus {
    if !(__item__[1] == __type__ && __item__[2] == __name__) {
      continue
    }
    __item__[3].Call(args*)
  }
  return this
}
shell_68(list, n := 1) {
  if !($.isArray.Call(list)) {
    throw Exception("$.drop: invalid type")
  }
  __listNew__ := []
  for __i__, __item__ in list {
    __i__ := __i__ - 1
    if !(__i__ >= n) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_69(time, callback) {
  __timer__ := $.setTimeout.Call(callback, time)
  return __timer__
}
shell_70(callback, time, index) {
  $.clearTimeout.Call(__tDebounce__[__ci_shell__.Call(index)])
  __tDebounce__[__ci_shell__.Call(index)] := $.setTimeout.Call(callback, time)
}
shell_71(time, callback) {
  __iDebounce__++
  return Func("shell_70").Bind(callback, time, __iDebounce__)
}
shell_72(list, args*) {
  if !($.isArray.Call(list)) {
    throw Exception("$.concat: invalid type")
  }
  __listNew__ := $.clone.Call(list)
  for __index_for__, __arg__ in args {
    __type__ := $.type.Call(__arg__)
    if (__type__ == "array") {
      for __index_for__, __item__ in __arg__ {
        $.push.Call(__listNew__, __item__)
      }
    } else {
      $.push.Call(__listNew__, __arg__)
    }
  }
  return __listNew__
}
shell_73(list) {
  if !($.isArray.Call(list)) {
    throw Exception("$.compact: invalid type")
  }
  __listNew__ := []
  for __index_for__, __item__ in list {
    if !(__item__) {
      continue
    }
    $.push.Call(__listNew__, __item__)
  }
  return __listNew__
}
shell_74(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __listNew__ := []
    for __index_for__, __item__ in input {
      $.push.Call(__listNew__, __item__)
    }
    return __listNew__
  }
  if (__type__ == "object") {
    __mapNew__ := {}
    for __key__, __value__ in input {
      __mapNew__[__ci_shell__.Call(__key__)] := __value__
    }
    return __mapNew__
  }
  throw Exception("$.clone: invalid type '" . (__type__) . "'")
}
shell_75(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
shell_76(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_77(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
shell_78(n) {
  return Ceil(n)
}
shell_79(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
shell_80() {
  SoundBeep
}
shell_81(message := "") {
  __msg__ := $.toString.Call(message)
  MsgBox, % __msg__
  return message
}
shell_82(n) {
  return Abs(n)
}
shell_83(input) {
  if input is Number
    return input + 1
  return input
}
