# @ts-check

import $abs from './include/abs'
import $add from './include/add'
import $admin from './include/admin'
import $alert from './include/alert'
import $beep from './include/beep'
import $bind from './include/bind'
import $blockInput from './include/blockInput'
import $ceil from './include/ceil'
import $chunk from './include/chunk'
import $clearInterval from './include/clearInterval'
import $clearTimeout from './include/clearTimeout'
import $click from './include/click'
import $clone from './include/clone'
import $compact from './include/compact'
import $concat from './include/concat'
import $confirm from './include/confirm'
import $debounce from './include/debounce'
import $defer from './include/defer'
import $delay from './include/delay'
import $drop from './include/drop'
import $each from './include/each'
import $echo from './include/echo'
import $emitter from './include/emitter2'
import $eq from './include/eq'
import $exec from './include/exec'
import $exit from './include/exit'
import $file from './include/file2'
import $filter from './include/filter'
import $findColor from './include/findColor'
import $findImage from './include/findImage'
import $first from './include/first'
import $floor from './include/floor'
import $formatHotkey from './include/formatHotkey'
import $get from './include/get'
import $getColor from './include/getColor'
import $getPosition from './include/getPosition'
import $getState from './include/getState'
import $getType from './include/getType'
import $gt from './include/gt'
import $gte from './include/gte'
import $includes from './include/includes'
import $isArray from './include/isArray'
import $isFunction from './include/isFunction'
import $isNumber from './include/isNumber'
import $isObject from './include/isObject'
import $isString from './include/isString'
import $join from './include/join'
import $keys from './include/keys'
import $last from './include/last'
import $length from './include/length'
import $lt from './include/lt'
import $lte from './include/lte'
import $map from './include/map'
import $mixin from './include/mixin'
import $mod from './include/mod'
import $move from './include/move'
import $noop from './include/noop'
import $now from './include/now'
import $nth from './include/nth'
import $once from './include/once'
import $open from './include/open'
import $play from './include/play'
import $pop from './include/pop'
import $press from './include/press'
import $push from './include/push'
import $random from './include/random'
import $range from './include/range'
import $reload from './include/reload'
import $replace from './include/replace'
import $reverse from './include/reverse'
import $round from './include/round'
import $setFixed from './include/setFixed'
import $setInterval from './include/setInterval'
import $setTimeout from './include/setTimeout'
import $shift from './include/shift'
import $shuffle from './include/shuffle'
import $sleep from './include/sleep'
import $slice from './include/slice'
import $sort from './include/sort'
import $split from './include/split'
import $startsWith from './include/startsWith'
import $subString from './include/subString'
import $sum from './include/sum'
import $suspend from './include/suspend'
import $tail from './include/tail'
import $take from './include/take'
import $throttle from './include/throttle'
import $tip from './include/tip'
import $toLowerCase from './include/toLowerCase'
import $toString from './include/toString'
import $toUpperCase from './include/toUpperCase'
import $trim from './include/trim'
import $trimEnd from './include/trimEnd'
import $trimStart from './include/trimStart'
import $uniq from './include/uniq'
import $unshift from './include/unshift'
import $values from './include/values'
import $version from './include/version'
import $window from './include/window'
import './include/emitter'
import './include/file'

$ = {}

$mixin $, abs: $abs
$mixin $, add: $add
$mixin $, admin: $admin
$mixin $, alert: $alert
$mixin $, beep: $beep
$mixin $, bind: $bind
$mixin $, blockInput: $blockInput
$mixin $, ceil: $ceil
$mixin $, chunk: $chunk
$mixin $, clearInterval: $clearInterval
$mixin $, clearTimeout: $clearTimeout
$mixin $, click: $click
$mixin $, clone: $clone
$mixin $, compact: $compact
$mixin $, concat: $concat
$mixin $, confirm: $confirm
$mixin $, debounce: $debounce
$mixin $, defer: $defer
$mixin $, delay: $delay
$mixin $, drop: $drop
$mixin $, each: $each
$mixin $, echo: $echo
$mixin $, emitter: $emitter
$mixin $, eq: $eq
$mixin $, exec: $exec
$mixin $, exit: $exit
$mixin $, file: $file
$mixin $, filter: $filter
$mixin $, findColor: $findColor
$mixin $, findImage: $findImage
$mixin $, first: $first
$mixin $, floor: $floor
$mixin $, forEach: $each
$mixin $, formatHotkey: $formatHotkey
$mixin $, get: $get
$mixin $, getColor: $getColor
$mixin $, getPosition: $getPosition
$mixin $, getState: $getState
$mixin $, getType: $getType
$mixin $, gt: $gt
$mixin $, gte: $gte
$mixin $, head: $first
$mixin $, includes: $includes
$mixin $, isArray: $isArray
$mixin $, isFunction: $isFunction
$mixin $, isNumber: $isNumber
$mixin $, isObject: $isObject
$mixin $, isString: $isString
$mixin $, join: $join
$mixin $, keys: $keys
$mixin $, last: $last
$mixin $, length: $length
$mixin $, lt: $lt
$mixin $, lte: $lte
$mixin $, map: $map
$mixin $, mixin: $mixin
$mixin $, mod: $mod
$mixin $, move: $move
$mixin $, noop: $noop
$mixin $, now: $now
$mixin $, nth: $nth
$mixin $, once: $once
$mixin $, open: $open
$mixin $, play: $play
$mixin $, pop: $pop
$mixin $, press: $press
$mixin $, push: $push
$mixin $, random: $random
$mixin $, range: $range
$mixin $, reload: $reload
$mixin $, replace: $replace
$mixin $, reverse: $reverse
$mixin $, round: $round
$mixin $, setFixed: $setFixed
$mixin $, setInterval: $setInterval
$mixin $, setTimeout: $setTimeout
$mixin $, shift: $shift
$mixin $, shuffle: $shuffle
$mixin $, sleep: $sleep
$mixin $, slice: $slice
$mixin $, sort: $sort
$mixin $, split: $split
$mixin $, startsWith: $startsWith
$mixin $, subString: $subString
$mixin $, sum: $sum
$mixin $, suspend: $suspend
$mixin $, tail: $tail
$mixin $, take: $take
$mixin $, throttle: $throttle
$mixin $, tip: $tip
$mixin $, toLower: $toLowerCase
$mixin $, toLowerCase: $toLowerCase
$mixin $, toString: $toString
$mixin $, toUpper: $toUpperCase
$mixin $, toUpperCase: $toUpperCase
$mixin $, trim: $trim
$mixin $, trimEnd: $trimEnd
$mixin $, trimStart: $trimStart
$mixin $, uniq: $uniq
$mixin $, unshift: $unshift
$mixin $, values: $values
$mixin $, VERSION: $version
$mixin $, window: $window
